### PR TITLE
Update docs by running update-imported-docs.sh

### PR DESCRIPTION
**Pull request by bboreham**
My primary motivation is to get the `--cni-bin-dir` option documented, but it seems reasonable to bring everything up to date with the 1.4 release.

Evidently the script has also wiped `CertificateSigningRequest` and `StorageClass`.  I don't know much about those, or why they needed to be removed.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1455)

### CODE REVIEW

**Comment by janetkuo** [comment]
`cni-bin-dir` is on HEAD but not in 1.4 release. We usually only run this script during release process. @kubernetes/docs

**Comment by bboreham** [comment]
Beg to differ. 

https://github.com/kubernetes/kubernetes/blob/v1.4.0/cmd/kubelet/app/options/options.go#L152

**Comment by bboreham** [comment]
Also I ran the script off the 1.4 release tag.

**Comment by janetkuo** [comment]
Need @kubernetes/docs review

**Comment by devin-donnelly** [comment]
Looks like this is made irrelevant/obsolete by #1546. I'm going to close it.

**Pull request closed without merging**
