### PR TITLE
getting-started-guides-Kubespray-pr-2017-07-15

### PR DESCRIPTION
**Pull request by yufengqi**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4879)

### CODE REVIEW

**Comment by chenopis** [comment]
cc @markthink

**Comment by zhangxiaoyu-zidif** [comment]
@yufengqi 
please sign CLA :)

**Comment by zacharysarah** [comment]
@yufengqi :wave: A ping to sign the CLA agreement, please!

**Comment by steveperry-53** [comment]
Closing because we've waited long enough for the license to be signed. Please reopen if you want to sign the license agreement and move forward with this.

**Pull request closed without merging**
