### PR TITLE
Uc01

### PR DESCRIPTION
**Pull request by pete-uc**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.7 Features: set Milestone to `1.7` and Base Branch to `release-1.7`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3880)

### CODE REVIEW

**Comment by chenopis** [comment]
@pete-uc Can you give me more context for these changes? Are these coming from CNCF?

**Comment by pete-uc** [comment]
Andrew,

These changes are addressing the open items on the needs list at:
https://github.com/kubernetes/kubernetes.github.io/issues?q=is%3Aissue+label%3A%22Needs+UX+Review%22+is%3Aopen

Although we need to roll back #2293, since this will no longer be needed.  Can individual changes be rolled back, or is it best to start from a new fork & branch?

I am working with Jared Bhatti and Bob Hrdinsky on these changes.

Thanks,
Pete Miller
United Creations




________________________________

**Comment by chenopis** [comment]
@pete-uc Ok, cool. I just wanted to make sure I knew who to get approval from for this. I'll assign it to @jaredbhatti for review. Thx

**Comment by jaredbhatti** [comment]
This looks good, but you should roll back the index page changes.  Might be easier to start with a new fork

**Comment by chenopis** [comment]
@pete-uc Did you end up starting w/ a new fork? Should I close this PR?

**Comment by pete-uc** [comment]
@chenopis @jaredbhatti  I've committed changes on the uc01 branch which roll back the index page changes in 2293.

**Comment by chenopis** [comment]
@jaredbhatti Is this ready to be merged now?

**Comment by chenopis** [comment]
ping @jaredbhatti

**Comment by steveperry-53** [comment]
@jaredbhatti This looks OK to me. I'll leave it open for your comment for a few more days. Then I'll merge.

**Comment by jaredbhatti** [comment]
Cann't be rebased due to conflicts :(

**Comment by steveperry-53** [comment]
Fixes #2294.

**Pull request merged**
