### PR TITLE
Typo in StatefulSet tutorial text

### PR DESCRIPTION
**Pull request by andrewjamesmorgan**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3350)

### CODE REVIEW

**Comment by andrewjamesmorgan** [comment]
I signed the CLA a few minutes ago



On 12 April 2017 at 11:14:18, k8s-ci-robot (notifications@github.com) wrote:

Thanks for your pull request. Before we can look at your pull request,
you'll need to sign a Contributor License Agreement (CLA).

📝 *Please follow instructions at
https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ
<https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ> to sign the CLA.*

It may take a couple minutes for the CLA signature to be fully registered;
after that, please reply here with a new comment and we'll verify. Thanks.
------------------------------

   - If you've already signed a CLA, it's possible we don't have your
   GitHub username or you're using a different email address. Check your
   existing CLA data and verify that your email is set on your git commits
   <https://help.github.com/articles/setting-your-email-in-git/>.
   - If you signed the CLA as a corporation, please sign in with your
   organization's credentials at
   https://identity.linuxfoundation.org/projects/cncf to be authorized.

Instructions for interacting with me using PR comments are available here
<https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md>.
If you have questions or suggestions related to my behavior, please file an
issue against the kubernetes/test-infra
<https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
repository. I understand the commands that are listed here
<https://github.com/kubernetes/test-infra/blob/master/commands.md>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes.github.io/pull/3350#issuecomment-293534032>,
or mute the thread

**Comment by andrewjamesmorgan** [comment]
CLA submitted

**Comment by andrewjamesmorgan** [comment]
trying again

**Comment by andrewjamesmorgan** [comment]
trying again

**Comment by thelinuxfoundation** [comment]
bump for cla check

**Pull request merged**
