### PR TITLE
removing word that doesn't flow correctly

### PR DESCRIPTION
**Pull request by scollier**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2224)

### CODE REVIEW

**Comment by scollier** [comment]
"I signed it!" as an employee of Red Hat.

**Comment by chenopis** [comment]
@scollier not sure why it still says the CLA wasn't signed. Can you check on the Linux Foundation site again to make sure it went through? Also, I need you to rebase in order to pass the Travis check. There was a change in a previous version of master that broke Travis which has since been fixed. Thx

**Comment by chenopis** [comment]
@scollier ...and nevermind. It just cleared. =/ But please still rebase. Thx

**Comment by chenopis** [comment]
The Travis CI fail is related to a previous known issue unrelated to this PR, so I'm going to rebase and merge this.

**Pull request merged**
