### PR TITLE
Link to http://kubernetes.io/docs/admin/networking broken, formatting

### PR DESCRIPTION
**Pull request by CaptTofu**
hi there! The link on the live doc site for networking is broken. I moved the "toc" to the top, moved the text that needs to be below the summary into the first section on kubernetes networking

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1584)

### CODE REVIEW

**Comment by CaptTofu** [comment]
hi all, sorting out CLA

**Comment by CaptTofu** [comment]
@googlebot I signed it!

**Comment by mattfarina** [comment]
Note, @CaptTofu has a signed linuxfoundation CLA now. Not sure how to kick it to re-check. (comment and force-push did not do it)

**Comment by CaptTofu** [comment]
I signed it!

**Comment by CaptTofu** [comment]
@googlebot I signed it!

**Comment by chrismarino** [comment]
Actually, I think the broke link problem is because my client/editor changed the ' to an unsupported character in my PR (#1549). Specifically, the problem was with "other's" (line 86) and "doesn't" (line 166). This PR  may have changed it back to a valid character, but not really sure how to verify that.

**Comment by chrismarino** [comment]
Submitted a separate PR (#1605) to fix the invalid characters.  This PR still has them.

**Comment by CaptTofu** [comment]
Thanks - I thought it was the toc, but there's no way to test as gh-pages render differently than say a markdown editor. I assumed it was the toc issue after comparing with other docs.

**Pull request closed without merging**
