### PR TITLE
Update the title to Deployments, markdown not

### PR DESCRIPTION
**Pull request by oshalygin**
Markdown doesnt translate 100% to the kubernetes documentation.  The italicized title of "Deployments" just gets the underscores

Looks like this:
_Deployments_

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1998)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
This is fine, but we'll need you to sign the CLA before we can merge.

**Comment by oshalygin** [comment]
Signed license agreement!  Was on vacation, thanks ladies/gents

image

**Comment by janetkuo** [comment]
Looks like it's now fixed in `master`

**Comment by oshalygin** [comment]
@janetkuo thats fine! glad its resolved already 👍

**Pull request closed without merging**
