### PR TITLE
Fix spelling mistake.

### PR DESCRIPTION
**Pull request by ianfisk**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5506)

### CODE REVIEW

**Comment by ianfisk** [comment]
Overall the docs have been incredibly helpful. Thank you to the maintainers!

**Comment by ianfisk** [comment]
I have signed the CNCF CLA.

**Comment by xiangpengzhao** [comment]
/lgtm

Thanks for contribution!

**Comment by steveperry-53** [comment]
@ianfisk Please rebase your branch so that it picks up 99fbc2b. That will fix the deploy/netlify failure. Thanks.

**Comment by Bradamant3** [comment]
merging anyway -- tiny change for typo so seems safe.

**Pull request merged**
