### PR TITLE
Add python client to "Programmatic access to the API" section

### PR DESCRIPTION
**Pull request by mbohlool**
Python has a supported client library. Add documentation to use it.

reference https://github.com/kubernetes-incubator/client-python/issues/130

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2729)

### CODE REVIEW

**Comment by mbohlool** [comment]
@chenopis any updates on this? who should do the tech review?

**Comment by chenopis** [comment]
@mbohlool  Sorry, I'll track someone down today and assign them to the tech review.

**Comment by chenopis** [comment]
@mbohlool BTW, we are in the process of restructuring the documents, so `/docs/user-guide/accessing-the-cluster.md` has moved to `/docs/concepts/cluster-administration/access-cluster.md`. To resolve the conflict, please apply your changes there. Thx

**Comment by mikedanese** [comment]
Tech LGTM

**Comment by chenopis** [comment]
@mikedanese Thanks!

**Comment by chenopis** [comment]
@mbohlool If you can resolve the merge conflict as per my comment above, I should be able to merge this PR. Thx

**Comment by mbohlool** [comment]
@chenopis done. PTAL.

**Pull request merged**
