### PR TITLE
turn on travis for preformat balance

### PR DESCRIPTION
**Pull request by jessfraz**
updates https://github.com/kubernetes/kubernetes/issues/31264

to be merged after https://github.com/kubernetes/kubernetes.github.io/pull/1527

just want to make sure this fails correctly before that PR is merged

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1528)

### CODE REVIEW

**Comment by jessfraz** [comment]
perfect it failed in the way I wanted it to, so it should pass after the other PR is merged \o/

**Comment by lavalamp** [comment]
I am back so ping me after you rebase?

**Comment by jessfraz** [comment]
@lavalamp rebased, thanks!

**Comment by lavalamp** [comment]
Looks like travis is mad about the new entry!

**Comment by jaredbhatti** [comment]
Pingity ping.  What's the plan with this PR?  It's been a while.

**Comment by jessfraz** [comment]
whoa sorry will figure it out..

**Comment by jessfraz** [comment]
ok updated!

**Comment by lavalamp** [comment]
We should probably figure out a way of doing this that doesn't involve downloading the entire k8s repo at some point in the future...

**Comment by jessfraz** [comment]
for reals

**Pull request merged**
