### PR TITLE
Update minikube docs for v0.12.0 release

### PR DESCRIPTION
**Pull request by r2d4**
Hi, I'm a maintainer for minikube and I noticed the minikube docs are quite old on k8s.io.  I updated them to reflect the current docs on https://github.com/kubernetes/minikube/blob/master/README.md

I made a few modifications such as removing the developer specific parts of the readme and cleaning a few things up (the kubectl installation instructions)

cc @dlorenc @aaron-prindle

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1536)

### CODE REVIEW

**Comment by dlorenc** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1536#-:-KUsU02Y21g5TWZIcg0i:bnfp4nl)*

**Comment by r2d4** [comment]
@dlorenc Please take a look.  I've rebased, not sure what else is needed to get this merged.

https://deploy-preview-1536--kubernetes-io-vnext-staging.netlify.com/docs/getting-started-guides/minikube/

**Comment by dlorenc** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1536#-:-KWJHa_UWssxURIasQf4:bnfp4nl)*

**Comment by r2d4** [comment]
@janetkuo Friendly ping, what else do I need to do in order to get this merged?  Thanks!

**Comment by devin-donnelly** [comment]
I can't merge until you fix the merge conflict; otherwise it looks good.

**Comment by r2d4** [comment]
@devin-donnelly Thanks for taking a look!  I've rebased and fixed the merge conflicts

**Comment by waprin** [comment]
@jeffmendoza @devin-donnelly any reason this is getting held up (looks like at this point @r2d4 needs to rebase but besides that)

**Comment by janetkuo** [comment]
Manually merging

**Pull request merged**
