### PR TITLE
noted exclusivity of volume claims, namespacing particularities

### PR DESCRIPTION
**Pull request by pnovotnak**
Clears up some `ROX` `RWX` usage ambiguities.

Addresses the final outstanding issue captured in this ticket; https://github.com/kubernetes/kubernetes/issues/25828

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1046)

### CODE REVIEW

**Comment by jsafrane** [comment]
lgtm

**Comment by jsafrane** [comment]
@pwittrock, sorry to bother you, but I noticed you merged some doc PRs that were assigned to me. How can I merge this request? It seems I lack some permissions and assigning storage related PRs to me by default is kind of useless, I can't do anything with them.

**Comment by pwittrock** [comment]
@jsafrane good question.  Mainly we are looking for a tech review to make sure the content is technically accurate so the lgtm is what we are looking for.  Setting up a merge bot to automatically merge lgtm'ed PRs is the next step.  Thanks.

**Comment by pwittrock** [comment]
@pnovotnak Would merge the latest changes from master into your branch and update the PR?

**Comment by pnovotnak** [comment]
Sorry for the wait, done!

**Comment by pwittrock** [comment]
Thanks everyone.

**Pull request merged**
