### PR TITLE
Delete the parameter "--google-json-key string"

### PR DESCRIPTION
**Pull request by chenhuan12**
Delete the parameter "--google-json-key string"

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2571)

### CODE REVIEW

**Comment by chenopis** [comment]
@chenhuan12 Can you elaborate on why that flag option is being removed? Is it no longer supported? If so, can you point to a Kubernetes issue # or pull request # where that is mentioned? Thx

**Comment by chenhuan12** [comment]
“# kube-prxoy -help”can not find --google-json-key option
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"f5ef9802914a47c848fd84c287333f8b4d28bbc1", GitTreeState:"dirty", BuildDate:"2017-01-23T00:04:39Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64", USEEVersion:"V1.02.01_alpha", USEEPublishDate:"2017-1-10 00:00:00"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"f5ef9802914a47c848fd84c287333f8b4d28bbc1", GitTreeState:"dirty", BuildDate:"2017-01-22T23:56:57Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64", USEEVersion:"V1.02.01_alpha", USEEPublishDate:"2017-1-10 00:00:00"}

```

**Comment by chenopis** [comment]
@pwittrock Do you know what the deal is w/ --google-json-key for kube-proxy? Is that flag just hidden from kube-proxy -help? Who should I ask?

**Comment by pwittrock** [comment]
@yujuhong is this something you know about?

**Comment by thockin** [comment]
I have no idea what this flag was or why it was documented :)

**Comment by thockin** [comment]
It looks to be defined in pkg/credentialprovider/gcp/jwt.go, not sure why it would be in kube-proxy...

**Comment by chenopis** [comment]
@thockin So it's definitely okay to remove then, right?

**Comment by thockin** [comment]
I think so - it's not part of the current help text

**Pull request merged**
