### PR TITLE
Add default storage class documentation for 1.6

### PR DESCRIPTION
**Pull request by kerneltime**
fixes https://github.com/kubernetes/kubernetes/issues/40070

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2596)

### CODE REVIEW

**Comment by jbeda** [comment]
In my mind, it is much better to put the relevant data inline or on a new page vs directing people to github. But I'm okay with this as is as this is isolated to VMWare stuff.

**Comment by jbeda** [comment]
Can you rebase and drop the merge commit?  Generally we look for a clean set of commits as we merge to master.

**Comment by kerneltime** [comment]
Eh.. I used the edit functionality of GitHub for markdown to do this change. let me start a new PR.. I cannot push to this branch as such.

**Comment by kerneltime** [comment]
Will fix this

**Comment by kerneltime** [comment]
Fixed

**Comment by chenopis** [comment]
@kerneltime This is for the 1.6 release, right? If so, I can change the base to `release-1.6` and merge it there.

**Comment by kerneltime** [comment]
I do not mind but does it not need to be in the master as well?

**Comment by chenopis** [comment]
@kerneltime It will be. Once the k8s 1.6 release goes out, we will merge the `release-1.6` branch for the docs into `master`.

**Comment by chenopis** [comment]
Had to merge `master` into `release-1.6` before I could change the base.

**Pull request merged**
