### PR TITLE
Add Travis badge to README.md.

### PR DESCRIPTION
**Pull request by jeffmendoza**
Travis tests are merged:
Do we want a badge on the readme?

### CODE REVIEW

**Comment by jeffmendoza** [comment]
Or, instead, how do we get Travis to show up as a PR check now?

**Comment by janetkuo** [comment]
Haven't done this myself but this [tutorial](https://www.raywenderlich.com/109418/travis-ci-tutorial) looks like what we need

**Comment by jeffmendoza** [comment]
It looks like building PRs is disabled for this repo, if that was enabled, we would probably see the check.

**Comment by pwittrock** [comment]
@foxish Can you follow up on this?

**Comment by foxish** [comment]
@pwittrock I don't have privileges on the repository. I can find out what the steps are, and let someone with privileges execute them, if that's ok.

**Comment by pwittrock** [comment]
@foxish Yes that would be great.  Thank you.

**Comment by foxish** [comment]
I just turned on protected branches and required status checks for the master branch. 
We should see the checks occurring starting from the next PR.

**Comment by foxish** [comment]
@jeffmendoza Looks like you need to rebase.

**Comment by jeffmendoza** [comment]
@foxish Looks like the PRs are working with Travis. Do we want a badge? I'm leaning towards no.

**Comment by janetkuo** [comment]
@jeffmendoza I agree with you on not having the badge

**Comment by foxish** [comment]
Yeah, me too. I don't think the badge would serve any real purpose on this repo.

**Pull request closed without merging**
