### PR TITLE
Add deprecated docs warning mechanism

### PR DESCRIPTION
**Pull request by zoidbergwill**
This is the last piece of https://github.com/kubernetes/kubernetes.github.io/issues/3992

- [ ] `deprecated: true` in the config will need to be changed to `false` before merging into branch.

The version selector branch adds more version-specific stuff that could make this more dynamic, but if we had static URLs for development version and stable version then maintaining the stable and development URLs for deprecated versions would be easier.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4731)

### CODE REVIEW

**Comment by zoidbergwill** [comment]
I don't have access to see why the Netlify deploy failed.

**Comment by chenopis** [comment]
Ugh. Nevermind. The branches aren't synced up enough. Let's just keep this on `master` and remove the `/_configl.yml` changes before we merg.

**Comment by zoidbergwill** [comment]
@chenopis Awesome, thanks. I've enabled edits.

Yeah, I swear the red was different when I was originally testing it. It is from the callouts, but it works more as a border colour than a background. Sounds good.

**Comment by chenopis** [comment]
@zoidbergwill Ok, I think this looks good. If @steveperry-53 approves, we can turn off the `deprecated` flag then merge this into `master`.

**Comment by zoidbergwill** [comment]
Awesome, thanks @chenopis 🎉

**Comment by chenopis** [comment]
@zoidbergwill I think we're all set now. Thank you for all your work making the versioning UI and adding the deprecation warning!

**Pull request merged**
