### PR TITLE
Convert PROJECT_ID to a shell variable in hello-node shell snippets

### PR DESCRIPTION
**Pull request by ace-n**
As title; this should make following the tutorial ever-so-slightly more seamless.

### CODE REVIEW

**Comment by ace-n** [comment]
(Paging Googlebot.)

**Comment by ace-n** [comment]
I signed it!

**Comment by kelseyhightower** [comment]
@ace-n LGTM. Can you rebase this so I can get it merged?

**Comment by ace-n** [comment]
(I reapplied the changes proposed in this PR on top of a current checkout [as opposed to rebasing/resolving merge conflicts], so be sure to review/double-check before merging. Thanks!)

**Comment by kelseyhightower** [comment]
This looks good to me.

**Pull request merged**
