### PR TITLE
Wrong link to inside cluster k8s Go client example

### PR DESCRIPTION
**Pull request by diegodelemos**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1460)

### CODE REVIEW

**Comment by diegodelemos** [comment]
I signed it!

**Comment by devin-donnelly** [comment]
Need you to sign the new LinuxFoundation CLA.

**Comment by janetkuo** [comment]
Thanks @diegodelemos! There are still a bunch of obselete links to client-go. Would you fix them too?

```console
$ git grep kubernetes/client-go
docs/user-guide/accessing-the-cluster.md:The Kubernetes project-supported Go client library is at [https://github.com/kubernetes/client-go](https://github.com/kubernetes/client-go).
docs/user-guide/accessing-the-cluster.md:* To get the library, run the following command: `go get k8s.io/client-go/<version number>/kubernetes` See [https://github.com/kubernetes/client-go](https://github.com/kubernetes/client-go) to see which versions are supported.
docs/user-guide/accessing-the-cluster.md:as the kubectl CLI does to locate and authenticate to the apiserver. See this [example](https://github.com/kubernetes/client-go/examples/out-of-cluster.go):
docs/user-guide/accessing-the-cluster.md:    This handles locating and authenticating to the apiserver. [example](https://github.com/kubernetes/client-go/examples/in-cluster.go)
```

**Comment by devin-donnelly** [comment]
@diegodelemos , any updates?

**Comment by jaredbhatti** [comment]
Ping.  Please update.  If we don't hear from you in a week, we'll close this PR :(

**Comment by jaredbhatti** [comment]
Already updated: http://kubernetes.io/docs/user-guide/accessing-the-cluster/

Thanks for filing this change!

**Pull request closed without merging**
