### PR TITLE
Added a section to kubectl cheatsheet about verbosity levels

### PR DESCRIPTION
**Pull request by ianchakeres**
There have been a bunch of questions about verbosity level for kubectl (e.g. https://github.com/kubernetes/kubernetes/issues/35054). 

This PR adds a section to the kubectl cheatsheet with some basic information about using the -v and --v flags.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4186)

### CODE REVIEW

**Comment by ianchakeres** [comment]
@pwittrock - Please let me know if you have any comments or whether it looks good to you.

**Comment by janetkuo** [comment]
@kubernetes/sig-cli-misc

**Comment by pwittrock** [comment]
lgtm

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 51d19f271c5f5217d5e68418c997a5bd4de77f20

https://deploy-preview-4186--k8sio-v1-6.netlify.com

**Pull request merged**
