### PR TITLE
seo improvements: add custom plugin for page title generation

### PR DESCRIPTION
**Pull request by jessfraz**
Also did a few cleanups of the templates I am going to clean up more though

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1444)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
When checking how the documentation now renders in staging, it looks like the page titles are now formed off the directory structure. See this page for an example: http://deploy-preview-1444.kubernetes-io-vnext-staging.netlify.com/docs/user-guide/pods/multi-container/

I don't think we want to push that live.

What exactly is the plug-in doing?

**Comment by jessfraz** [comment]
yeah thats what it's doing, if the page has no title it tries to make one from the directory structure
this was an idea to work around the problems with some pages, for example kubectl, not having titles and messing with the seo
but open to other ideas

**Comment by devin-donnelly** [comment]
I would actually prefer to have page authors explicitly title their pages. Let's hold onto this PR for now; I'd like to discuss the titling strategy with a wider audience (specifically Jared Bhatti and Steve Perry).

**Comment by jessfraz** [comment]
makes sense!

**Pull request closed without merging**
