### PR TITLE
Minor typo

### PR DESCRIPTION
**Pull request by xarg**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2166)

### CODE REVIEW

**Comment by xarg** [comment]
I signed it!

**Comment by xarg** [comment]
I signed it!

**Comment by chenopis** [comment]
@xarg I am unable to see the file in the deploy/netlify preview. Where is it supposed to live/where are you getting it from exactly?

**Comment by chenopis** [comment]
Nevermind. I found it.

**Pull request merged**
