### PR TITLE
Update Kompose docs

### PR DESCRIPTION
**Pull request by cdrage**
This updates the current page of Kompose with our quickstart,
installation as well as user guide.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4437)

### CODE REVIEW

**Comment by cdrage** [comment]
@janetkuo @chenopis @pwittrock Could I get a review? Document still indicated 0.1.2 even though we've already reached 1.1.0

Would be great to get an update :+1:

**Comment by chenopis** [comment]
@cdrage Ok, all the changes look reasonable, so I can merge this once the conflicts have been resolved. Are there any other core maintainers for Kompose that can be a second pair of eyes on this? Since you're the de facto owner, I'm more okay w/ letting this through as is.

**Comment by chenopis** [comment]
Oh, also, yes. Since you are the core maintainer of Kompose and assignee at the top of the page, I'm fine w/ deferring judgment of changes in this section to you.

**Comment by cdrage** [comment]
Awesome. Thank you @chenopis 

I've gone ahead and resolved the conflicts.

**Pull request merged**
