### PR TITLE
Add links to AppsCode managed Kubernetes clusters.

### PR DESCRIPTION
**Pull request by TamalSaha**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1155)

### CODE REVIEW

**Comment by TamalSaha** [comment]
I have signed the Corp CLA for AppsCode Inc.

**Comment by TamalSaha** [comment]
I signed it!

**Comment by TamalSaha** [comment]
I signed it!

**Comment by devin-donnelly** [comment]
Looks fine. Should this go out right away, or should it wait until the next Kubernetes release (1.4)?

**Comment by devin-donnelly** [comment]
Also, would you mind rebasing?

**Comment by TamalSaha** [comment]
@devin-donnelly , I rebased. We would like it to go out right away. Can you accept the pr?

**Comment by TamalSaha** [comment]
@devin-donnelly , do you mind merging this change?

**Comment by erictune** [comment]
@TamalSaha can you squash this into 1 commit?   There should not be 6 commits for a few lines of changes.  Thanks.

**Comment by TamalSaha** [comment]
@erictune, I was using the "Update Branch" button on the webpage to fix conflicts. That created multiple commits. Now, I have squashed it. PTAL.

**Pull request merged**
