### PR TITLE
add docs about cloud-controller-manager

### PR DESCRIPTION
**Pull request by wlan0**
@thockin @luxas @idvoretskyi @jaredbhatti

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2900)

### CODE REVIEW

**Comment by thockin** [comment]
LGTM from content.

**Comment by devin-donnelly** [comment]
@wlan0 Since this PR needs a bunch of general grammar, usage, and formatting fixes, would you mind providing maintainers access to edit it? I can fix them pretty quickly and it would save us some back and forth.

**Comment by wlan0** [comment]
@devin-donnelly done

**Comment by devin-donnelly** [comment]
Added two commits for grammar, wording, and usage. Didn't change any technical content.

**Pull request merged**
