### PR TITLE
Add multi zone clarification for Ingress

### PR DESCRIPTION
**Pull request by bprashanth**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1239)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
Is this change only relevant to version 1.4? Can you please target the pull request to the release-1.4 branch?

**Comment by bprashanth** [comment]
It's valid for 1.4 onwards, still put it in release-1.4? or put it here and cherrypick it there/some variant of the same?

**Comment by devin-donnelly** [comment]
If it's valid for 1.4 onwards, it needs to be in release-1.4 to avoid being published early.

**Comment by bprashanth** [comment]
right but it also needs to be in HEAD (meaning this pr goes in) so I don't again need to check it into release-1.5 and so on right? i will open another against 1.4

**Comment by devin-donnelly** [comment]
No, it won't need to be checked into subsequent release branches, because all of release-1.4 will be merged into master en masse on launch day. No need for a separate PR.

**Comment by bprashanth** [comment]
I'm going to assume there's something I'm missing and just open the 1.4 pr (merging 1.4 into HEAD will clobber 1.5 changes in HEAD right). Let me know if that's not what you meant.

**Comment by devin-donnelly** [comment]
Why are there 1.5 changes in master at all?

**Comment by bprashanth** [comment]
Because you can't check in doc changes for 1.5 in the 1.4 branch? (say I'm done with a new 1.5 feature and have already started doc int it, or im just fixing a bug for 1.4.1 but it won't be in the 1.4 release etc)

**Comment by bprashanth** [comment]
we usually check into master and cherrypick into a branch, but we can probably get away with something else if the velocity of changes is low (as im expecting the prs to be in docs repo)

**Comment by devin-donnelly** [comment]
Anything that gets pushed to HEAD is published live to the website. Nothing should go into that branch unless you want people to see it right now. Please do not publish changes for releases that do not exist to master.

**Comment by bprashanth** [comment]
Oh, so docs website is just latest version and I can't get to 1.2 docs through it? I assumed docs website was just pointing at latest branch and I could do /docs/1.2/foo and get to the 1.2 branch etc

**Comment by devin-donnelly** [comment]
No, GitHub pages limits us to publishing that which is merged into master. Anything that had to do with versioned docs in the past was generally done by creating dummy organizations and cloning the repo out to them. This was contributing to our massive SEO problems.

We've addressed this by staging via Netlify now.

**Comment by bprashanth** [comment]
Oh, hmm, thanks for the clarification. Not having versioned docs is a github pages dealbreaker but that's just my opinion. I heavily use eg: https://docs.docker.com/v1.9/engine/userguide/labels-custom-metadata/ vs https://docs.docker.com/v1.11/engine/userguide/labels-custom-metadata/ because of the rate of changes between releases, and I guess I just expected it to work

**Pull request closed without merging**
