### PR TITLE
fix the command output

### PR DESCRIPTION
**Pull request by chenhuan12**
fix the command output

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2999)

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
I do not thinks so. After my check, <nodes>, <pending>, and <none> are all possible in this case.
So I disagree with it replacing by <none>. @janetkuo

**Comment by chenopis** [comment]
Sorry, I jumped the gun on merging this, so I reverted it. Let me know what you guys want to do about this change.

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis That is blanket before changing. chenhuan12 wanted to replace it with state"none". Actually, none is one possibilty, there are other at least two states possible "nodes" and "pending", in this case.
So I am not sure if it is true to replace blanket with state "none". May it is proper or not. I just hesitate.

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif Yeah, it's probably better to just leave it blank instead putting in a value that may be incorrect in certain situations.

**Pull request merged**
