### PR TITLE
Update user-guide/quick-start.md to include Azure

### PR DESCRIPTION
**Pull request by SteveLasker**
Added Azure as a target

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2354)

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks @SteveLasker. Please sign the CLA.

**Comment by SteveLasker** [comment]
CLA signed

**Comment by chenopis** [comment]
@SteveLasker Could you add an 'and' so that it reads "for example Google Compute Engine, AWS EC2, **and** Azure ACS". Thx

**Comment by jaredbhatti** [comment]
Added the "and" in :)

**Pull request merged**
