### PR TITLE
Update pick-right-solution.md

### PR DESCRIPTION
**Pull request by nique905**
Adding new Local-machine Solution - IBM Spectrum Conductor for Containers

> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.7 Features: set Milestone to `1.7` and Base Branch to `release-1.7`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3821)

### CODE REVIEW

**Comment by chenopis** [comment]
@nique905 Thanks for adding that! When you get a chance, please sign the CLA so that I can merge this PR. Ping me if you run into any issues w/ that. Thanks!

**Comment by nique905** [comment]
@chenopis Hey, thanks for reviewing so quickly! Yeah I am having a little bit of issue with the CLA. I have sent a message through the CNCF site, just waiting on on a response. Will update you as soon as possible. Thanks!

**Comment by chenopis** [comment]
@nique905 No prob. This happens a lot. My suggestions would be: 

1. If you're an employee of a contributing organization, such as IBM, make sure you choose the [Sign up to contribute to this project as an employee](https://identity.linuxfoundation.org/node/285/employee-signup) option. Otherwise, if you choose [Sign up to contribute to this project as an individual](https://identity.linuxfoundation.org/node/285/individual-signup), make sure you click on the "get started" link in the email they send you and sign the agreement.
2. After you create a Linux Foundation account, make sure you connect your GitHub account in the "Social network logins" tab. Click on the GitHub icon in the "Add more identities" section and follow the directions to connect that account. If successful, it should look similar to this:

screen shot 2017-05-17 at 2 09 44 pm

**Comment by nique905** [comment]
@chenopis Thanks so much for this! I am going to go with the employee of an organization route. So now to get the internal approval. Just sent the request, hopefully it gets approved in the morning. Then I can get to the next steps. But thanks again for the detailed steps, really appreciate it

**Comment by nique905** [comment]
@chenopis Hi. I am now approved for my organizations group.
cncf

cncf2


But I had to change my email address to my work email for it to work. Should I now:
1. Change my primary github email address to my work email
2. Close this pull request
3. Resubmit the request so that the pull request will have my work email address that had the approved CLA.

**Comment by chenopis** [comment]
@nique905 Yes, you should change your github email to match your work email address. There is a [way](http://stackoverflow.com/questions/2919878/git-rewrite-previous-commit-usernames-and-emails) to retroactively change the email address marked in the commit and PR; however, since this change is pretty simple, I think it would be easier to just close this PR and redo it in a new one.

**Comment by nique905** [comment]
@chenopis Hey, I opted to go with the retroactive change. It seems to have worked.  Let's see if I get an all clear from the check now :)

**Comment by chenopis** [comment]
@nique905 Doesn't look like it's picking it up. Hmmm. Try doing a force push to make sure this PR picks up the change.

**Comment by nique905** [comment]
@chenopis ok I think I just fully accepted the the group membership. My bad.
Is there a way to check if the commiter email is updated, I tried `git log --pretty="%an %ae%n%cn %ce" | sort | uniq` . It works for me on other repos, I can see that my email is updated. But when I run it here, I cannot find my name, I guess because I do not have any merged content.

Sorry about all the trouble.

**Comment by nique905** [comment]
@chenopis oh nevermind it seems to work now. YAY!!!

**Comment by chenopis** [comment]
Awesome! Thanks @nique905!

**Pull request merged**
