### PR TITLE
fix a bug in the example initializerconfiguration

### PR DESCRIPTION
**Pull request by caesarxuchao**
Tested locally and it's working.

cc @droot

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4288)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@chenopis if this PR is merged, it will be reflected in the k8s.io doc at once, right?

**Comment by caesarxuchao** [comment]
sorry, i should had created the pr against the release-1.7 branch, will create another PR.

**Comment by chenopis** [comment]
@caesarxuchao Yeah, it takes a couple of minutes for the build to complete, but then it's live.

**Comment by chenopis** [comment]
@caesarxuchao Actually, no, it should be for `master` now that 1.7 is already out.

**Pull request merged**
