### PR TITLE
Update audit.md

### PR DESCRIPTION
**Pull request by islinwb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5029)

### CODE REVIEW

**Comment by cody-clark** [comment]
@steveperry-53 @chenopis Thoughts on reconciling American punctuation with international standards? (Specifically, with periods inside or outside of quotation marks)

**Comment by zacharysarah** [comment]
@cody-clark The international standard (the way you have it) is preferable.

**Comment by cody-clark** [comment]
Thanks, @zacharysarah!

**Comment by chenopis** [comment]
@zacharysarah Thank you! I hate the American standard. Never made sense to me to pull the punctuation into the quote when it's not part of the actual quote.

**Pull request merged**
