### PR TITLE
Update volumes.md

### PR DESCRIPTION
**Pull request by stewart-yu**
Fix leading spaces in commands. And fix command line format.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5026)

### CODE REVIEW

**Comment by a-mccarthy** [comment]
@stewart-yu, great improvement to the formatting on the page. I wonder if it would also look better if we got ride of the bullet points formatting altogether for these two?
@chenopis

**Comment by stewart-yu** [comment]
In fact, i'm not sure. Original web page looks not tidy.Ok, Thanks!

**Comment by chenopis** [comment]
@stewart-yu @a-mccarthy I'm changing this to use tabs instead of bullet points.

**Comment by stewart-yu** [comment]
OK.@chenopis

**Pull request merged**
