### PR TITLE
Add Tigera to community page

### PR DESCRIPTION
**Pull request by caseydavenport**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1477)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
Need you to sign the new CLA.

**Comment by caseydavenport** [comment]
@devin-donnelly It claims I already signed it.

> You are already authorized to contribute code to this project through your membership with CNCF - Tigera.

**Comment by caseydavenport** [comment]
@devin-donnelly OK - CLA has been signed.

**Comment by caseydavenport** [comment]
@devin-donnelly looks like the partners section has been removed in master.  Any clues as to where it went?

**Comment by devin-donnelly** [comment]
@caseydavenport I'm not sure how that commit got merged; I know I merged no such thing. I also don't see a PR for it. I'll try and investigate.

**Comment by caseydavenport** [comment]
@devin-donnelly thanks for the context :)

I've re-opened this here: https://github.com/kubernetes/kubernetes.github.io/pull/1581 

please take a look!

**Pull request closed without merging**
