### PR TITLE
Fix link to kubectl from docs/user-guide/kubectl/kubectl_version.md

### PR DESCRIPTION
**Pull request by pallavagarwal07**
The link to kubectl wasn't working properly on actual webpage.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1158)

### CODE REVIEW

**Comment by pallavagarwal07** [comment]
I signed it!

**Comment by devin-donnelly** [comment]
Can you rebase this, please, and I'll use the automatic staging to make sure it works before I merge it? Thanks.

**Comment by devin-donnelly** [comment]
Still needs a rebase so I can verify via staging.

**Comment by pallavagarwal07** [comment]
@devin-donnelly 
Leave this pull open for some time. I'm trying to fix a few more broken links in the docs, then I'll do the rebase.

**Comment by pallavagarwal07** [comment]
@devin-donnelly  I did a couple more changes, and rebased.

**Comment by devin-donnelly** [comment]
Thanks! Merging.

**Pull request merged**
