### PR TITLE
Small proposal in the form of a PR: Add the release stage of the feature to the feature guide.

### PR DESCRIPTION
**Pull request by Kashomon**
To make using features and the guarantees more transparent, I think it
would be nice to include the release stage of the feature. I've only
done two features in this commit to preserve clarity of the idea.

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Kinda creates an inconsistency since we didn't do this for anything else, plus use-once-and-destroy information like that makes for a poor opener. Can it be a section inline? Instead of at the top, just add #### Launch stage as a heading and put the info there, someplace towards the bottom most likely?

**Comment by Kashomon** [comment]
> Kinda creates an inconsistency since we didn't do this for anything else

My plan was to go back add add this to as many of the user-guides as I could find, but I didn't want to do that until there was consensus on the approach.

> plus use-once-and-destroy information like that makes for a poor opener. Can it be a section inline? Instead of at the top, just add #### Launch stage as a heading and put the info there, someplace towards the bottom most likely?

Sure, that's easy. However, I'm still pro-putting it at the top -- I think it's really important to frame the support of all APIs. NodeJS does this to great effect: https://nodejs.org/api/cluster.html#cluster_cluster.

**Comment by Kashomon** [comment]
Jared -- what do you think?

**Comment by Kashomon** [comment]
I'm going to abandon this for now while I work on getting the mungers working.

**Pull request closed without merging**
