### PR TITLE
Fix broken link by removing invalid characters....

### PR DESCRIPTION
**Pull request by chrismarino**
The link to this page is broken because of invalid characters introduced with PR #1549.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1605)

### CODE REVIEW

**Comment by chrismarino** [comment]
@derekmahar Can you have a look at this change.  The link is broken and this change will fix it...

**Comment by derekmahar** [comment]
@chrismarino Are you sure it's me that you want to review your change?  I don't have authority to approve changes in Kubernetes. Could you have mistaken me for someone else?

**Comment by chrismarino** [comment]
@derekmahar Whoops, sorry about that. Darm autofill.... @derekwaynecarr Can you please have a look at this change. This patch will fix the broke link.

**Comment by chrismarino** [comment]
@derekwaynecarr This is very simple fix, can you please have a look....

**Comment by chrismarino** [comment]
@thockin can you help move this along? Its a trivial fix so the page will render....

**Comment by chrismarino** [comment]
Still getting issues (#1661) posted for this broken link. This PR will fix it.  @derekwaynecarr can you please have a look cc/ @thockin

**Comment by chrismarino** [comment]
Hmm...realizing now that the build isn't completing. Not sure what to do about that?

**Pull request merged**
