### PR TITLE
PR for Kubernetes.io Dead Link Report (generated 8-22): rows 7 to 13 inclusive

### PR DESCRIPTION
**Pull request by fbsolo**
This PR fixes rows 7 to 13 inclusive in the Kubernetes.io Dead Link Report (generated 8-22) file, for bad "a href" URL locations in file

kubernetes.io/docs/api-reference/autoscaling/v1/operations.html

---

This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1202)

### CODE REVIEW

**Comment by janetkuo** [comment]
@fbsolo thanks for the fix. These docs are auto-generated, so we should fix the script instead. cc @caesarxuchao @nikhiljindal

**Comment by caesarxuchao** [comment]
The href is correct in the main repository: https://github.com/kubernetes/kubernetes/blob/master/docs/api-reference/autoscaling/v1/operations.html

I think we just need to pull those file from the main repository again.

**Comment by janetkuo** [comment]
cc @kubernetes/docs

**Comment by nikhiljindal** [comment]
I remember seeing this fixed by @devin-donnelly 
Maybe it was only fixed in release-1.4 branch?

**Comment by janetkuo** [comment]
> I remember seeing this fixed by @devin-donnelly 
Maybe it was only fixed in release-1.4 branch?

I just checked and it's fixed in release-1.4.

**Comment by devin-donnelly** [comment]
If this is fixed in 1.4, it can probably wait a week and merge in from there on launch day. If we merge it in both places we may risk a merge conflict (one of many we'll probably incur from merging release-1.4 back into Master).

**Comment by devin-donnelly** [comment]
Can you resolve the merge conflict here and sign the new (additional) CLA?

**Comment by jaredbhatti** [comment]
@fbsolo  Can you resolve the conflicts?

**Comment by fbsolo** [comment]
OK. I'll take a look in the morning . . .

**Comment by fbsolo** [comment]
Jared - I sent an email to you on Nov. 23 re: this PR.

**Comment by techtonik** [comment]
Where are those Dead Link Reports?

**Comment by jaredbhatti** [comment]
Fixed in doc generation process. Closing PR.  Thank you for your work on this!

**Pull request closed without merging**
