### PR TITLE
ZTE-SH-CN-run-application-run-stateless-application-deployment-pr-201…

### PR DESCRIPTION
**Pull request by jianglingxia**
…7-09-18

> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.8 Features: set Milestone to `1.8` and Base Branch to `release-1.8`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box (see image below) to
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5511)

### CODE REVIEW

**Comment by jianglingxia** [comment]
cc @zhangxiaoyu-zidif

**Comment by zhangxiaoyu-zidif** [comment]
ref https://github.com/kubernetes/kubernetes.github.io/pull/5466
you need move the .yaml here like @YuxiJin-tobeyjin 
please have a try. :)

**Comment by jianglingxia** [comment]
thanks ,but I checked it that all yaml  used in the page both have in the path,and I don't know why deployed failed!

**Comment by jianglingxia** [comment]
reopen #5514

**Pull request closed without merging**
