### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by caiyixiang**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2193)

### CODE REVIEW

**Comment by mikedanese** [comment]
This looks correct as is.

**Comment by devin-donnelly** [comment]
Rebasing will fix the broken Travis check.

**Comment by caiyixiang** [comment]
@mikedanese I don't quite understand why this is correct, and there are no parentheses elsewhere

**Comment by mikedanese** [comment]
@caiyixiang the parenthesis on the s means that secret can be optionally plural.

http://english.stackexchange.com/questions/93940/number-agreement-when-using-s-for-optional-plural

**Comment by caiyixiang** [comment]
@mikedanese Thanks,this is the first time I've known it and agreed it.But I'm still a little confused,there is no difference between this and other direct use of the plural,why the whole document is not consistent

**Comment by mikedanese** [comment]
Good point. LGTM.

**Pull request merged**
