### PR TITLE
grammar nits

### PR DESCRIPTION
**Pull request by chenopis**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3676)

### CODE REVIEW

**Comment by crassirostris** [comment]
Thanks!

**Comment by chenopis** [comment]
@crassirostris No problem. In the future, if you check the “Allow edits from maintainers” box when you create a pull request, I can make edits directly and save us some back and forth.

**Comment by crassirostris** [comment]
@chenopis Whoops, sorry, I though it was enabled. Will be careful next time!

**Comment by chenopis** [comment]
@crassirostris No worries. =)

**Pull request merged**
