### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by chenhuan12**
fix typo

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3402)

### CODE REVIEW

**Comment by chenopis** [comment]
@chenhuan12 What is the issue with the"-it" switch exactly?

**Comment by chenhuan12** [comment]
docker attach does not support option "-it"

**Comment by chenhuan12** [comment]
@chenopis docker attach does not support option "-it".

**Comment by brendandburns** [comment]
LGTM. thanks.

**Pull request merged**
