### PR TITLE
Update pod-with-pod-affinity.yaml

### PR DESCRIPTION
**Pull request by caarlos0**
added preferredDuringSchedulingIgnoredDuringExecution examples

should close issue https://github.com/kubernetes/kubernetes/issues/39994

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3711)

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@caarlos0 thanks for the contribution! But seems like this had been fixed in https://github.com/kubernetes/kubernetes.github.io/pull/3631. I'm going to close this PR. Feel free to reopen if I'm wrong. And welcome for new contributions!

**Comment by caarlos0** [comment]
@xiangpengzhao seems like the referenced PR replaced one example with the other, while mine is keeping both examples (preferred and required)

**Comment by xiangpengzhao** [comment]
/reopen

@caarlos0 thanks for clarification!

/assign @gyliu513

**Comment by xiangpengzhao** [comment]
@caarlos0 sorry I can't reopen the PR, you can try to reopen it :)

**Comment by BenTheElder** [comment]
hmm
/unassign

**Comment by BenTheElder** [comment]
Ah, the branch has been deleted.

**Comment by gyliu513** [comment]
@caarlos0 can you help reopen this one?

**Comment by gyliu513** [comment]
It has been fixed and merged at https://github.com/kubernetes/kubernetes.github.io/pull/3631

**Comment by xiangpengzhao** [comment]
@BenTheElder I remember there was an issue talking about cathing the branch deletion. Should we catch the event/error and comment when reopening a PR whose branch has been deleted?

**Comment by caarlos0** [comment]
Sorry I'm late, Yeah, I provably removed the fork... should I open another PR?

**Comment by gyliu513** [comment]
Thanks @caarlos0 No, it has been fixed and merged at #3631

**Comment by caarlos0** [comment]
OK, thanks all, sorry for the trouble :)

**Comment by BenTheElder** [comment]
@xiangpengzhao, yeah we probably should try and handle that somewhere. Let's create a new test-infra issue.

**Pull request closed without merging**
