### PR TITLE
Fix link to qos

### PR DESCRIPTION
**Pull request by marrrvin**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1483)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@marrrvin please sign the new linuxfoundation cla.

**Comment by marrrvin** [comment]
>please sign the new linuxfoundation cla.
Done

**Comment by marrrvin** [comment]
But I still got "1 other problem" from check (
I used the same email for signup and for author in commit.
What else can be wrong?

**Comment by chrislovecnm** [comment]
All checks have passed. You are good.

**Comment by marrrvin** [comment]
Ok.

**Pull request merged**
