### PR TITLE
azure: switch to kubernetes-anywhere

### PR DESCRIPTION
**Pull request by colemickens**
**Do Not Merge before Kube 1.4 Release**

CC: @mikedanese 

Not sure what you had in mind for this Mike, but here's something to start the discussion.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1133)

### CODE REVIEW

**Comment by jeffmendoza** [comment]
I think it would be great to have an actual guide on the website, instead of linking out to github.

**Comment by mikedanese** [comment]
This is better than what we have now. kubernetes-anywhere is the supported azure deployment for v1.4.

**Comment by colemickens** [comment]
Is there any sort of special `include` syntax? I don't know enough about what special things you can do with the GitHub Pages syntax, but it seems that there are other types of substitions done?

Another option would be to have `kubernetes.github.io` be the primary source of the "K-A Azure Getting Started Guide" and then the main K-A `README.md` could link to here. I just don't want two copies that have to manually be kept in sync.

**Comment by colemickens** [comment]
Any consensus here? (I've also updated this to target the release-1.4 branch as per the new guidelines.

**Comment by jeffmendoza** [comment]
@colemickens This is lgtm'ed so it should get merged.

> Another option would be to have kubernetes.github.io be the primary source of the "K-A Azure Getting Started Guide" and then the main K-A README.md could link to here.

I think this is the right approach for the future. It is good to have a consistent doc experience, and not have the context switch of leaving the site to go to github. K-A for Azure will seem more "official" by having the docs on the website.

**Comment by mikedanese** [comment]
@devin-donnelly can you advise Cole on how to get this into v1.4 docs and also if there is a process for sharing docs between repos?

**Pull request merged**
