### PR TITLE
Version Selector

### PR DESCRIPTION
**Pull request by zoidbergwill**
Related to https://github.com/kubernetes/kubernetes.github.io/issues/322 and https://github.com/kubernetes/kubernetes.github.io/issues/3992

Visible here: https://kubernetes-docs.zoidbergwill.com/docs/home/

To do:

- [x] Make the dropdown pretty
- [x] Fix the versioned docs URLs in the dropdown, once we know how many versions of docs back we wanna host?

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4386)

### CODE REVIEW

**Comment by ahmetb** [comment]
@zoidbergwill do you mind deleting your kubernetes docs site? These get indexed on search engines and compete with the kubernetes.io website. Your Pull Request automatically gets a Netlify site if you click "Show all checks".

**Comment by zoidbergwill** [comment]
@ahmetb In my branches I have https://github.com/zoidbergwill/kubernetes.github.io/commit/f3c8c3c8a801a9112ca38d6ddc4aea9ad8689231 and I was using them to test before I created the PR, but they're deleted now.

**Comment by ahmetb** [comment]
Ah no worries, then.

**Comment by chenopis** [comment]
@zoidbergwill Thanks for working on this! Can you do me a favor and check the "Allow edits from maintainers" (see image below) so that I can make changes? I want to switch the URL paths to the subdomains I am setting up.

allow-maintainers-to-make-edits-sidebar-checkbox

**Comment by zoidbergwill** [comment]
@chenopis Done, sorry, thought I'd done that.

**Comment by chenopis** [comment]
@zoidbergwill No worries. Thanks!

**Comment by chenopis** [comment]
@zoidbergwill It works for me, but I think there needs to be some sort of background for the dropdown so that the version numbers don't get drowned out. This is what it looks like for me:

### Top of Page
screen shot 2017-07-27 at 10 23 42 am

### Mid-page Scroll
screen shot 2017-07-27 at 10 23 56 am

**Comment by zoidbergwill** [comment]
@chenopis Tidied up the dropdown a bunch. I think it's looking much better.

I'm not an experienced front-end person, so I'm not sure if I'm doing it the best way.

**Comment by steveperry-53** [comment]
@zoidbergwill, @chenopis, I agree that we need a background for the dropdown, so it doesn't get mixed up with the page text.

**Comment by steveperry-53** [comment]
@zoidbergwill, @chenopis, Do we need to display the patch numbers in the dropdown? Or in the interest of simplicity, could we just show major.minor? 1.7, 1.6, 1.5.

**Comment by zoidbergwill** [comment]
@steveperry-53 If you check out the site now, it should have a background on the dropdown now: https://deploy-preview-4386--kubernetes-io-master-staging.netlify.com

`major.minor` sounds good to me, since I don't think we plan on hosting multiple bugfix versions anytime soon.

**Comment by zoidbergwill** [comment]
Will change it to just `major.minor` in the morning.

What do you folk think of adding border-radius to the dropdown?

image

**Comment by chenopis** [comment]
@zoidbergwill I made the `major.minor` change. The border-radius is a nice touch.

**Comment by chenopis** [comment]
@zoidbergwill Yeah, I think we're pretty close. Just add the border-radius and I think we're good to go. I will then try to add this to the `release-1.6`, `release-1.5`, and `release-1.4` branches. Thanks!

**Comment by chenopis** [comment]
@zoidbergwill I'm going to implement this in the other release branches before I release this on `master`.

**Comment by steveperry-53** [comment]
@zoidbergwill, @chenopis, When you scroll down on a page, the background color of the dropdown changes from black to white. Is that the intention? The white background doesn't do a very good job of separating the dropdown from the page content. Seems like keeping the black background would be better.

**Comment by zoidbergwill** [comment]
@chenopis Awesome, I was thinking about doing some active/hover stuff, but it's difficult with how the padding and positioning currently works.

**Comment by zoidbergwill** [comment]
@steveperry-53 It's what the navbar does and is just matching that. Because of how the positioning and padding stuff is currently happening, it's hard to add a box-shadow that would look good.

I've played with it a bit here, but I think it'd be difficult to get it to match the navbar properly: 
image

I could maybe move it up a bit though and make it look like border/shadow just around the dropdown.

I also tried to do hover colour changing over the links in the dropdown but they look a bit gross because of the same padding stuff.

**Comment by steveperry-53** [comment]
@zoidbergwill, A border would be nice to have, but I'd say the dropdown is also OK as is. Thanks for your work on this.
/lgtm

**Comment by chenopis** [comment]
I'm deploying this now.

**Comment by chenopis** [comment]
closes #4386

**Comment by chenopis** [comment]
closes #3992

**Comment by chenopis** [comment]
closes #322

**Pull request merged**
