### PR TITLE
Update Heapster K8s doc

### PR DESCRIPTION
**Pull request by mwielgus**
cc: @piosz

### CODE REVIEW

**Comment by piosz** [comment]
@davidopp could you please take a look from native speaker perspective?

cc @fgrzadkowski

**Comment by piosz** [comment]
LGTM for the content.

**Comment by mwielgus** [comment]
Ping

**Comment by piosz** [comment]
@johndmulhausen I made tech review and added LGTM for it thought I'm not able to apply the label.
Maybe @fgrzadkowski has appropriate permissions.

**Comment by johndmulhausen** [comment]
Thanks guys :)

**Pull request merged**
