### PR TITLE
Add audit doc

### PR DESCRIPTION
**Pull request by soltysh**
This is copy of #1168 which already have tech approval (so I'm applying the label based on that) , I'm recreating it so it's part of 1.4.

@devin-donnelly ptal

@janetkuo @sttts fyi

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1193)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/admin/audit.md, line 12 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1193#-KRFPBkwk0YYpAz_JHhV:-KRFPBkwk0YYpAz_JHhW:bjt3hwd) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/8ff250ec8439a95ad1ef77e5e6b033c299a72544/docs/admin/audit.md#L12)):*
> ```Markdown
> 
> ## Audit in Kubernetes
> ```

If this is where we're introducing the context of Audit in Kubernetes, it would be a good place to give a one- or two-sentence description of what Audit does and why it exists.

Something like "Kubernetes Auditing makes sure that..." or "Kubernetes Audit provides..."

---

*[docs/admin/audit.md, line 50 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1193#-KRFPZ1q3nf46EZl2Alw:-KRFPXG0d_jqk6M58-Dy:b-v6n0c1) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/8ff250ec8439a95ad1ef77e5e6b033c299a72544/docs/admin/audit.md#L50)):*
> ```Markdown
> - `audit-log-maxsize` - specifies maximum size in megabytes of the audit log file before it gets rotated. Defaults to 100MB
> 
> Audit logs are being appended if the file already existed or a new one will be
> ```

"If an audit log file already exists, Kubernetes appends new audit logs to that file. Otherwise, Kubernetes creates an audit log file at the location you specified in `audit-log-path`. If the audit log file exceeds the size you specify in `audit-log-maxsize`, Kubernetes will rename the current log file by appending the current timestamp on the file name (before the file extension) and create a new audit log file.

---

*[docs/admin/audit.md, line 54 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1193#-KRFQ-izUtdHXZG679ut:-KRFQ-j-e4RrLGD1uImz:b-3w1zkr) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/8ff250ec8439a95ad1ef77e5e6b033c299a72544/docs/admin/audit.md#L54)):*
> ```Markdown
> renamed by putting the current timestamp at the end name of the file name (before
> the file's extension)
> Whenever a new logfile get created, old log files may be deleted. This policy is
> ```

Kubernetes may delete old log files when creating a new log file; you can configure how many files are retained and how old they can be by specifying the `audit-log-maxbackup` and `audit-log-maxage` options.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1193)*

**Comment by soltysh** [comment]
Comments addressed, ptal.

**Comment by devin-donnelly** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1193#-:-KR_iCzKKOn_y2Fe9Bym:bnfp4nl)*

**Comment by devin-donnelly** [comment]
Looks good, but there are some merge conflicts. I can't merge until they're resolved. @soltysh , would you mind taking a look?

**Comment by soltysh** [comment]
@devin-donnelly rebased

**Comment by soltysh** [comment]
Merging based on previous approval.

**Comment by devin-donnelly** [comment]
Thanks. Merging.

**Pull request merged**
