### PR TITLE
update links for safely-drain-node.md

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
update links for afely-drain-node.md

> NOTE: Please check the “Allow edits from maintainers” box (see image below) to  
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4373)

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@ahmetb OK， done.=)

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis 
PTAL

**Comment by ahmetb** [comment]
Looks fine, I can just merge this.

**Pull request merged**
