### PR TITLE
authentication/#creating-certificates document inconsistent in naming for the server certificate.

### PR DESCRIPTION
**Pull request by alejandroEsc**
fixed server.cert text to server.crt which is consistent with the res…t of the document.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2032)

### CODE REVIEW

**Comment by ericchiang** [comment]
lgtm

**Comment by alejandroEsc** [comment]
thanks @ericchiang do you have merge rights?

**Comment by ericchiang** [comment]
Nope. I'm sure someone with write access will come merge it though.

**Comment by alejandroEsc** [comment]
@ericchiang interesting. what is the appropriate way to get their attention?

**Comment by ericchiang** [comment]
devin-donnelly usually merges small PRs like this.

**Pull request merged**
