### PR TITLE
Making sure users get the latest version of Docker

### PR DESCRIPTION
**Pull request by johndmulhausen**
The default OS packages are probably not what users actually want to use.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1326)

### CODE REVIEW

**Comment by johndmulhausen** [comment]
I signed it!

**Comment by errordeveloper** [comment]
@johndmulhausen we have a long discussion on this, and the conclusion was that it's easier to use those packages, yet `docker-engine` is usage also. @lukemarsden @mikedanese where is the doc capturing this discussion?

**Comment by errordeveloper** [comment]
@johndmulhausen thanks for the PR, let's come up with the best solution to this. One requirement is that we have to pin to Docker release 1.11.2, as that's what Kubernetes 1.4 had been validated agains.

**Comment by mikedanese** [comment]
Hey John, nice to see you again!

I think this PR does the opposite of what we want right now.  Users are free to use other versions of Docker, if they so desire (perhaps we should make THAT clearer) but these instructions give them the most recent known-to-work-with-kubernetes Docker version.  Unfortunately, it seems that `apt-get` is incapable doing the right thing wrt exact-version dependencies, so we're sort of stuck.

As far as making it clearer how to pick the alternative docker versions, I'd prefer having a standalone doc for that. This should be possible and easy to do since none of our OS packages depend on a specific docker package. We should also publish the known good k8s <-> docker version pairs in this doc.

I'm all for enabling power users but this doc is specifically aimed at users who want to get started with Kubernetes quickly and probably don't care which docker version they get as long as they have a good/not buggy first experience. For this case the redirect offpage seems unnecessary and counter productive to the user journey if we can deliver a reasonable default package that does just this.

**Pull request closed without merging**
