### PR TITLE
Add missing information and new link on Kompose

### PR DESCRIPTION
**Pull request by cdrage**
Adds a new to Kompose on the Kubernetes Incubator

More information on Kompose / better formatting to reflect other tools
on the page

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1501)

### CODE REVIEW

**Comment by cdrage** [comment]
ping @janetkuo

**Comment by janetkuo** [comment]
Looks good. Thanks!

**Comment by janetkuo** [comment]
Would you sign the CLA?

**Comment by cdrage** [comment]
@janetkuo Done!

**Comment by cdrage** [comment]
(and rebased)

**Comment by janetkuo** [comment]
cc @kubernetes/docs

**Pull request merged**
