### PR TITLE
Update ResourceQuota documentation for 1.2

### PR DESCRIPTION
**Pull request by derekwaynecarr**
This updates the quota documentation to align with current code state from 1.2.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@pmorie @ncdc - can either of you provide the tech LGTM tag here?  This represents what we have already documented in OpenShift that needed to go upstream.

**Comment by pmorie** [comment]
@derekwaynecarr rebase needed

**Comment by derekwaynecarr** [comment]
@ncdc -- this is the same content from https://github.com/kubernetes/kubernetes.github.io/pull/641 excluding the new features in 1.3 for `services.loadbalancers` and `services.nodeports`.  PTAL so we can push this out.

**Comment by derekwaynecarr** [comment]
After seeing how rebasing got difficult across branches, I am closing this in favor of https://github.com/kubernetes/kubernetes.github.io/pull/622 which combines the example change with the doc change.

**Pull request closed without merging**
