### PR TITLE
Updated user guide for `kubectl taint` by adding `NoExecute`.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed part of #2737

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2744)

### CODE REVIEW

**Comment by aveshagarwal** [comment]
LGTM.

FYI: @mburke5678

**Comment by kevin-wangzefeng** [comment]
LGTM.

You may rebase to the latest master since it's prompting "This branch is out-of-date with the base branch".

**Comment by gyliu513** [comment]
This is target for 1.6, can we have this merged soon? @aveshagarwal @kevin-wangzefeng @cmluciano

**Comment by gyliu513** [comment]
This is target for 1.6, can we have this merged soon? @aveshagarwal @kevin-wangzefeng @cmluciano

**Comment by davidopp** [comment]
LGTM

**Comment by mburke5678** [comment]
LGTM

**Comment by ymqytw** [comment]
@gyliu513 @chenopis There is no need to manually update the doc here. These files are all generated (see the bottom of this file)
We will run scripts to update the imported doc, like kubectl help message.
```
https://github.com/kubernetes/kubernetes.github.io/blob/master/update-imported-docs.sh
```
For new reference docs, @pwittrock has script in `https://github.com/kubernetes-incubator/reference-docs` to update the new style doc.

FYI, we are not maintaining the old docs.

cc: @devin-donnelly

**Comment by gyliu513** [comment]
Good to know, thanks @ymqytw

**Pull request merged**
