### PR TITLE
Pin flannel yaml to specific version

### PR DESCRIPTION
**Pull request by robszumski**
This file has been updated in master from what is supported in this Kubernetes version

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5588)

### CODE REVIEW

**Comment by chenopis** [comment]
@robszumski Could this possibly change in the future?

**Comment by robszumski** [comment]
@robszumski The version of flannel itself installed by Kubernetes may change (and this link updated), but I would not expect the file contents of that link as written to change over time, as it's a tagged release. It is not common or expected for that tag to ever change.

**Comment by chenopis** [comment]
@robszumski Ok, cool. We just need a tech sign-off on this. Then I can merge it.

**Comment by luxas** [comment]
This now needs a rebase...
cc @aaronlevy @tomdee PTAL
I guess this looks good to me as well -- is v0.8.0 the supported version for v1.8?

**Pull request merged**
