### PR TITLE
Create Installing kubeadm topic.

### PR DESCRIPTION
**Pull request by steveperry-53**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3709)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@bgrant0607, Can you comment on whether you think this PR is heading in the right direction? The last time you and I met, we discussed the idea of having a set of Tasks for installing tools like kubectl, minikube, kubeadm, helm, etc. I like the idea putting tool installation in its own section. But on the other hand, I'm concerned about factoring tool installation out of Setup topics like [Installing Kubernetes on Linux with kubeadm](https://kubernetes.io/docs/getting-started-guides/kubeadm/). I really don't want to duplicate the installation instructions for a given tool, so I think we should choose one approach or the other.

cc @mikedanese, @luxas, @errordeveloper, @jbeda

**Comment by bgrant0607** [comment]
@steveperry-53 Creating a kubeadm installation task makes sense to me. I could imagine someone wanting to know just that. Is the concern that it would only be referenced by the guide that explains how to use kubeadm to create a cluster? I expect to have multiple kubeadm-related guides, for creating different types of clusters, updating clusters, etc.

**Comment by steveperry-53** [comment]
@bgrant0607 My concern is about where to put the How to Install kubeadm topic. In the top nav, we have a Setup, Concepts, Tasks, ... I'm thinking that How to Install kubeadm should not be under Tasks. Instead it should be under Setup, along with the other topics that talk about how to use kubeadm to create/update clusters.

**Comment by bgrant0607** [comment]
@steveperry-53 

Installing anything (kubeadm, kubectl, etc.) is probably "Setup".

However, we want to make docs easy to find.

Is it not possible to list the topic under multiple categories?

**Comment by steveperry-53** [comment]
@bgrant0607 OK, we'll put the Installing topics under Setup. I'll look into listing topics in multiple places. I think we can do that.

**Pull request merged**
