### PR TITLE
Update the template to version 1.2.2

### PR DESCRIPTION
**Pull request by aabed**

### CODE REVIEW

**Comment by rata** [comment]
Now 1.2.3 is out there :)

**Comment by pwittrock** [comment]
and 1.3.0  ...

**Comment by aabed** [comment]
@pwittrock this is nornal when you merge after 3 months :'D 
I will submit another request with 1.3

**Comment by pwittrock** [comment]
@aabed Apologies for the long delay.  I wouldn't say it is normal and definitely not what we want.  The process who reviews these PRs and how they are assigned has changed, and it is clearly insufficient.  We aware of the issue, and we are working on automation to address this.

RE: The 1.3 PR.  Please @ mention me so it goes to the top of my list.  If I am unresponsive feel free to @ mention me in the sig-docs slack channel.

**Comment by aabed** [comment]
Wow, I was just kidding, but thank you very much I really appreciate your
effort
Will let you know once I am done with the change

**Comment by pwittrock** [comment]
@aabed I could tell that you were kidding, but it is actually something we have been talking about quite a bit :)

**Pull request merged**
