### PR TITLE
Add Windows version details

### PR DESCRIPTION
**Pull request by sandeepveldi**
Adding windows version related download path.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2009)

### CODE REVIEW

**Comment by sandeepveldi** [comment]
I signed it!

**Comment by sandeepveldi** [comment]
I signed it!

Thanks & Regards,
Sandeep Veldi

**Comment by sandeepveldi** [comment]
If any of have access to the build logs, please check and let me know why the deployment is failing.

**Comment by devin-donnelly** [comment]
@sandeepveldi It's fine now, but this needs a tech review before I can merge.

**Comment by sandeepveldi** [comment]
@devin-donnelly Thanks!

**Comment by bgrant0607** [comment]
@sandeepveldi Please rebase.

@david-mcmahon Is this the correct path?

**Pull request merged**
