### PR TITLE
Apply templates, some edits for style guide conformance

### PR DESCRIPTION
**Pull request by Bradamant3**
This is possibly an interim PR to make sure I've got the templates right and am prioritizing work appropriately. Complete style guide conformance is not done -- latinisms removed, some small text tightening and clarification only. Minimal work on ReplicationController because Deployment/ReplicaSet seem to be The Future.

Addresses one item plus related files in issue #4507

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4537)

### CODE REVIEW

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 8c78c82fd5dc0b56a4ac14ce2904bef974aa28db

https://deploy-preview-4537--kubernetes-io-master-staging.netlify.com

**Comment by Bradamant3** [comment]
Template mess, please do not review yet!

**Comment by Bradamant3** [comment]
Template errors fixed, ok to review.

**Comment by chenopis** [comment]
@Bradamant3 /lgtm

**Pull request merged**
