### PR TITLE
Fix broken link to example in access-cluster.md

### PR DESCRIPTION
**Pull request by jlewi**
I also updated the snippet to match the code in the example. It looks like the snippet was still using the 1.4 client which I think is outdated.

> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.7 Features: set Milestone to `1.7` and Base Branch to `release-1.7`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4139)

### CODE REVIEW

**Comment by janetkuo** [comment]
@jlewi thanks, this lgtm. Would you sign the CLA?

The link was broken by https://github.com/kubernetes/client-go/commit/6df6f2148a8d325ba34ed91c801d1c8409598f2a cc @ahmetb

**Comment by vishh** [comment]
@thelinuxfoundation update CLA

**Comment by ahmetb** [comment]
FWIW having "Programmatic access to cluster" documented in k8s.io is not very ideal. We already have the same code snippets (more complete/up-to-date) at client-go and client-python repositories. Having it in multiple places probably increases the chances of having out-of-date information further.

**Comment by janetkuo** [comment]
Agree with @ahmetb. @jlewi would you remove the code snippets too?

**Comment by jlewi** [comment]
@ahmetb @janetkuo  Did you want me to delete the entire section "Programmatic access to cluster"? I just deleted the Go code snippet to avoid duplicating code in the sample.

It seems useful to me to have a section Programmatic Access with links to the relevant code samples.

**Comment by ahmetb** [comment]
We have those snippet samples maintained at client-go/client-python repository. You can link out to those places and still keep the sections here.

**Comment by janetkuo** [comment]
@jlewi thanks! This change lgtm. Please squash commits into one and sign the CLA

**Comment by janetkuo** [comment]
To squash commits:
```
git rebase -i upstream/master 
```

You'll see several commits prefixed with `pick `.

Pick your fist commit using `pick`, squash your subsequent commits with `fixup`, and remove other commits with `drop`

**Comment by jlewi** [comment]
Thanks @janetkuo . I'm still working on the CLA. I think the issue is the commit email is different from the email associated with my github account. I'll try to figure that out.

**Comment by ahmetb** [comment]
Looks good now, thanks.

**Comment by chenopis** [comment]
@jlewi This might help: https://stackoverflow.com/questions/2919878/git-rewrite-previous-commit-usernames-and-emails

**Comment by ahmetb** [comment]
in your case `git commit --amend --no-edit --author ="Your Name <your@email.com>"` should work just fine as you only have 1 commit, then you would `git push -f` to your branch.

**Comment by jlewi** [comment]
Thanks @ahmetb I followed the FAQ (https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ) and created a hellosign.com account and was able to find and sign the agreement.

**Pull request merged**
