### PR TITLE
Issue #69: Updated version of k8s from 1.1.4 to 1.1.8

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
Resolves issue: #69

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Looks good from a docs perspective!

**Comment by MikeSpreitzer** [comment]
It should be very easy to get a tech confirmation of this, just have someone look at https://github.com/kubernetes/kubernetes/blob/master/cluster/ubuntu/download-release.sh#L56

**Comment by MikeSpreitzer** [comment]
@johndmulhausen: what is needed to move this forward?

**Comment by erictune** [comment]
LGTM.

**Comment by MikeSpreitzer** [comment]
@johndmulhausen: is there a documented process here?  What does this PR lack?

**Comment by johndmulhausen** [comment]
Thank you @MikeSpreitzer for the PR and thank you @erictune for the review!

**Pull request merged**
