### PR TITLE
Updated hpa config file to the latest API version.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Updated hpa config file to the latest API version.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1356)

### CODE REVIEW

**Comment by jszczepkowski** [comment]
Fixes #33776.

**Comment by jszczepkowski** [comment]
CC @pwittrock

**Comment by davidopp** [comment]
LGTM

**Comment by jszczepkowski** [comment]
Fixes https://github.com/kubernetes/kubernetes/issues/33776.

**Comment by jszczepkowski** [comment]
@steveperry-53 
This PR has both LGTMs. Can you merge it please?

**Comment by jszczepkowski** [comment]
@devin-donnelly 

Please, can you merge this PR?

**Comment by devin-donnelly** [comment]
I need you to sign the new Linux Foundation CLA before I can merge.

**Comment by jszczepkowski** [comment]
@devin-donnelly 

> I need you to sign the new Linux Foundation CLA before I can merge.

Done

**Comment by jszczepkowski** [comment]
@devin-donnelly 
Something with verification of CLA for linux foundation is broken. Please check validity of my CLA here:
https://github.com/kubernetes/kubernetes/pull/34536

**Pull request merged**
