### PR TITLE
Adding redirects for kubectl commands

### PR DESCRIPTION
**Pull request by foxish**
Fixes https://github.com/kubernetes/kubernetes.github.io/issues/3124, https://github.com/kubernetes/kubernetes.github.io/issues/3116, https://github.com/kubernetes/kubernetes.github.io/issues/3077

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3125)

### CODE REVIEW

**Comment by foxish** [comment]
PTAL @chenopis @pwittrock

**Comment by foxish** [comment]
cc @kubernetes/sig-docs-maintainers

**Comment by pwittrock** [comment]
LGTM

**Comment by pwittrock** [comment]
Instead of putting these place holders in, there is a way to automatically redirect to the new page.

Also I think the links are wrong, and they should be pointing to ref docs.

**Comment by pwittrock** [comment]
@chenopis @steveperry-53 Would you take a look at this and comment on the best way to do redirectss?

**Comment by foxish** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes.github.io/pull/3160

**Comment by chenopis** [comment]
Sorry, I should have responded to this yesterday, but I was working on #3160. Please let me know if any other links need to be fixed by way of redirects.

**Pull request closed without merging**
