### PR TITLE
Updates to partner page design to add KCSPs

### PR DESCRIPTION
**Pull request by kbarnard10**
**Do not merge until 9/11 at 9am PT**

Final KCSPs still need to be confirmed (logos are currently placeholders), but page layout is finalized and ready to test otherwise.

@bobsky @zacharysarah

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5336)

### CODE REVIEW

**Comment by dankohn** [comment]
Could we please switch to the Bitnami and Heptio logos we use on https://www.cncf.io/about/members/ ? I think including the company name in the logo makes it much more visually clear who we're talking about, even if you lose a bit of the design aesthetic.

Also, Skippbox needs to be removed from the Service Providers section (they were acquired by Bitnami) and StackPointCloud needs to be removed (since they're in the KCSP section).

Thanks.

**Comment by dankohn** [comment]
Also, please remove Deis for Service Providers, as they were acquired by Microsoft.

**Comment by kbarnard10** [comment]
@dankohn I made your requested updates. Also added Booz Allen Hamilton.

**Comment by dankohn** [comment]
Could you please remove Deis from this version or in a new PR?

**Comment by kbarnard10** [comment]
@dankohn Yup! Done - I had missed their second listing.

**Comment by kbarnard10** [comment]
@zacharysarah Can you merge this now?

**Pull request merged**
