### PR TITLE
Fix doc issues 617, 616, and 614

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
For 617: changed the master setup instructions to install the kubelet
after Calico.  Also noted the additional file, to fix 616 and replaced
`rkt` with `cni` to fix 614.

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@johndmulhausen @caseydavenport what are we waiting for here?

**Comment by caseydavenport** [comment]
@johndmulhausen - as a Calico dev, am I capable of providing the necessary tech review?

**Comment by caseydavenport** [comment]
This looks fine to me and I would be happy with this solution, but I wonder if it might be simpler for #617 to just remove the dependency on `calico-node.service` from kubelet, since kubelet doesn't actually rely on `calico/node`.

**Comment by MikeSpreitzer** [comment]
I will be happy to test that, next time I build a cluster.

**Comment by MikeSpreitzer** [comment]
On second thought, I am surprised at the claim that kubelet doesn't actually rely on `calico/node`.  How functional is the kubelet without `calico/node`?

**Comment by caseydavenport** [comment]
`calico/node` will be necessary for any containers that are started to actually get network connectivity.  However, `calico/node` itself shouldn't be necessary for the kubelet to start.  I believe it should even be possible to have `calico/node` managed by the kubelet itself (e.g as a static pod rather than via systemd) - it's something I plan on investigating in the near future.

**Comment by pwittrock** [comment]
@caseydavenport Yes, you can provide the Tech Review LGTM

**Comment by pwittrock** [comment]
@caseydavenport Or if you just comment LGTM I will add the label

**Comment by caseydavenport** [comment]
Yep, this LGTM.

**Comment by MikeSpreitzer** [comment]
Hey wait, this is partly redundant with #855 (which is already merged).  I wanted to break this into two pieces, since Casey suggested an alternate fix for #617.

**Comment by caseydavenport** [comment]
Right.. my head must be somewhere else (though surprised this isn't conflicting with the now-merged #855?)

@MikeSpreitzer I think I'm happy with this either way (with slight preference to removing the dependency) as I see them both as medium term fixes.  Eventually I think what we'll want to do is have `calico/node` running as pod in a DaemonSet (or as a static pod), but I don't think we're quite there yet in being able to support that.

**Comment by MikeSpreitzer** [comment]
Wait, what?  I already did another PR to fix #614 and #616, and was planning on working on an alternative to fix #617 like Casey suggested.  Sorry I did not close this, I have been busy on other items.

**Pull request merged**
