### PR TITLE
update resources name

### PR DESCRIPTION
**Pull request by shiywang**
follow https://github.com/kubernetes/kubernetes/pull/43303

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2902)

### CODE REVIEW

**Comment by ymqytw** [comment]
LGTM

**Comment by ahmetb** [comment]
Should this be targeting the 1.6 as the base branch instead? It doesn't appear in `kubectl get` output for 1.5.x.

**Comment by ymqytw** [comment]
> Should this be targeting the 1.6 as the base branch instead?

Yes. The release 1.6 is not out yet

**Comment by devin-donnelly** [comment]
@ymqytw , You can change the base branch to `release-1.6`. If you do that, I can merge this right away.

**Comment by ymqytw** [comment]
@devin-donnelly Unfortunately, I can't change the base branch. I'm not the owner of this PR and I don't have permission to change that.

**Comment by chenopis** [comment]
I was able to change the base to `release-1.6`.

**Comment by ymqytw** [comment]
@chenopis Great! Thanks.

**Pull request merged**
