### PR TITLE
Add Quobyte volumes in docs

### PR DESCRIPTION
**Pull request by johscheuer**
Now to the right branch https://github.com/kubernetes/kubernetes.github.io/pull/1061 

Thanks @pwittrock  :)

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1067)

### CODE REVIEW

**Comment by johscheuer** [comment]
Ping @thockin

**Comment by johscheuer** [comment]
The failed check seems unrelated to the PR:

````
The command "git config --global user.email ${GIT_EMAIL}" exited with 1.
$ git config --global user.name "${GIT_NAME}"
...
$ git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:
  git config --global push.default matching
To squelch this message and adopt the new behavior now, use:
  git config --global push.default simple
See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)
remote: Anonymous access to kubernetes-v1-4/kubernetes-v1-4.github.io.git denied.
fatal: Authentication failed for 'https://:@github.com/kubernetes-v1-4/kubernetes-v1-4.github.io.git/'
The command "git push" exited with 128.
```

**Comment by devin-donnelly** [comment]
This looks fine; I'm not sure why that Travis check failed. @jeffmendoza , any insight?

Otherwise I can just merge this.

**Comment by jeffmendoza** [comment]
@jaredbhatti The release-1.4 branch needs it credentials updated as well.

**Comment by janetkuo** [comment]
I hit this also and filed issue #1124

**Comment by janetkuo** [comment]
The travis scripts is updated. The build should succeed after rebasing.

**Comment by janetkuo** [comment]
I merged #1159 so after another rebase the travis should pass

**Comment by janetkuo** [comment]
Oh wait, I re-run the build and it passed. No need to rebase.

**Comment by saad-ali** [comment]
LGTM @kubernetes/docs for final sign-off.

**Comment by thockin** [comment]
@devin-donnelly @jaredbhatti for 1.4

**Comment by devin-donnelly** [comment]
Docs LGTM. Merging to release-1.4. Thanks, everybody.

**Pull request merged**
