### PR TITLE
allow copy&paste of sample code

### PR DESCRIPTION
**Pull request by Hades32**
multi-line code samples should not be prefixed with stuff that makes copy&paste hard!

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1835)

### CODE REVIEW

**Comment by Hades32** [comment]
signed CLA

**Comment by jbeda** [comment]
Looks good to me but the `#` indicated that it should be run as root.  We should communicate that somehow if you remove it from the CLI samples.

**Comment by Hades32** [comment]
Ah, I didn't realize that. I found that to be obvious :)
But I guess a red "run as root' at the beginning of the tutorial should be enough....

**Comment by Hades32** [comment]
Actually there is already this sentence in there:

> * SSH into the machine and become `root` if you are not already (for example, run `sudo su -`).

Do we need more?

**Comment by jbeda** [comment]
Meh -- good enough.  :)

/lgtm

**Comment by jbeda** [comment]
@devin-donnelly -- what do I need to do to get this merged?  The process here isn't clear.

**Pull request merged**
