### PR TITLE
fix the command output

### PR DESCRIPTION
**Pull request by chenhuan12**
fix the command output

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5516)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@chenhuan12 Please rebase your branch so that it picks up 99fbc2b. That will fix the deploy/netlify failure. Thanks.

**Comment by chenhuan12** [comment]
cc @zhangxiaoyu-zidif

**Comment by zhangxiaoyu-zidif** [comment]
which version do you test it? @chenhuan12 
Because you want this PR to merge into master branch, I recommand you to use recent verion. Thanks.

**Comment by steveperry-53** [comment]
Closing based on recommendation from @zhangxiaoyu-zidif .

See also #5518.

**Pull request closed without merging**
