### PR TITLE
Update Nebulaworks logo on partner page

### PR DESCRIPTION
**Pull request by chrisciborowski**
Update Nebulaworks logo on Kubernetes.io partner page (https://kubernetes.io/partners/)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4104)

### CODE REVIEW

**Comment by chrisciborowski** [comment]
Looks like the CCNF CLA (corp) hasn't been registered yet.

**Comment by chrisciborowski** [comment]
Hi @jaredbhatti - correct CCNF CLA e-signed and associated.

**Comment by chenopis** [comment]
@chrisciborowski You might need to rewrite the commit to make sure the email address matches up w/ the one you used for the CLA. See: http://stackoverflow.com/questions/2919878/git-rewrite-previous-commit-usernames-and-emails

**Comment by chrisciborowski** [comment]
@chenopis tried to get this squared away, and It seems like it is moving backwards not forwards. The committer email is correct, and I went back and rewrote using the alias the committer and author emails for my previous commits. Maybe better to just close the PR and I can resubmit, rather than try and unwind this plus the branch mis-match?

**Comment by chenopis** [comment]
@chrisciborowski Ok, that's fine. Just ping me w/ the new PR.

**Pull request closed without merging**
