### PR TITLE
Update static-pods.md

### PR DESCRIPTION
**Pull request by scjane**
Some of the serial numbers of the ordered list in the "Static pod creation" section are incorrect because items in the list are segmented by code blocks. I think this can be solved in at least the following ways:
1.Remove the ordered list style and just use plain text each beginning with "1", "2"，...,or  "step 1", "step 2"，... (My modification adopts this one)
2.Replace the ordered list with an unordered list in which each item beginning with "step 1", "step 2"，...
3.Use HTML tags, such as <ol>,<li> to give the lists involved
Are there any other better ways for this problem? I would be appreciated to know.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2518)

### CODE REVIEW

**Comment by chenopis** [comment]
@scjane You want to try it the way @jsafrane suggested?

**Comment by scjane** [comment]
@jsafrane Thanks for your reply. But I still have a problem, if an item in an ordered list has both code and plain texts (and perhaps the text has several paragraphs) like the following, how can I edit the list to ensure proper style (avoid displaying the text as code ) as well as correct serial number (avoid displaying other serial numbers except "1" as "1"):

1. First item
  
    code 1
   
    text 1

2.Second item

    code 2
   
    text 2-1
    
    text 2-2

3.Third item
   ...
("text 2-1" and "text 2-2“,... indicate that the text can have several paragraphs. )

In fact, I've encountered this problem now and then. Looking forward to your advice :)

**Comment by scjane** [comment]
@chenopis Yes, I have copied the source doc and edited it in MarkDownPad on my computer, but it seems that I missed something to make a satisfying modification. So, a further discussion is ongoing.

**Comment by jsafrane** [comment]
Indentation is the key. All lines "inside" an ordered list must have the same numbers of spaces at the beginning, even empty lines. See https://gist.github.com/jsafrane/cd4d38d2b531d7db2e1108be3c023dc2

**Comment by chenopis** [comment]
@scjane It's also possible that MarkDownPad parses the MD a little differently than our site. You can try pushing the change to this branch then viewing it in the Netlify preview that is part of the checks.

**Comment by chenopis** [comment]
@scjane Ping. Just wanted to check in to see what the state of this PR is.

**Comment by scjane** [comment]
@jsafrane @chenopis Sorry for updating this PR late. I'm not good at adjusting indent. But indent really works. Now I Get it! Thank you.

**Comment by chenopis** [comment]
@scjane No problem. Thanks for all of your contributions. BTW, I'm seeing a conflict so I can't merge this PR yet. Can you rebase or merge `master` into this branch and resolve the conflict? Thx

**Pull request merged**
