### PR TITLE
The key-value "optional:true"  doesn't work

### PR DESCRIPTION
**Pull request by sallydeng**
The key-value "optional:true"  doesn't work in 1.5.2 yet. 
So should we add a note here? "The key-value "optional:true" will be work after kubernetes 1.5.2."

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2522)

### CODE REVIEW

**Comment by chenopis** [comment]
@sallydeng I would phrase it something like "The key-value `optional:true` is supported for kubernetes 1.5.3 and above."

**Comment by sallydeng** [comment]
OK. I change the sentence base on your comment. @chenopis 
But what happened here?
"continuous-integration/travis-ci/pr — The Travis CI build could not complete due to an error"
https://travis-ci.org/kubernetes/kubernetes.github.io/builds/201755620

**Comment by chenopis** [comment]
@sallydeng I don't think this is an issue w/ your change. I'll look into why the Travis CI check failed, but my guess is that it's something else when you merged in the master branch. Try doing a rebase (or update the branch).

**Comment by sallydeng** [comment]
@chenopis , 
The button "Update branch" has been disabled.
I tried rebase in git, but it just show the last commit of sallydeng:patch-4, so I can't merger all three changes.

**Comment by chenopis** [comment]
@sallydeng The Travis CI issue seems to be ongoing, so I'm working on getting that fixed. This PR looks fine, so I will merge it as soon as I can and also do a rebase as part of the merge.

**Comment by Bregor** [comment]
`optional:true` doesn't work with 1.5.3:

    $ kubectl apply -f redis.yaml
    error: error validating "redis.yaml": error validating data: found invalid field optional for v1.ConfigMapVolumeSource; if you choose to ignore these errors, turn validation off with --validate=false

`invalid field optional for v1.ConfigMapVolumeSource`

    $ kubectl version --short
    Client Version: v1.5.3
    Server Version: v1.5.3

**Comment by chenopis** [comment]
Thanks @Bregor . I'm going to rollback this PR for now. @sallydeng can you verify which release this will be available for? I know they had to take some things out at the last minute for 1.5.3.

**Comment by sallydeng** [comment]
@chenopis "I know they had to take some things out at the last minute for 1.5.3."
Base on this pr
https://github.com/kubernetes/kubernetes/pull/39981/files ，"optional :true" hasn't been added to K8S1.5.2 。
Checked source code of 1.5, it doesn't contain "optional:true":
https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/api/types.go。
Since @Bregor said it doesn't work in 1.5.3 yet.
I tested it in K8Sv1.6.0-alpha.1, it can work.
So should we add a note like this? "NOTE: The key-value optional:true is supported for kubernetes 1.6 and above."

**Comment by chenopis** [comment]
@sallydeng Ok, yes, if it's for 1.6, then open a new pull request for the branch `kubernetes:release-1.6` and make the text "**NOTE:** The key-value `optional:true` is supported for Kubernetes 1.6 and above." It will go out with the rest of the 1.6 documentation when 1.6 is released. Thx

**Comment by sallydeng** [comment]
@chenopis OK, Thx~

**Pull request merged**
