### PR TITLE
typo

### PR DESCRIPTION
**Pull request by caruccio**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.7 Features: set Milestone to `1.7` and Base Branch to `release-1.7`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4147)

### CODE REVIEW

**Comment by janetkuo** [comment]
LGTM, would you sign the CLA?

**Comment by chenopis** [comment]
@caruccio Are you having any trouble signing the CLA?

**Comment by caruccio** [comment]
Sorry, I'm in the middle of a business trip. Hope to get back to it on
monday. Thanks 4 asking.

Em 23 de jun de 2017 05:41, "Andrew Chen" <notifications@github.com>
escreveu:

**Comment by chenopis** [comment]
Looks like this was taken care of already.

**Pull request closed without merging**
