### PR TITLE
fix link in docs/getting-started-guides/kubeadm.md

### PR DESCRIPTION
**Pull request by xilabao**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2482)

### CODE REVIEW

**Comment by jbeda** [comment]
Is this breaking something?  It seems to work fine at https://kubernetes.io/docs/getting-started-guides/kubeadm/.

**Comment by chenopis** [comment]
@xilabao It's actually fine not to use the .md in the URL paths. These links seem to be working okay for me. Are you seeing a problem with them?

**Comment by xilabao** [comment]
Ah... The url paths don't work at https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/kubeadm.md

Is it not supported to do this?

**Comment by chenopis** [comment]
Ok, I see now. They don't work on the GitHub preview, but they do work on the actual site: https://kubernetes.io/docs/getting-started-guides/kubeadm/

If you look at the Netlify preview, you'll see that by adding the .md extensions, it causes a brief redirect I would like to avoid: https://deploy-preview-2482--kubernetes-io-vnext-staging.netlify.com/docs/getting-started-guides/kubeadm/

We are trying to improve the redirect mechanism, so maybe this won't be an issue in the future. Is it critical for you that the links work in the GitHub preview?

**Comment by xilabao** [comment]
@chenopis Thanks for your explain.  I just try to get the last document from the github. It's not so important for me. Closed.

**Comment by chenopis** [comment]
Ok, thanks @xilabao

**Pull request closed without merging**
