### PR TITLE
Fix the variables file path.

### PR DESCRIPTION
**Pull request by warmchang**
follow the repo "https://github.com/kubernetes/contrib".

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4483)

### CODE REVIEW

**Comment by ahmetb** [comment]
@warmchang can you please check the "Allow edits from contributors" box on the right so we can rebase then merge?

**Comment by warmchang** [comment]
@ahmetb I have checked it, thanks.

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 2df0b54006b421ff113d5c9849b27063be3c29bb

https://deploy-preview-4483--kubernetes-io-master-staging.netlify.com

**Pull request merged**
