### PR TITLE
Minor copy edits to Running Kubernetes Locally via Minikube

### PR DESCRIPTION
**Pull request by jseldess**
Removing an extra word and adding a comment.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1080)

### CODE REVIEW

**Comment by jseldess** [comment]
I signed it!

**Comment by jaredbhatti** [comment]
Can you sync with branch with the master branch?

**Comment by dlorenc** [comment]
LGTM, other than the sync.

**Comment by jseldess** [comment]
OK, sync is done, I believe. Please let me know if there's anything else.

**Pull request merged**
