### PR TITLE
More details around leader election / failure case

### PR DESCRIPTION
**Pull request by alexbrand**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1056)

### CODE REVIEW

**Comment by alexbrand** [comment]
@mikedanese added some more information about what we talked about earlier.

**Comment by devin-donnelly** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes.github.io/1056#-:-KQSQEJH73_m3iVBEW36:bnfp4nl)*

**Comment by devin-donnelly** [comment]
Merged. Thanks, Alex.

**Comment by alexbrand** [comment]
Thank you @devin-donnelly

**Pull request merged**
