### PR TITLE
Write new task: Defining a Command and Arguments for a Container.

### PR DESCRIPTION
**Pull request by steveperry-53**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1526)

### CODE REVIEW

**Comment by pwittrock** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/tasks/configure-pod-container/define-command-argument-container.md, line 26 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526#-KUYvj7VTeOB905H2psq:-KUYvj7VTeOB905H2psr:bpuix9h) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/32f45fb417fb3bf0fc29e6792fa059206af7ecd3/docs/tasks/configure-pod-container/define-command-argument-container.md#L26)):*
> ```Markdown
> containers that run in the Pod. To specify a command, include the `command`
> field in the configuration file. To specify arguments for the command, include
> the `args` field in the configuration file. The command that you specify in the
> ```

What does the args file override?  The CMD specified in the container image?  If I just specify args without command it will use the entrypoint specified the container image with the new args? 

---

*[docs/tasks/configure-pod-container/define-command-argument-container.md, line 57 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526#-KUYxuFth90H6TByFJbD:-KUYxuFth90H6TByFJbE:b-kdc0og) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/32f45fb417fb3bf0fc29e6792fa059206af7ecd3/docs/tasks/configure-pod-container/define-command-argument-container.md#L57)):*
> ```Markdown
>         tcp://10.3.240.1:443
> 
> {% endcapture %}
> ```

Should we mention that args + commands can not be updated once the Pod is created?

---

*[docs/tasks/configure-pod-container/define-command-argument-container.md, line 61 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526#-KUYxdFKwK3qciJx7b5M:-KUYxdFKwK3qciJx7b5N:b9kegpt) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/32f45fb417fb3bf0fc29e6792fa059206af7ecd3/docs/tasks/configure-pod-container/define-command-argument-container.md#L61)):*
> ```Markdown
> {% capture whatsnext %}
> 
> * Learn more about [containers and commands](/docs/user-guide/containers/).
> ```

args can also be set using configmaps, secrets, or environment variables.  Worth mentioning these in the whatsnext section.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526)*

**Comment by steveperry-53** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/tasks/configure-pod-container/define-command-argument-container.md, line 26 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526#-KUYvj7VTeOB905H2psq:-KUZThhppzTKS0hMCJow:bu8fzok) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/32f45fb417fb3bf0fc29e6792fa059206af7ecd3/docs/tasks/configure-pod-container/define-command-argument-container.md#L26)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> What does the args file override?  The CMD specified in the container image?  If I just specify args without command it will use the entrypoint specified the container image with the new args? 
</details>
Added text about defining only args.

---

*[docs/tasks/configure-pod-container/define-command-argument-container.md, line 57 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526#-KUYxuFth90H6TByFJbD:-KUZTst-_yHKPWhXUjS8:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/32f45fb417fb3bf0fc29e6792fa059206af7ecd3/docs/tasks/configure-pod-container/define-command-argument-container.md#L57)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Should we mention that args + commands can not be updated once the Pod is created?
</details>
Done.

---

*[docs/tasks/configure-pod-container/define-command-argument-container.md, line 61 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526#-KUYxdFKwK3qciJx7b5M:-KUZTv0Y5n30sM_YZE24:b-u9qddc) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/32f45fb417fb3bf0fc29e6792fa059206af7ecd3/docs/tasks/configure-pod-container/define-command-argument-container.md#L61)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> args can also be set using configmaps, secrets, or environment variables.  Worth mentioning these in the whatsnext section.
</details>
Added section about using environment variables, configmaps, and secrets.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526)*

**Comment by pwittrock** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/tasks/configure-pod-container/define-command-argument-container.md, line 75 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526#-KUZZK9B7rOIReSxUomf:-KUZZK9B7rOIReSxUomg:b-n2sthc) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/9b18efd3345496aa1e078a3c00b1b184ffec33a9/docs/tasks/configure-pod-container/define-command-argument-container.md#L75)):*
I would add a special 

>
NOTE: The environment variable appears in parenthesis "$(VAR)".  This is required for the variable to be expanded in the command or args sections.

This is easy to miss as it is different from how commands are specified in bash.

Another thing I would mention is that if the user needs their command to be execute in a shell (e.g. they want to setup a pipe), then should execute it by passing it to sh like so:

>
["/bin/sh", "-c", "while true; do sleep 1; done"]

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526)*

**Comment by pwittrock** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/tasks/configure-pod-container/define-command-argument-container.md, line 75 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526#-KUZZK9B7rOIReSxUomf:-KUbyNVI6UYbkfAm--xS:bugzr5t) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/9b18efd3345496aa1e078a3c00b1b184ffec33a9/docs/tasks/configure-pod-container/define-command-argument-container.md#L75)):*
Maybe something like:

>
Note: If your command should be executed in a shell you must wrap it like this:
command: ["/bin/sh"]
args: ["-c", "while true; do echo hello; sleep 10;done"]

This will be necessary for tasks such as shell scripting and piping commands together.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526)*

**Comment by pwittrock** [comment]
love it

**Comment by pwittrock** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1526#-:-KUdTgqwQhGVvvttnOHX:bnfp4nl)*

**Pull request merged**
