### PR TITLE
Kubernetes Basics-Overview

### PR DESCRIPTION
**Pull request by markthink**
K8S 基础教程-概述 - Kubernetes Basics Overview

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4035)

### CODE REVIEW

**Comment by chenopis** [comment]
@markthink Looks like there are some changes in this PR to core site files, such as `/Gemfile.lock` and `_includes/templates/concept.md`, which probably shouldn't be made. I'm fine w/ letting anything in the `/cn` directory being changed, and will leave that to your discretion, but none of the Chinese language changes should be made in the `/docs` directory.

**Comment by markthink** [comment]
@chenopis I only work in the / cn directory, thank you very much for your support.

**Comment by markthink** [comment]
@chenopis  I have fixed it.

**Comment by markthink** [comment]
@chenopis  The merger will be a conflict, but it does not matter, you can force to replace.

image

**Comment by chenopis** [comment]
@markthink Ok, just let me know when you open another PR for this. Thx

**Comment by markthink** [comment]
@chenopis I newly submitted a pr.
https://github.com/kubernetes/kubernetes.github.io/pull/4182

**Pull request closed without merging**
