### PR TITLE
fix borken link

### PR DESCRIPTION
**Pull request by iredwards**
my first k8s pr

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2376)

### CODE REVIEW

**Comment by chenopis** [comment]
@iredwards Thanks for finding the broken link and making a contribution. Make sure you sign the CLA so that I can merge your PR. Thx!

**Comment by iredwards** [comment]
I _think_ I have done that now, as a member of https://identity.linuxfoundation.org/content/cncf-samsung-sds-america

**Comment by iredwards** [comment]
Ahh.  Now I have signed the CLA.

**Comment by chenopis** [comment]
@iredwards Ok, great! Make sure your GitHub username is associated with the CLA and/or your email address is set for your git commits. I'll wait a bit to see if the bot picks up your new CLA status.

* If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
* If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.

**Comment by bgrant0607** [comment]
@iredwards You need to sign your commits with the same email address you used to sign the CLA.

https://help.github.com/articles/setting-your-email-in-git/
http://stackoverflow.com/questions/2919878/git-rewrite-previous-commit-usernames-and-emails

**Comment by iredwards** [comment]
user.email set to my email address

**Comment by chenopis** [comment]
@iredwards It now says "iredwards authorized, but 1 other problem". It's not clear to me what that one other problem is. LOL

**Comment by iredwards** [comment]
I think it is because I neglected to set the global setting user.email in
git on this machine I'm using now.  I set the email setting but apparently
failed to get it updated in the commit.  I deleted my local copy and cloned
it anew; I see the change I made (which surprised me).  Now I am officially
confused!  Glad I tried this first with a trivial change.  I'll try
deleting my fork and trying again, unless you have a better suggestion.
Thanks, -red

**Comment by chenopis** [comment]
@iredwards Now that you're setup correctly, maybe just redo this in a new PR. Keep it simple, right? ;-)

**Comment by iredwards** [comment]
Cool.  Reloading foot shooter...

**Comment by chenopis** [comment]
Haha. Ok, I'll close this one and look for a new PR from you.

**Pull request closed without merging**
