### PR TITLE
Update hellonode.md

### PR DESCRIPTION
**Pull request by akshayl**

### CODE REVIEW

**Comment by akshayl** [comment]
I signed it!

**Comment by bgrant0607** [comment]
cc @pwittrock @janetkuo

**Comment by pwittrock** [comment]
@akshayl  Thanks for your contribution.  The kube dashboard has a number of changes from the kubeui referenced in this document, and the section does not accurately reflect the dashboard any longer.  PR #248 should address this.  Feel free to leave review comments if there is something you see that should be changed.

**Comment by pwittrock** [comment]
Marking as closed, reopen if needed.

**Pull request closed without merging**
