### PR TITLE
Add Weave to the list of NetworkPolicy implementations

### PR DESCRIPTION
**Pull request by bboreham**
Patterned after the Calico and Romana files in the same directory.

I don't know what "assignees" does.  Hope it's something good.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1777)

### CODE REVIEW

**Comment by errordeveloper** [comment]
@jaredbhatti I've asked at the dev summit already, I do get doc PRs assigned, but don't have powers to set label or merge... PTAL, this PR LGTM.

**Comment by eparis** [comment]
Lets see if the bot is working here. Put a comment with just `/lgtm`

**Comment by errordeveloper** [comment]
@eparis I haven't see the bot around here... but yeah, let's give it a shot 👍

**Pull request merged**
