### PR TITLE
Experiment with heading levels.

### PR DESCRIPTION
**Pull request by steveperry-53**
For all tasks, tutorials, and concepts, start at heading level 2 instead of heading level 3.

Related: https://github.com/kubernetes/kubernetes.github.io/pull/2244

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2287)

### CODE REVIEW

**Comment by steveperry-53** [comment]
attn: @craigbox

**Comment by steveperry-53** [comment]
cc: @devin-donnelly @chenopis @jaredbhatti

**Comment by jaredbhatti** [comment]
This makes a lot more sense to me from a doc structuring standpoint.  Do we have to update a lot of docs with this?

**Comment by craigbox** [comment]
Contributed docs (Guides?) seem to use either h2/h3 or h3/h4 - both seem to look the same in the ToC. First example I found

https://kubernetes.io/docs/user-guide/load-balancer/
https://kubernetes.io/docs/user-guide/services-firewalls/

This one even has a h1 where it shouldn't be, messing the ToC up:

https://kubernetes.io/docs/user-guide/compute-resources/#meaning-of-memory

**Comment by steveperry-53** [comment]
>Contributed docs (Guides?) seem to use either h2/h3 or h3/h4 - both seem to look the same in the ToC.

This PR is concerned only with Tasks, Tutorials, and Concepts. We in the process of gradually moving topics out of Guides into Tasks, Tutorials, and Concepts. As we move topics, that's when we can apply the templates and the consistent headings. For example, see https://github.com/kubernetes/kubernetes.github.io/pull/2226 and https://github.com/kubernetes/kubernetes.github.io/pull/2289.

**Comment by steveperry-53** [comment]
> This makes a lot more sense to me from a doc structuring standpoint. Do we have to update a lot of docs with this?

I'll need to add all of the existing Task, Tutorial, and Concept pages to this PR. That's not a terribly big job. I'll get started now.

**Comment by steveperry-53** [comment]
@craigbox, Do you have any more feedback before I merge this?

**Comment by craigbox** [comment]
For the scope of this PR - looking at https://deploy-preview-2287--kubernetes-io-vnext-staging.netlify.com/docs/concepts/abstractions/controllers/statefulsets/ for example, LGTM

**Pull request merged**
