### PR TITLE
New Docs Landing Page and ToC Organization.

### PR DESCRIPTION
**Pull request by devin-donnelly**
This is a Work-In-Progress change to the main documentation landing page (kubernetes.io/docs) experience. I'm experimenting with the ToC both above and to the left of the pages. Please do not merge; this change will need a detailed review with project stakeholders.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1468)

### CODE REVIEW

**Comment by pwittrock** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/index.md, line 8 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468#-KUSwiVqNEGEPl4p1vTv:-KUSwiVqNEGEPl4p1vTw:b-w4q0e0) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/52ceb6525b5d1ae5bd11705d37492ba5d8f698b8/docs/index.md#L8)):*
> ```Markdown
> ---
> 
> <p>Kubernetes is an open source, production-ready cluster management and container orchestration system. With Kubernetes on your cluster, you can ensure that your containerized applications and other cloud-based workloads run where you want them, when you want them, and with the resources that they need.</p>
> ```

I'd start out with a super simple explanation of the problem kubernetes solves:  `Kubernetes runs and manages containers running in a cluster.`
Then list out some of the aspect buzzwords that we might think are important:

- Open-source
- Production ready
- Simple cluster setup with kubeadm
- Baremetal or VMs

Consider also including some of the core functionality highlights beyond running containers:

- Service discovery and load balancing
- Configuration management
- Cluster federation

---

*[docs/index.md, line 93 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468#-KUSxxei940qamcW1BiY:-KUSxxei940qamcW1BiZ:b-98ssrr) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/52ceb6525b5d1ae5bd11705d37492ba5d8f698b8/docs/index.md#L93)):*
> ```Markdown
>   </div>
>   <div class="col2nd">
>     <h4>Installing Kubernetes on Linux with kubeadm</h4>
> ```

We should probably first direct users to installing k8s for local development using minikube before introducing this.  Make it clear that one is for development and the other for running real workloads

---

*[docs/index.md, line 94 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468#-KUSxZdWFV4Oscbz5z2N:-KUSxZdXLU8byTNmUI2i:b-rq17uq) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/52ceb6525b5d1ae5bd11705d37492ba5d8f698b8/docs/index.md#L94)):*
> ```Markdown
>   <div class="col2nd">
>     <h4>Installing Kubernetes on Linux with kubeadm</h4>
>     <p>This quickstart helps you install a secure Kubernetes cluster using the built-in <code>kubeadm</code> tool. You can use <code>kubeadm</code> to install Kubernetes on any computers running Linux&emdash;it works with local VMs, physical servers, or cloud servers. You can use <code>kubeadm</code> manually or as part of your own automation. <code>kubeadm</code> is currently an alpha feature, but we invite you to try it out and give us feedback!</p>
> ```

Doesn't display properly

---

*[docs/index.md, line 94 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468#-KUSxd9KX18diVOa3Amt:-KUSxd9KX18diVOa3Amu:beg7znb) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/52ceb6525b5d1ae5bd11705d37492ba5d8f698b8/docs/index.md#L94)):*
> ```Markdown
>   <div class="col2nd">
>     <h4>Installing Kubernetes on Linux with kubeadm</h4>
>     <p>This quickstart helps you install a secure Kubernetes cluster using the built-in <code>kubeadm</code> tool. You can use <code>kubeadm</code> to install Kubernetes on any computers running Linux&emdash;it works with local VMs, physical servers, or cloud servers. You can use <code>kubeadm</code> manually or as part of your own automation. <code>kubeadm</code> is currently an alpha feature, but we invite you to try it out and give us feedback!</p>
> ```

Does this mean it installs the whole cluster including spinning up vms, or it installs kubernetes onto an existing set of running machines?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468)*

**Comment by devin-donnelly** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/index.md, line 8 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468#-KUSwiVqNEGEPl4p1vTv:-KUThBVI9iOLIaPH2oB8:bwjmion) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/52ceb6525b5d1ae5bd11705d37492ba5d8f698b8/docs/index.md#L8)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> I'd start out with a super simple explanation of the problem kubernetes solves:  `Kubernetes runs and manages containers running in a cluster.`
> Then list out some of the aspect buzzwords that we might think are important:
> 
> - Open-source
> - Production ready
> - Simple cluster setup with kubeadm
> - Baremetal or VMs
> 
> Consider also including some of the core functionality highlights beyond running containers:
> 
> - Service discovery and load balancing
> - Configuration management
> - Cluster federation
> 
</details>
I've pared it down significantly and made it simpler. PTAL.

---

*[docs/index.md, line 93 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468#-KUSxxei940qamcW1BiY:-KUTgkCIKKj1Fru3EA-i:bm1207) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/52ceb6525b5d1ae5bd11705d37492ba5d8f698b8/docs/index.md#L93)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> We should probably first direct users to installing k8s for local development using minikube before introducing this.  Make it clear that one is for development and the other for running real workloads
</details>
We should add an additional quickstart for local development with Minikube.

---

*[docs/index.md, line 94 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468#-KUSxd9KX18diVOa3Amt:-KUTgGv2NEUzrrtu0uvT:b-quvkmk) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/52ceb6525b5d1ae5bd11705d37492ba5d8f698b8/docs/index.md#L94)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Does this mean it installs the whole cluster including spinning up vms, or it installs kubernetes onto an existing set of running machines?
</details>
From reading the kubeadm docs, you need to have existing machines running Ubuntu or CentOS, so it does not appear to spin up VMs for you.

---

*[docs/index.md, line 94 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468#-KUSxZdWFV4Oscbz5z2N:-KUTggv4QRJHBIdV8xHu:be6y4va) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/52ceb6525b5d1ae5bd11705d37492ba5d8f698b8/docs/index.md#L94)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Doesn't display properly
</details>
Fixed. I also pared down some of the extraneous explanation.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468)*

**Comment by devin-donnelly** [comment]
So the basic things I want to accomplish with a review:

- Do we want all this information on the landing page?
- Do we want a separate sub-landing page for Quickstarts? That's more scalable than packing them all onto the front page.
- Should we add top-level site nav for "Quickstarts"? It's awfully crowded up there.
- We need to mark or otherwise notify folks that "Guides" are deprecated and the content is migrating to new sections (Tutorials, Tasks, Concepts).

**Comment by devin-donnelly** [comment]
Further questions:

- Do we want a simpler landing page with just direct links to the major sections and very brief explanations? Or do we want to be slightly more verbose? The current proposal is "slightly more verbose", because I find the site navigation confusing with the major headers in the top nav bar and sub-TOCs to the left.
- Do we want to keep the samples and contributor evangelism?

**Comment by pwittrock** [comment]
My $0.02

- Yes to simple landing page with direct links routing users based on their intended goals and background
- I would get rid of samples and contributor evangelism from the landing page.  
- Guides is still where most of the content exists.  We shouldn't deprecate it until Tutorials + Tasks + Concepts is at least comparable in terms of content
- Quickstarts for top-level: probably not if the landing page is simple enough that it is highly discoverable

---

Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/index.md, line 93 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468#-KUSxxei940qamcW1BiY:-KUTqinbi4v8WdN1qENA:b-5ah456) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/52ceb6525b5d1ae5bd11705d37492ba5d8f698b8/docs/index.md#L93)):*
<details><summary><i>Previously, devin-donnelly wrote…</i></summary>
> We should add an additional quickstart for local development with Minikube.
</details>
Can we just link to minikube for now?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1468#-:-KUTqtqruIARw18cdPNn:b-mo7zxt)*

**Comment by devin-donnelly** [comment]
From collected feedback from @pwittrock and @bgrant0607 , I've made a few changes:

- Removed overview text; I'll move it to the main page.
- Removed Samples and Contribution Evangelism

Still to-do:

- I could use some CSS/layout help in getting things rendering like "tiles" if we want to do it that way.

**Comment by bgrant0607** [comment]
@bryk We could use some layout help with kubernetes.io. Do you think someone in the UI SIG could help with that?

**Comment by bryk** [comment]
> @bryk We could use some layout help with kubernetes.io. Do you think someone in the UI SIG could help with that?


Yep, definitely. Can you describe what is needed to be done? We haven't been following this topic so far. 

cc @romlein @rf232

**Comment by romlein** [comment]
@bgrant0607 I have limited availability pre-KubeCon, but I would definitely like to help out with layout. What's the best way for me to come up to speed on what's been done so far and what the specific needs are?

**Comment by bgrant0607** [comment]
@romlein 

This is the new docs landing page. Our original idea for the layout was a card-based approach. Mock:

https://docs.google.com/presentation/d/14mJwJGlwBJHIpMRGR-nYMSyyNk-kRpabyz74-YYXeTo/edit#slide=id.g12dfc4542a_17_14

The current layout in this PR can be seen here:

https://deploy-preview-1468--kubernetes-io-vnext-staging.netlify.com/docs/

It's a mix of multi-column and single-column.

**Comment by bgrant0607** [comment]
@devin-donnelly 

Things I think are important to fix:
* Kubernetes in the heading is misspelled
* Quickstarts take up so much space that the rest of the content is pushed off the first screen -- could we just link to the bootcamp, remove the other 2 "quickstarts", and convert it to the same wide format as the rest of the page?
* I think this may steer users in the wrong direction with respect to figuring out how to create a Kubernetes cluster
  * K8s on AWS is the first option I see
  * kubeadm is under it, and is only alpha
  * The Tutorials description makes me think it will explain how to set up clusters, but doesn't currently
  * The Guides description makes me think it won't cover cluster creation, but that's in fact where all the relevant content is
  * There's no link to docs/getting-started-guides/, which contains the guide that is intended to help users to choose a solution, including GKE
  * That guide doesn't mention kops nor kubeadm

**Comment by devin-donnelly** [comment]
@bgrant0607 , PTAL.

I think this addresses more or less all of your feedback. However, some things to note:

- Tutorials eventually WILL explain how to set up clusters
- Guides will eventually be deprecated
- Getting Started Guides is fine for now, but we should probably revisit Picking the Right Solution in the near future and look at how we provide an "on-ramp" for various ways to install and set up the system

**Comment by bgrant0607** [comment]
@devin-donnelly LGTM, thanks. Please squash, remove WIP from the title, and feel free to merge when you're ready.

**Comment by danielromlein** [comment]
Sorry, I lost track of this with KubeCon. Is there still anything that would benefit from having a designer check it out @bgrant0607?

**Comment by bgrant0607** [comment]
@danielromlein Thanks for checking in. I believe we're looking into getting help from the original vendor that produced the kubernetes.io home page.

**Comment by danielromlein** [comment]
Sounds good @bgrant0607! Keep me posted 👍

**Pull request merged**
