### PR TITLE
add GCR and ECR for private registries

### PR DESCRIPTION
**Pull request by Bradamant3**
First PR for the docs, please be kind :-)
Q: what do y'all think of also adding links FROM this topic: /docs/concepts/containers/images/#using-a-private-registry

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4336)

### CODE REVIEW

**Comment by steveperry-53** [comment]
Thanks @Bradamant3. I'll take a look and have some feedback by Wednesday, 7/12.

**Comment by steveperry-53** [comment]
@Bradamant3, I'd like to spend some more time studying these two new topics, but here are a few comments to start with.

* There are some rendering issues that you can see in the [Netlify preview](https://deploy-preview-4336--kubernetes-io-master-staging.netlify.com/docs/tasks/configure-pod-container/pull-image-gcr). For example, some links aren't rendering correctly, and the indentation is too deep for some code snippets.

* Check the [style guide](https://deploy-preview-4336--k8sio-netlify-move.netlify.com/docs/home/contribute/style-guide/) for guidance on using caps for API objects.

* I think the opening sentence gets the topic off track. That is, it starts out by talking about having your cluster on GCE or GKE. But that shouldn't be the point in a kubernetes.io topic. The scenario should be that your cluster can be anywhere, and you want to pull an image from the GCR of some GCP project. For examples: gcr.io/google_containers/<image-name> or gcr.io/google-samples/<image-name>.

* If you want the topic to be about pulling private images from your own GCR in your own GCP project, then I think the title should make that clear.

* If the reader must have a GCP project, then the prerequisites should make that clear. If the reader must have the Google Cloud SDK (including the gcloud tool) installed, then the prerequisites should make that clear.

* Given the current title, I prefer specifying imagePullSecrets on an individual Pod. But then, I think you should show a kubectl command that would actually cause the image to be pulled. Say kubectl create -f the-pod.yaml.

* Patching the default service account is interesting, but consider a separate topic to cover that. Or call out the two approaches with headings: ## Patch the default service account, ## Include your Secret in a Pod configuration file.

* Our general guideline in tasks is to avoid placeholders and choice. So if the reader needs to create a Secret, I think it's best to avoid having the reader choose a name for the Secret. Instead, you could just tell the reader to create a Secret named Bob (or whatever). Same for the JSON filename. You could just choose a name and stick with it.

**Comment by steveperry-53** [comment]
@Bradamant3, Here are some comments on the ECR topic.

* The intro says the topic applies only to running a cluster on AWS. But the prerequisites say you can use Minikube.

* The title doesn't really match the content. Maybe the title should be something like Configuring Access Management for ...

* If you decide that the topic should be about pulling an image, show a command that pulls an image. I'm not sure what that looks like for AWS.

**Comment by steveperry-53** [comment]
As I look again at the ECR topic, it seems that maybe it doesn't belong in the kubernetes.io docs. I don't see any Kubernetes content; I see only AWS content. So maybe the topic belongs in the AWS docs.

**Comment by Bradamant3** [comment]
Many thanks for all the detailed comments; I'll try to get to them by the end of the week but unfortunately another deadline has intervened. Everything you say makes sense, though, and I'll be sure to check the build more carefully next time too. I see what you mean about the ECR topic, and I'll look again at the big related concept topic that I linked to in my first comment (/docs/concepts/containers/images/#using-a-private-registry)

**Comment by ahmetb** [comment]
I like the idea of having these docs, but there are other registries too (e.g. Azure, Quay) and I'm trying to see if having all these pages would scale. Just like over time we got rid of cloud-specific cluster setup instructions, these may soon become obsolete too. It's always nice to link out to vendor websites as they usually tend to keep their content more up to date.

Specifically in GCR page, it is probably worth mentioning that GKE clusters can use the project's container registry out-of-the-box, without configuring any secrets.

**Comment by ahmetb** [comment]
I just looked at the commit history, looks like you removed ECR and kept GCR –and both of these pages are very similar.  I did not mean to say "remove ECR and keep GCR" by any means (I don't think @steveperry-53 meant to say that either).

If these vendor-specific instructions are not Kubernetes-heavy content, they probably should be hosted in vendor’s website and not kubernetes.io. @steveperry-53 please chime in.

**Comment by steveperry-53** [comment]
@ahmetb, @Bradamant3, I think the ECR topic should not be in the kubernetes.io docs. The ECR topic is only about AWS. That is, the reader is using both an AWS registry and AWS nodes. I think it (maybe) makes sense for the GCR topic to be in the kubernetes.io docs. In the GCR topic, the reader is using a GCR registry, but is not necessarily using GCP nodes.

**Comment by Bradamant3** [comment]
I meant to add more comments first, but y'all beat me to it. I was thinking along the same lines as @steveperry-53 wrt the AWS topic being only about AWS (point well taken). The GCR topic on the other hand is about how to map GCR info into a K8s secret -- I at least wrote it thinking more in terms of K8s than GCR. So to that extent it's meant as a parallel topic to the one about Docker (which after all isn't K8s either although everything K8s more or less depends on it). I even "borrowed" more of Steve's language from the Docker registry topic to try to make the parallelism point implicitly. But I'm a newcomer, not trying to belabor the point but explain what I was trying to do and how I thought of the larger picture, especially in light of Steve's comments.

**Comment by ahmetb** [comment]
The worry of maintaining the external links is probably less than having a complete page that may contain out-of-date information. :)

The part I'm worried more is that there are other registries: Azure Container Registry (ACR), or Quay.io can be used without using Azure nodes, too. (So, GCR is not the only one.) Should this mean they can have a page on Kubernetes.io? I think it would be really neat for us if all providers create documentation on their websites on "how to use xCR on Kubernetes" and we could just link to them.

Alternatively, maybe we can make `#using-a-private-registry` a real document, and have examples of all these on the website. (Again, if they already have a page about it, we should just link out there.)

**Comment by Bradamant3** [comment]
There seems to be some interest in this content, but it also seems as though the core docs may not be the right place for it, at least not in this form. I'll look more carefully at Ahmet's suggestion to "make #using-a-private-registry a real document". With thanks to Steve and Ahmet for your careful reviews, I'm closing this PR at least for now.

**Pull request closed without merging**
