### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by FGRibreau**
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3102)

### CODE REVIEW

**Comment by FGRibreau** [comment]
I signed it!
ᐧ

**Comment by fgrzadkowski** [comment]
Thanks for the fix!

**Pull request merged**
