### PR TITLE
Highlighted command --kubectl describe

### PR DESCRIPTION
**Pull request by jianglingxia**
In web page ,there is no space ,need some empty space,thanks!

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2678)

### CODE REVIEW

**Comment by chenopis** [comment]
@jianglingxia I don't see the change you are referring to in the title of this PR. The changes look the same as a previous PR. Perhaps there is an issue w/ your git branch?

screen shot 2017-03-03 at 12 14 27 am

**Comment by jianglingxia** [comment]
choose the file  to  :docs/user-guide/kubectl/kubectl_describe.md  according to the title ,   a70d0a3: Highlighted command --kubectl describe

**Comment by chenopis** [comment]
@jianglingxia Strange. It's not showing up in the *Files changed* tab. I can only see it if I directly go to that commit.

**Comment by jianglingxia** [comment]
yes ,at that time I make a mistake result to the problem ,but now I don't know how to solve the problem?I want to delete the commit but not found the button,or I create a new branch to pull a new  request?can you help me?thanks!

**Comment by chenopis** [comment]
@jianglingxia Are you using the website's edit function (see below screenshot) or the git command line or a git client to submit this pull request (PR)? 

ygn9qrixhve

For simple changes, the [website's edit function](https://github.com/kubernetes/kubernetes.github.io/edit/master/docs/admin/cluster-components.md) is easiest. However, if you are using the git command line or client, there are a few options for how to fix it:

- The proper way is probably to do a rebase, see [http://stackoverflow.com/questions/36168839/how-to-remove-commits-from-pull-request](http://stackoverflow.com/questions/36168839/how-to-remove-commits-from-pull-request).
- Or you can just make the change again and add another commit to the PR.
- However, since you have a lot of unrelated commits in this PR, you might want to just start over and create a new branch from the current `kubernetes:master`, submit a new PR, and close this one.

**Comment by jianglingxia** [comment]
I have create a new branch and add another commit to the PR,so I will close the request,thanks!

**Comment by chenopis** [comment]
Ok, thanks!

**Pull request closed without merging**
