### PR TITLE
apps/v1beta1 is not valid

### PR DESCRIPTION
**Pull request by campoy**
Replacing it with extensions/v1beta1 which actually works

Found this file from this document: 
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.7 Features: set Milestone to `1.7` and Base Branch to `release-1.7`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3814)

### CODE REVIEW

**Comment by foxish** [comment]
apps/v1beta1 is correct, and newer. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#deployment-2

**Comment by chenopis** [comment]
@foxish So can I close this PR?

**Comment by campoy** [comment]
When was this changed?

It still fails for me with this kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

Trying to create a deployment using `apps/v1beta1` gives:

```
error: error validating "kubernetes.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by foxish** [comment]
The server version needs to be 1.6 or higher for it to work. https://github.com/kubernetes/kubernetes/pull/39683 added the new apps/v1beta1.Deployment which will become the default eventually and we'll deprecate extensions/v1beta1.Deployment by the year end. See https://github.com/kubernetes/kubernetes/issues/43214

**Comment by foxish** [comment]
In the absence of versioned docs (as opposed to docs that reflect the latest version only), we can't make this change. cc @janetkuo @kubernetes/sig-apps-misc

**Comment by kargakis** [comment]
Yeah, we really need versioned docs.

**Comment by campoy** [comment]
Agreed, versioned docs are essential here.

In the meanwhile, could we add a note about how in previous versions the value is different?
This was very confusing for me

**Comment by foxish** [comment]
I think a note makes total sense! @campoy, can you modify your PR to add that? Also I think you'll need to sign the CLA. It can be in manner similar to how the node controller [specifies pre-1.5 behavior](https://kubernetes.io/docs/concepts/architecture/nodes/#condition). Thanks!
@chenopis, In the long term, perhaps we should come up with a standard way to call out such changes in docs.

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers is there any discussion somewhere re versioned docs?

**Comment by campoy** [comment]
PTAL

**Comment by campoy** [comment]
I am authorized to contribute, as a Google employee

**Comment by foxish** [comment]
I was thinking more along specifying the constraint in the text description surrounding the YAML. @chenopis WDYT of comments inline in the YAML itself?

**Comment by campoy** [comment]
Well, I don't know from how many places this specific file is embedded.
If it's only one I could easily add a note there

**Comment by chenopis** [comment]
Yeah, I like this solution. YAML comments works for me! /lgtm

**Comment by campoy** [comment]
ping

**Comment by janetkuo** [comment]
Agree with @chenopis, lgtm

**Comment by janetkuo** [comment]
I saw a similar fix (closed) for this earlier, which proved that this is confusing enough for a fix

**Pull request merged**
