### PR TITLE
Updates on the PV zone affinity documentation

### PR DESCRIPTION
**Pull request by jrnt30**
Updates docs around the PV distribution process per the linked issues

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2072)

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/admin/multiple-zones.md, line 193 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2072#-K_6Wj0nMcId8Jl9CZK0:-K_6Wj0nMcId8Jl9CZK1:b-sko0zp) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/528c98f4f471d12fc97cb906a0d74fa583e574f7/docs/admin/multiple-zones.md#L193)):*
> ```Markdown
> the configured zones.
> 
> For version 1.2, dynamic persistent volumes are 
> ```

Since this documentation applies to stable, s/are/were

---

*[docs/admin/multiple-zones.md, line 195 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2072#-K_6W_UDbN3OY48lLnJz:-K_6W_UDbN3OY48lLnK-:b-7296tp) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/528c98f4f471d12fc97cb906a0d74fa583e574f7/docs/admin/multiple-zones.md#L195)):*
> ```Markdown
> For version 1.2, dynamic persistent volumes are 
> always created in the zone of the cluster master 
> (here us-central1-a / us-west-2a); this was addressed in 1.3+ via 
> ```

"that issue ([#23330](...)) is resolved in 1.3+."

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2072)*

**Comment by jrnt30** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/admin/multiple-zones.md, line 193 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2072#-K_6Wj0nMcId8Jl9CZK0:-K_6mbF8jNKsn7vBuuHp:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/528c98f4f471d12fc97cb906a0d74fa583e574f7/docs/admin/multiple-zones.md#L193)):*
<details><summary><i>Previously, jlowdermilk (Jeff Dempsey) wrote…</i></summary><blockquote>

Since this documentation applies to stable, s/are/were
</blockquote></details>

Done.

---

*[docs/admin/multiple-zones.md, line 195 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2072#-K_6W_UDbN3OY48lLnJz:-K_6medXLEViEugEwiaz:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/528c98f4f471d12fc97cb906a0d74fa583e574f7/docs/admin/multiple-zones.md#L195)):*
<details><summary><i>Previously, jlowdermilk (Jeff Dempsey) wrote…</i></summary><blockquote>

"that issue ([#23330](...)) is resolved in 1.3+."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2072)*

**Comment by jlowdermilk** [comment]
lgtm thanks. Please squash and I'll add tag

**Comment by jrnt30** [comment]
@jlowdermilk Done.  In general, do you find it's easier to have individuals do the squash?  I personally prefer the new "[Squash And Merge](https://github.com/blog/2141-squash-your-commits)" command in Github to avoid the hassle for people and the potential for mistakes

**Comment by jlowdermilk** [comment]
Actually this is the first time I'm hearing about squash and merge. Thanks for the tip, I will use it in future

Looks like you need to rebase, but otherwise lgtm.

**Comment by jlowdermilk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2072#-:-K_petJpPk3_ugtykNRC:bnfp4nl)*

**Comment by jrnt30** [comment]
I had done so as of yesterday.  I am not sure how this git repo is setup, but forcing a rebase every time the origin/master is changed is not viable.  If the Squash and merge (or my preivous squash and merge commit and the merge commit I just made) is not sufficient, I can just close this.

**Comment by chenopis** [comment]
Commit checks look good now.

**Pull request merged**
