### PR TITLE
Fixed environment variables use-case for ConfigMap

### PR DESCRIPTION
**Pull request by slintes**

### CODE REVIEW

**Comment by slintes** [comment]
I signed it!

**Comment by bgrant0607** [comment]
cc @pmorie

**Comment by johndmulhausen** [comment]
@bgrant0607 should I wait for @pmorie to comment, or will @janetkuo's LGTM suffice? Pretty small edit, I was about to wave it in.

**Comment by pmorie** [comment]
lgtm

**Pull request merged**
