### PR TITLE
added vsphere RWX note

### PR DESCRIPTION
**Pull request by ReSearchITEng**
tested on k8s 1.6.4, rh/centos 7.3.
Adding: @divyenpatel 

> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.7 Features: set Milestone to `1.7` and Base Branch to `release-1.7`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4117)

### CODE REVIEW

**Comment by divyenpatel** [comment]
We can access PV in multiple pod if they are on the same node VM.
but this should not create confusion. 

User should not specify ReadWriteMany in the PVC spec for vSphere cloud provider.

```
spec:
  accessModes:
    - ReadWriteMany 
```



adding team: @luomiao @rohitjogvmw @BaluDontu @tusharnt

**Comment by chenopis** [comment]
Is this ready to be merged, or does there need to be any further discussion?

**Comment by ReSearchITEng** [comment]
I guess we should add the same comment for ROX.  @divyenpatel, is this
correct?

**Comment by divyenpatel** [comment]
VsphereVolume does not have ReadOnly volume support. ReadWriteMany on collocated PODs is fine.

**Pull request merged**
