### PR TITLE
Update centos_manual_config.md

### PR DESCRIPTION
**Pull request by alanld407**
fix typo
Remove $ so that it is easier to cut and paste into shell without the need to edit in text editor.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2165)

### CODE REVIEW

**Comment by alanld407** [comment]
I signed it! 

    On Saturday, January 7, 2017 9:04 AM, k8s-ci-robot <notifications@github.com> wrote:
 

 Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA). 📝 Please follow instructions at https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ to sign the CLA.Once you've signed, please reply here (e.g. "I signed it!") and we'll verify. Thanks.   
   - If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
   - If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
 Instructions for interacting with me using PR comments are available here. If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository. I understand the commands that are listed here. —

**Comment by thockin** [comment]
Need to wait for CLA to clear, but otherwise LGTM

**Comment by chenopis** [comment]
@alanld407 I'm not sure why the CLA didn't clear when you signed it before, but could you try signing it again? Thx

**Comment by chenopis** [comment]
@alanld407 Since this was Tech LGTM'ed, I'm going to just close this PR and reimplement it. We'll have to track down the issue w/ the CLA signing separately.

**Pull request closed without merging**
