### PR TITLE
Modify some of the syntax errors in the Chinese document 'expose-intro'

### PR DESCRIPTION
**Pull request by Lion-Wei**
> Changed some inconvenient sentence. Hope to join this work.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.8 Features: set Milestone to `1.8` and Base Branch to `release-1.8`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box (see image below) to
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4737)

### CODE REVIEW

**Comment by Lion-Wei** [comment]
have been assigned

**Comment by chenopis** [comment]
@markthink Can someone review this?

**Comment by tengqm** [comment]
Two questions:
1. Whether we should translate the markdown files or the HTML files. I'd suggest we work on markdown files directly. 

2. For ease of review, can we add some wraps to the doc? It is very difficult to view the diffs given that the browser doesn't do auto wrapping.

**Comment by Lion-Wei** [comment]
@tengqm 
1. I think markdown files is more convenience, but this file is HTML, maybe because the original file is HTML too.
2. I will do it later.

**Comment by chenopis** [comment]
Yes, this is a very old tutorial, so it was written in HTML instead of markdown.

**Pull request closed without merging**
