### PR TITLE
Adding travis checks for linter (md-check).

### PR DESCRIPTION
**Pull request by foxish**
Additions to travis to execute checks from the md-check linter.

Issue: https://github.com/kubernetes/kubernetes/issues/31264

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1101)

### CODE REVIEW

**Comment by foxish** [comment]
We can turn on more linters in future, after we fix these issues.
cc @jaredbhatti @devin-donnelly

**Comment by foxish** [comment]
Based on my discussion with @devin-donnelly, we're going to go ahead and turn on these linters incrementally but with close attention to the larger effort of fixing the docs, so as to not get in the way of that.

**Comment by foxish** [comment]
@pwittrock @Kashomon PTAL.

**Comment by jaredbhatti** [comment]
I don't see the benefits of merging this change.  In fact, I see this drastically slowing down the process of submitting new documentation if we're linting every single doc change.  Let's chat about this before we merge so I can better understand the goal, here.

**Comment by jaredbhatti** [comment]
Foxish - thanks for taking the time with me and sitting down and chatting.  This current change only verifies that the markdown is valid - that is, it renders correctly to HTML.  We decided NOT to pursue whitespace verification, nor to verify analytics (since they're already integrated into page templates).  Likewise, any additional tests will be verified with the docs team.

**Pull request merged**
