### PR TITLE
[OpenStack-Heat] Use openstackclient to list the Heat stack

### PR DESCRIPTION
**Pull request by sc68cal**
python-openstackclient is a more modern tool

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2290)

### CODE REVIEW

**Comment by sc68cal** [comment]
When running `heat stack-list` or other commands you get the following warning:

```
WARNING (shell) "heat stack-list" is deprecated, please use "openstack stack list" instead
```

**Comment by sc68cal** [comment]
Hmm, that "update branch" button is ... less than helpful. Let me rebase it.

**Comment by chenopis** [comment]
@idvoretskyi Can you take a look? Thx

**Comment by chenopis** [comment]
@sc68cal you also might want to change the preceding sentence so that it doesn't mention heat.

**Comment by idvoretskyi** [comment]
cc @k8s-sig-openstack-pr-reviews

**Comment by xsgordon** [comment]
LGTM, but needs rebase.

**Pull request merged**
