### PR TITLE
Doc Bug: 64Mib is 2^26 and not 2^20

### PR DESCRIPTION
**Pull request by krmayankk**
Please help fix this

### CODE REVIEW

**Comment by johndmulhausen** [comment]
@krmayankk please sign the CLA

**Comment by krmayankk** [comment]
@johndmulhausen we are almost there. The CLA is being signed on behalf by our company. Once its signed, this would automatically show up here as long as my official email address is attached to this profile and that email address is part of the group, though which the signing happens right ?

**Comment by krmayankk** [comment]
@johndmulhausen 
Can you check, my CLA was signed and approved as a corporation by Salesforce Inc

**Comment by krmayankk** [comment]
@johndmulhausen can you please verify , my CCLA was signed by Salesforce

**Comment by krmayankk** [comment]
I signed it!

**Comment by krmayankk** [comment]
@johndmulhausen Can you please update cla label, my CLA is signed and approved by Salesforce

**Comment by pwittrock** [comment]
@krmayankk I am going to try and figure out why your cla for salesforce isn't working.

**Comment by krmayankk** [comment]
Thanks @pwittrock really appreciate it. One thing to note is that earlier this account was not associated with Salesforce account but now it's associated so I think the bot should pick up right ?

**Comment by pwittrock** [comment]
cc @lavalamp 

@krmayankk Is the email address you used for the commit the email address that is part of the group?  You can have multiple email addresses associated with your GH account, but your Git client only has 1 email associated with it.

**Comment by krmayankk** [comment]
@pwittrock i used the online kubernetes.github.io to make the PR. My primary email address on my github profile is my salesforce account. When i made this  PR, it was another personal email but i switched it later and just to make sure i made two more PR's later :-) but none of them are picking my email address it seems

https://github.com/kubernetes/kubernetes.github.io/pull/768
https://github.com/kubernetes/kubernetes.github.io/pull/806

**Comment by lavalamp** [comment]
From the command line, `git reset --soft HEAD^ && git add <change files> &&
git commit` will remake a commit and drop in the email set in your git
config. There's probably a better way, but that will get the job done. Not
sure if that'll be possible from the github interface.

**Comment by krmayankk** [comment]
@pwittrock @lavalamp thanks guys. i just resubmitted from a fork now. Here is the 4 PR for this doc bug :-). thanks for the help, cla shows yes now 

https://github.com/kubernetes/kubernetes.github.io/pull/864

**Comment by pwittrock** [comment]
Merged #864

**Pull request closed without merging**
