### PR TITLE
Initial docs for envFrom ConfigMap

### PR DESCRIPTION
**Pull request by fraenkel**
corresponds to proposal https://github.com/kubernetes/community/pull/148

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1967)

### CODE REVIEW

**Comment by chenopis** [comment]
@pmorie can you verify that the yaml looks good so I can merge the request? thx

**Comment by chenopis** [comment]
@fraenkel So is this for 1.6? If so, I'll tag it so that it's not merged before we open a branch for 1.6

**Comment by fraenkel** [comment]
Yes, this is 1.6

**Comment by chenopis** [comment]
@fraenkel FYI, the kubernetes:release-1.6 branch is now available. Please change the base branch to that. Thx

**Comment by fraenkel** [comment]
@chenopis Base branch is now release-1.6

**Comment by zhangxiaoyu-zidif** [comment]
If the context contains some symbols like "v1.6 above only", that would be much better. 
At first sight, I think it was a bug at first sight,=) , because my env is v1.5.2.

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif Do you want to add that to the documentation as a note in another PR?

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis I‘d like to. PTAL https://github.com/kubernetes/kubernetes.github.io/pull/3511
Thanks.=)

**Pull request merged**
