### PR TITLE
Used master branch to link files from the repo

### LINKED ISSUE #1269: Links pointing to release-1.3 branch which does not exist
All the links in the documentation are pointing to `release-1.3` branch. To name a few:
- http://kubernetes.io/docs/user-guide/connecting-applications/ is pointing to `run-my-nginx.yaml` ->  https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/release-1.3/docs/user-guide/run-my-nginx.yaml
- http://kubernetes.io/docs/user-guide/jobs/, pointing to `job.yaml` -> https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/release-1.3/docs/user-guide/job.yaml

@devin-donnelly could we create such a branch or you prefer to wait for 1.4 and have it working then?

### PR DESCRIPTION
**Pull request by rnaveiras**
Fixes #1269

/cc @devin-donnelly

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1331)

### CODE REVIEW

**Comment by pwittrock** [comment]
@devin-donnelly I don't know anything about this file :P  Let me know if I need to figure it out.

**Comment by rnaveiras** [comment]
@devin-donnelly a simple link to see that is working now:

http://deploy-preview-1331.kubernetes-io-vnext-staging.netlify.com/docs/user-guide/deploying-applications/

In this section, int he deploy-preview, you can see that the link for `run-my-nginx.yaml` now works as expected.

**Comment by rnaveiras** [comment]
hey @devin-donnelly did you have time to look at this? Let me know if I can help...

**Comment by devin-donnelly** [comment]
Thanks! I'll go ahead and merge this.

**Pull request merged**
