### PR TITLE
Update Calico docs link

### PR DESCRIPTION
**Pull request by gunjan5**
Point to the latest stable Calico version docs link

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1971)

### CODE REVIEW

**Comment by gunjan5** [comment]
I signed it!

Gunjan Patel

**Comment by gunjan5** [comment]
I signed it!

**Comment by caseydavenport** [comment]
This LGTM.

**Comment by caseydavenport** [comment]
@gunjan5 this looks like it needs a rebase.

@devin-donnelly Doesn't look like anyone has been auto-assigned as a reviewer.  Could you merge once rebased?

**Pull request merged**
