### PR TITLE
Update broken links to fix directs

### PR DESCRIPTION
**Pull request by kairen**
Fix broken links, because some of these broken links are due to the recent PR kubernetes/community#1010.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5630)

### CODE REVIEW

**Comment by chenopis** [comment]
FYI, this is an autogenerated doc, so changes need to be made upstream. I need to track down where that is exactly.

**Comment by kairen** [comment]
@chenopis Okay!

**Comment by xiangpengzhao** [comment]
The original place is in the upstream here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4379

**Comment by chenopis** [comment]
Thanks @xiangpengzhao!

**Comment by xiangpengzhao** [comment]
In fact, not only the links mentioned  in this PR but also almost all the links in that type.go file should be fixed. I remember there is already a PR to fix this but I'm not so sure.

**Comment by xiangpengzhao** [comment]
FYI: https://github.com/kubernetes/kubernetes/pull/52731 fixes some of the links in upstream.

**Comment by chenopis** [comment]
Ok, I'm going to close this PR then. Thanks!

**Pull request closed without merging**
