### PR TITLE
Correct links to correct repository

### PR DESCRIPTION
**Pull request by ltupin**
I also update : 

- adding a link that refer the CloudStack website
- prerequesites list on the "Ansible host"
- prerequesites on the CloudStack server
- delete the needs of the cs submodule as now its fully in Ansible CloudStack module

After the issue I mentioned yesterday https://github.com/kubernetes/kubernetes.github.io/issues/3407. Here is my documentation modification request accordingly to the work on the new repo I created.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3430)

### CODE REVIEW

**Comment by ltupin** [comment]
Hello !
As on the k8s website, actually the article regarding CloudStack is not working, do you want some help from my side for the tech-review ? 

Don't hesitate if you have any questions or if you want me to show you that with my suggestion everything is working well.

**Comment by chenopis** [comment]
@ltupin We need someone else to give independent verification that the technical aspects of the change are correct. It's just the process we use to ensure the quality of the doc changes. If you could suggest someone else that knows CloudStack and can do a tech review, that would work. Thx

**Comment by thockin** [comment]
@runseb ?

**Comment by sebgoa** [comment]
Runseb is now @sebgoa

I will check this thursday, i am traveling right now

**Comment by sebgoa** [comment]
Just had a quick look. 

It is awkward because the repo that is referenced is a fork of a skippbox repo.

So either you need to PR the original repo. Or you need yo put this code upstream in cloudstack community or in the exoscale repo (if exoscale specifique).

I do realize that i am the original author, but we need to aim for a long term maintainable plan.

**Comment by ltupin** [comment]
I propose, to ensure a long term maintainable plan, to put this code upstream in CloudStack community (have to define where...) ?

There is nothing really related to Exoscale except the usage of cs (we can plan to modify it to use another tool to interact with CloudStack, ie CloudMonkey ?).

**Comment by sebgoa** [comment]
let's bring in @pdion891 . Hey PL, where can we put some Ansible scripts used to create a k8s cluster in cloudstack. Somewhere upstream for CS community ? I thought of cloudstack-extras but it does not seem active right now.

**Comment by pdion891** [comment]
Hi @sebgoa, I think the simplest answer would be to create a new project under https://github.com/apachecloudstack. seams quiet for now but that is where we should be placing side projects related to Apache Cloudstack.  Thanks ! :-)

**Comment by chenopis** [comment]
@sebgoa @pdion891 Now that the location is https://github.com/apachecloudstack/k8s, is this PR ready to be merged?

**Comment by pdion891** [comment]
Nice, Thanks a lot !

**Pull request merged**
