### PR TITLE
Fix broken documentation link

### PR DESCRIPTION
**Pull request by aee11**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2390)

### CODE REVIEW

**Comment by aee11** [comment]
I signed it!

**Comment by chenopis** [comment]
@aee11 The CLA check is still failing. Did you sign the CLA w/ the same email address that you are using for GitHub?

**Comment by aee11** [comment]
I signed it!

**Comment by aee11** [comment]
I signed it!

**Comment by aee11** [comment]
I signed it!

**Comment by aee11** [comment]
I signed it!

**Pull request merged**
