### PR TITLE
Update security-context.md

### PR DESCRIPTION
**Pull request by islinwb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5075)

### CODE REVIEW

**Comment by cody-clark** [comment]
@chenopis /lgtm

**Comment by islinwb** [comment]
@cody-clark Many thanks for your suggestions! What I did is to correct it but yours is to better it.

**Comment by cody-clark** [comment]
@islinwb Many thanks to you for your careful attention and quick response! :smile:

**Pull request merged**
