### PR TITLE
Refactor tabs implementation

### PR DESCRIPTION
**Pull request by chenopis**
Improve tabs implementation w/ these requirements:

* CSV field you specify to name the tab, assumes no spaces in the name
  * Having a name with spaces results in a broken page
  * Requirement: need to be able to have tab names with spaces in them (e.g. "Weave Net")
* Want to have no default selected, default should say "select one of the tabs"
  * In particular, when no default is selected, it shouldn't be a code block
* Current implementation requires file that needs to be linked to
  * One line doesn't require a file, nor a link to that file

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3268)

### CODE REVIEW

**Comment by ahmetb** [comment]
@chenopis I'm trying to understand why you need to add bunch of webfonts assets and a bootstrap.js that we don’t use to fix this problem.

**Comment by chenopis** [comment]
@ahmetb I haven't actually had a chance to work on this yet. I was in the middle of adding stuff to the bootstrap framework to try out their implementation of tabs. Just ignore this PR for now until the `WIP:` prefix has been dropped.

**Comment by chenopis** [comment]
@errordeveloper @lukemarsden @ahmetb Ok, this is ready for review. You can test out the implementation here: https://deploy-preview-3268--kubernetes-io-master-staging.netlify.com/docs/tabs-example/

**Comment by chenopis** [comment]
Ok, cool. I'm just going to add some documentation to the example and call it a day.

**Comment by chenopis** [comment]
@errordeveloper If you see any issues, I can address them in a follow-up PR. Cheers.

**Pull request merged**
