### PR TITLE
Update imported docs

### PR DESCRIPTION
**Pull request by ymqytw**
Update imported docs and keep the v1.5 new style reference docs, remove old style docs for api-reference and kubectl

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2947)

### CODE REVIEW

**Comment by ymqytw** [comment]
@devin-donnelly Rebased.

**Comment by chenopis** [comment]
@ymqytw Looks like there's a conflict with `docs/admin/kube-scheduler.md` that needs to be resolved before we can merge this. Thx

**Comment by ymqytw** [comment]
@chenopis Rebased. PTAL

**Comment by chenopis** [comment]
@ymqytw Sorry, there are a lot of docs changes going on at the moment. It looks like there is a conflict with docs/user-guide/kubectl/kubectl_completion.md now. :(

**Comment by ymqytw** [comment]
@chenopis It seems that people are keep changing the auto-generated files. We should prevent that and direct them to update the source.

**Comment by ymqytw** [comment]
Rebased.

**Comment by chenopis** [comment]
@ymqytw Ok, I'll keep an eye out for that. Is there an easy way to know which files are auto-generated? Also, there still seems to be a conflict.

**Comment by ymqytw** [comment]
@chenopis I have resolved the conflict.

**Comment by chenopis** [comment]
@ymqytw Great, thanks!

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis @ymqytw kube-scheduler.md should not be removed.

**Comment by ymqytw** [comment]
@zhangxiaoyu-zidif Sorry. It seems that the [this file](https://github.com/kubernetes/kubernetes.github.io/pull/2947/files#diff-e70dc7a8fce6c0c1c59b22232f7d446eR7) has `kube-scheduler.md`. It seems this file should be kept by the script. Not sure how it has been deleted.

Can you send a PR to roll back that file? Thanks.

**Comment by ymqytw** [comment]
I guess maybe something went wrong in multiple time of rebase :/

**Comment by zhangxiaoyu-zidif** [comment]
@ymqytw @chenopis  I add the file at https://github.com/kubernetes/kubernetes.github.io/pull/3340.
I have no right to revert the PR. If you both have some way to roll back it or revert it, you can close #3340.

**Comment by chenopis** [comment]
It's being added back in PR #3320.

**Comment by ymqytw** [comment]
Thanks

**Pull request merged**
