### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by chenhuan12**
fix typo

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5517)

### CODE REVIEW

**Comment by heckj** [comment]
@chenhuan12 thank you for the update! To apply it, we will need you to provide a signature to the CLA

**Comment by steveperry-53** [comment]
@chenhuan12 Please rebase your branch so that it picks up 99fbc2b. That will fix the deploy/netlify failure. Thanks.

**Comment by zhangxiaoyu-zidif** [comment]
@chenhuan12 
please rebase your patch. Thanks

**Comment by chenhuan12** [comment]
cc @zhangxiaoyu-zidif

**Pull request merged**
