### PR TITLE
Fix the kubeadm getting-started-guides link.

### PR DESCRIPTION
**Pull request by warmchang**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3201)

### CODE REVIEW

**Comment by chenopis** [comment]
@warmchang Avoid using relative URLs with "../" paths. Please change the URL to `/docs/getting-started-guides/kubeadm/`. Thanks for finding the broken link!

**Comment by warmchang** [comment]
Hi @chenopis , thank you for your reply.
Actually, the URL of this file is "https://kubernetes.io/docs/admin/kubeadm/"  in "kubernetes.io" site, and the getting-started-guides of kubeadm is "https://kubernetes.io/docs/getting-started-guides/kubeadm/".
If we change to "/docs/getting-started-guides/kubeadm/", then the link should to be "https://kubernetes.io/docs/admin/kubeadm/docs/getting-started-guides/kubeadm/", it's a 404 page.

**Comment by chenopis** [comment]
@warmchang If you use the leading "/" in a URL, that will use the root of the site as the base, so then "/docs/getting-started-guides/kubeadm/" will become "https://kubernetes.io/docs/getting-started-guides/kubeadm/". Trust me. =) Make the change, then try it out in the Netlify preview.

**Comment by warmchang** [comment]
@chenopis , I've changed the url by your opilin. Not that I don't believe, just don't know about it. :smile:

**Comment by chenopis** [comment]
@warmchang Great, thanks! Here's a link to the preview page where you can test it: https://deploy-preview-3201--kubernetes-io-master-staging.netlify.com/docs/admin/kubeadm/#automating-kubeadm

FYI, if you click on the "Show all check" link at the bottom of this PR, then click on the "Details" link for "deploy/netlify", that will take you to a preview build of the site w/ your changes.

**Comment by warmchang** [comment]
@chenopis thank you for the  preview page link!

**Pull request merged**
