### PR TITLE
move -u so that it applies to minikube docker-env

### PR DESCRIPTION
**Pull request by Tony-X**
eval $(minikube docker-env) -u => eval $(minikube docker-env -u)
# This change will unset docker environment vars correctly

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2312)

### CODE REVIEW

**Comment by chenopis** [comment]
@Tony-X Thanks for the contribution. Can you sign the CLA when you get a chance? We need that before we can merge the PR. Thx

**Comment by chenopis** [comment]
This is actually a duplicate of PR #2127, so if the other one goes through first, I'm going to close it.

**Comment by Tony-X** [comment]
Sure. Feel free to close it if since I'm having trouble getting the CLA due to some constraints..

Thanks,
Tony

**Comment by chenopis** [comment]
@Tony-X Ok, no problem. I'll take care of it. Thx

**Pull request closed without merging**
