### PR TITLE
Include filename fix

### PR DESCRIPTION
**Pull request by mkuchin**
mysql-deployment.yaml was included instead of wordpress-deployment.yaml in the last step.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5139)

### CODE REVIEW

**Comment by chenopis** [comment]
@mkuchin Sorry, looks like there's a merge conflict now. Once you fix that, I can merge this PR. Thx

**Comment by chenopis** [comment]
@mkuchin Ping.

**Comment by mkuchin** [comment]
@chenopis I fixed merge conflict.

**Pull request merged**
