### PR TITLE
[1.8] StatefulSet `initialized` annotation is now ignored.

### PR DESCRIPTION
**Pull request by enisoc**
ref https://github.com/kubernetes/kubernetes/issues/41605

This is dependent on https://github.com/kubernetes/kubernetes/pull/49251 merging. (Done)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4426)

### CODE REVIEW

**Comment by enisoc** [comment]
This is now ready for review as https://github.com/kubernetes/kubernetes/pull/49251 has merged.

/assign @foxish @kow3ns 
/unassign @smarterclayton

**Comment by chenopis** [comment]
@enisoc If you can take care of the merge conflicts and change that one URL, I think this will be ready to merge.

**Comment by enisoc** [comment]
Updated URL and rebase.

**Pull request merged**
