### PR TITLE
Update path to build directory

### PR DESCRIPTION
**Pull request by sakshamsharma**
Path changed in release 1.5 of k8s

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1795)

### CODE REVIEW

**Comment by sakshamsharma** [comment]
I have signed the CLA now :smile:

**Comment by devin-donnelly** [comment]
If this change is not relevant until release 1.5, please retarget this PR to the release-1.5 branch.

**Comment by devin-donnelly** [comment]
@sakshamsharma , is this change relevant now? Or not until release 1.5 goes out?

**Comment by sakshamsharma** [comment]
The change takes effect right now (since the link refers to the Github repository, which is bleeding edge, and the link was broken. That way, it is relevant now.
But technically, the updated directory only exists in release 1.5 and above. Which may be misleading for some, since release 1.5 is not in stable right now.
What would be the procedure in such a case?

**Comment by devin-donnelly** [comment]
Let's wait until the 1.5 release, which should happen today anyway.

**Pull request merged**
