### PR TITLE
Update Jetstack logo

### PR DESCRIPTION
**Pull request by mattbates**
This PR updates the Jetstack logo on the [partners page](https://kubernetes.io/partners/).

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4616)

### CODE REVIEW

**Comment by mattbates** [comment]
I've updated the commit (and pushed) to now use my Jetstack email address and we're all signed up to the CNCF CLA.

Can someone prod the bot to check CLA again, please?

**Comment by lichuqiang** [comment]
@mattbates just comment "I signed"

**Comment by mattbates** [comment]
I signed

**Comment by chenopis** [comment]
@mattbates Sometimes the bot requires a nudge. :(

**Pull request merged**
