### PR TITLE
Update link

### PR DESCRIPTION
**Pull request by xialonglee**
Update the link to where the origin link finally pointed to.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3126)

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@xialonglee @chenopis  It is better not do this change. "https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md" is only a temporary file, because it belongs to design-proposals.  And original link works well now, without "404 error".

**Comment by xialonglee** [comment]
I see the page: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/ use the link pointed to the community project too, so for consistency reason, i think it should be updated too.
and though both links works well, but i have to click twice before getting the right content when use the original link, it's reduntant i think.
@zhangxiaoyu-zidif

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif We will have to change the link again anyway once it's no longer under design proposals. Consequently, I think it would be okay to update the link to go directly there. Or do you think there's a better place we can point the link to?

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis Yes, it is convenient for users to read pages if we update the link to go directly there. En, when those temporary files do not exist, let's fix them! Fixing would make community full of energy. :)  I approve it now!

**Pull request merged**
