### PR TITLE
[Federation] Add reference docs for kubefed

### PR DESCRIPTION
**Pull request by irfanurrehman**
Addresses https://github.com/kubernetes/kubernetes.github.io/issues/2888

@kubernetes/sig-federation-misc @madhusudancs 
cc @csbell

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2937)

### CODE REVIEW

**Comment by madhusudancs** [comment]
@irfanurrehman content looks good. A minor nit and a couple of comments about the URL structure. We need @devin-donnelly's suggestions to fix them though. Thank you so very much for creating these docs!

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[_data/guides.yml, line 207 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2937#-Kflyu09WHNW1EhHM5BL:-Kflyu0BIAsN7FcQkUMG:b-uh5pxz) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/f5279723ebc2adea81b2d854ce51f028d2f4f169/_data/guides.yml#L207)):*
> ```YAML
> - title: Administering Federation
>   section:
>   - docs/tutorials/federation/set-up-cluster-federation-kubefed.md
> ```

We want the old URL to be around. We don't want to break links on the Internet.

---

*[_data/reference.yml, line 146 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2937#-KflzOfgCM6yMWj5lAZl:-KflzOfgCM6yMWj5lAZm:b2trzty) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/f5279723ebc2adea81b2d854ce51f028d2f4f169/_data/reference.yml#L146)):*
> ```YAML
>       - docs/user-guide/kubectl/kubectl_stop.md
> 
> - title: Kubeadm - Administrate Federations
> ```

Just call this `kubefed CLI` or `kubefed commands`

---

*[docs/admin/federation/kubefed.md, line 1 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2937#-Kfm0AXgEDWjHYdfrpc6:-Kfm0AXgEDWjHYdfrpc7:bil2zej) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/f5279723ebc2adea81b2d854ce51f028d2f4f169/docs/admin/federation/kubefed.md#L1)):*
> ```Markdown
> ---
> ```

I am not entirely sure if we want the reference documentation at this URL.

@devin-donnelly this is a command reference. What's your URL location recommendation for these reference docs?

---

*[docs/admin/federation/kubefed_options.md, line 2 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2937#-Kfm0dEfajVzakYWQmy2:-Kfm0dEfajVzakYWQmy3:bjztkvg) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/f5279723ebc2adea81b2d854ce51f028d2f4f169/docs/admin/federation/kubefed_options.md#L2)):*
> ```Markdown
> ---
> title: Kubefed options
> ```

I did not know we had `kubefed options`! TIL!

Auto-generated command I guess?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2937#-:-Kfm0zLqt8OG6Q6bdADA:bpybhii)*

**Comment by madhusudancs** [comment]
/assign @madhusudancs

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2937#-:-Kfm1EmPplpWk0bySZ0z:b59i52z)*

**Comment by nikhiljindal** [comment]
@irfanurrehman Did you manually generate these docs in core repo and copy them here?
We have a script for copying autogenerated docs from core repo to here: https://github.com/kubernetes/kubernetes.github.io/blob/master/update-imported-docs.sh

hack/update-generated-docs.sh should generates autogenerated docs in core and then that script copies them to this repo (We should have better documentation for the process, if there isnt already).

**Comment by devin-donnelly** [comment]
@irfanurrehman , @madhusudancs , reference documentation should go under the docs/api-reference directory.

Is this generated documentation that got copy-pasted?

**Comment by irfanurrehman** [comment]
@devin-donnelly apologies for a late response. I think you mistook this for an api reference. Kubefed is an admin command used to deploy federation control plane and manage federations.
kubeadm is the exact parallel of this command, but I could not find the command reference for the same in the docs repo (may be the kubeadm dev team hasnt built the command reference yet).
kebefed is very similar to kubectl too, but kubectl is an user facing (not an admin alone) command/tool. That is why I think docs/user-guide is probably not a right place for kubefed command reference.

Also, yes this is an auto generated reference (with minor manual changes, for example title, owner, etc), and manually copied to this place. As per @nikhiljindal's comment above I did check https://github.com/kubernetes/kubernetes.github.io/blob/master/update-imported-docs.sh, but I think it will need additional logic to copy the kubefed auto generated doc to the appropriate place (similar to the way kubectl command reference is handled). If that is the correct approach, I would rather raise a PR updating that and close this one.
Please educate me.. :-)

---

Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[_data/guides.yml, line 207 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2937#-Kflyu09WHNW1EhHM5BL:-Kg8vhuCapr6XbsHOQyx:bkrqiiv) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/f5279723ebc2adea81b2d854ce51f028d2f4f169/_data/guides.yml#L207)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

We want the old URL to be around. We don't want to break links on the Internet.
</blockquote></details>

I am sort of sure, this change would not break any links. The old url would open up  a redirection page (is currently active at https://kubernetes.io/docs/admin/federation/kubefed/), with the link to the set-up-cluster-federation-kubefed. 
Without this change, the link at the line above and the tools page kubefed link  (https://kubernetes.io/docs/tools/) both pointed to the redirection page.
With this change the tools page (https://kubernetes.io/docs/tools/) kubefed link will reach the command help (just like kubectl) (which I think its supposed to show, rather then the redirection link which reaches set-up-cluster-federation-kubefed) and the "Administering federation" link will directly go to the correct page rather then via a redirection.

---

*[_data/reference.yml, line 146 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2937#-KflzOfgCM6yMWj5lAZl:-Kg8y5JJ9pUF-4zc5yU2:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/f5279723ebc2adea81b2d854ce51f028d2f4f169/_data/reference.yml#L146)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

Just call this `kubefed CLI` or `kubefed commands`
</blockquote></details>

Done.

---

*[docs/admin/federation/kubefed_options.md, line 2 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2937#-Kfm0dEfajVzakYWQmy2:-Kg8zkUPUHCGtxYMe0Ra:b2nign6) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/f5279723ebc2adea81b2d854ce51f028d2f4f169/docs/admin/federation/kubefed_options.md#L2)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

I did not know we had `kubefed options`! TIL!

Auto-generated command I guess?
</blockquote></details>

yes

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2937#-:-Kg94GGN0BLPgB8E4kI1:byl28bf)*

**Comment by irfanurrehman** [comment]
@devin-donnelly any suggestions ??
thanks!

**Comment by chenopis** [comment]
@madhusudancs @nikhiljindal Sorry I'm only looking at this now. Did you guys give this a Tech LGTM?

**Comment by irfanurrehman** [comment]
@chenopis, I raised some questions in the last comment. I need some suggestions on those queries to take it forward!

**Comment by chenopis** [comment]
@irfanurrehman Ok, no problem. Just ping me when it's ready to be merged.

**Comment by nikhiljindal** [comment]
I think updating https://github.com/kubernetes/kubernetes.github.io/blob/master/update-imported-docs.sh to move kubefed docs as well (as it does for federation api reference docs) is the right thing to do. That way, every new branch will get updated docs.
Update the script and then run it to generate these docs.

You will still need manual changes to the navigation menu from this PR.

**Comment by chenopis** [comment]
I agree with @nikhiljindal since we import these into kubernetes/kubernetes.github.io. @irfanurrehman can you make the changes he suggested?

**Comment by irfanurrehman** [comment]
> I agree with @nikhiljindal since we import these into kubernetes/kubernetes.github.io. @irfanurrehman can you make the changes he suggested?

@chenopis updated this. Am not sure if I need to add the generated md files here for the first time?
@madhusudancs @nikhiljindal, can u please verify that the placeholders for the files are ok?
I have updated https://github.com/kubernetes/kubernetes/pull/43443 also accordingly.

**Comment by chenopis** [comment]
@irfanurrehman I don't see that the kubefed docs are being pulled in. Can you verify that before I merge this?

**Comment by irfanurrehman** [comment]
> @irfanurrehman I don't see that the kubefed docs are being pulled in. Can you verify that before I merge this?

@chenopis thanks for the updates! The docs generation PR is still open, I have requested merge for it. I will update you as soon as that happens.

**Comment by chenopis** [comment]
@irfanurrehman Ok, great. Thx!

**Comment by irfanurrehman** [comment]
@chenopis, Thanks for helping me on this and fixing the issues, as well.
I have rebased this on latest as the changes were out of syn with master. Please let me know if anything further is needed.

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 2db7e161a1b8060d5848219463c64b14f8092481

https://deploy-preview-2937--kubernetes-io-master-staging.netlify.com

**Comment by chenopis** [comment]
@irfanurrehman I think I need to kickoff the autogeneration for the kubefed docs and then push them into the kubernetes.github.io repo. Let me ask @pwittrock

**Comment by irfanurrehman** [comment]
thanks @chenopis, that is what I actually asked [here](https://github.com/kubernetes/kubernetes.github.io/pull/2937#issuecomment-305260782) earlier.
I know how to autogenerate those docs and which doc fits which title (Infact, I did add them here as part of original PR). If its ok, I can autogenerate and add those docs also to this PR.
Also, I did not completely get what is the new commit (2db7e16) which you did add for the netlify preview. Isn't rebasing this on latest master sufficient?

**Comment by chenopis** [comment]
@irfanurrehman Sorry, I was mistaken about how the process is supposed to work. :( Yes, you will need to include those docs in this PR. Sorry again for the confusion.

The "Deploy preview ready!" comment is actually a bot I'm testing out that displays the preview build link in a comment after a commit instead of burying it in the checks sections. It seems that most people don't know that the preview exists, so I'm trying to make it more obvious.

**Comment by irfanurrehman** [comment]
@chenopis no problems, and thanks again for helping me on this PR. I have updated the auto-generated docs also.

**Comment by irfanurrehman** [comment]
@chenopis ```verify-docs-format.sh``` seems to be failing with ```<file> doesn't have a proper title defined``` for the newly added files. The auto-generation tools dont add titles.
However the same is true for other similar reference files for example ```kube-apiserver``` or ```federation-apiserver```. Some script in the process of copying these files into their target path seems to be adding title lines (or its manually done when those files are copied). For example
``` 
---
title: federation-apiserver
notitle: true
---
```
for ```federation-apiserver```.

```update-imported-docs.sh``` seems to add the lines ```---```, but not sure which script is adding the title lines.
If you can verify and confirm how is this getting done, I can update a commit for that too. On the other hand we can skip this check for these files too, as they anyways are auto-generated. Let me know which might be the more suitable option.
Thanks again for all your help.

**Comment by irfanurrehman** [comment]
On second thoughts did add those files to ```skip_title_check.txt```

**Comment by irfanurrehman** [comment]
@chenopis rebased this again (conflict). Please let me know if anything else is needed!

**Pull request merged**
