### PR TITLE
Remove redundant, out of sync table of contents

### PR DESCRIPTION
**Pull request by olalonde**
This table of contents is redundant (it's also available from the side nav) and confusing (not clear if it's a copy of the side nav or contains additional information). Plus, it was out of sync with the actual table of contents (last section on GPU was missing). So, I think it's best to just remove it.

> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3433)

### CODE REVIEW

**Comment by chenopis** [comment]
@olalonde IMHO, it would be best if it were updated, not just removed. Otherwise, there's not much content on the Tasks landing page, which might be confusing.

**Comment by chenopis** [comment]
@steveperry-53 Do you want to chime in?

**Comment by olalonde** [comment]
I can't talk for everyone but I personally feel keeping the page empty (or with a clear "Next step" link) is a better UX. Here's what I did:

1) Scanned page and realized it looked just like the nav to the left...
2) Skipped reading it and navigate to next page in nav.
3) Few minutes later... Read about a term and can't tell whether it was explained previously. Start getting paranoid about having skipped important information.
4) Remember I skipped intro page.
5) Go back to read intro page.
6) Realize it's like the side nav but slightly different.
7) Click every links one by one to be sure.

Ok.. it wasn't that dramatic but you get the idea 👍

**Comment by techtonik** [comment]
Empty page is ok, but speaking of UX side:
1. I would place the menu on the right side
2. Place "----> Use the menu on the right to get more details"
3. "Next" item is a good idea

**Comment by techtonik** [comment]
Ouch. Missed the critical part - the empty page doesn't explain what "Kubernetes Tasks" really are.

**Comment by techtonik** [comment]
It looks like the "Tasks" section of documentation is a "Cookbook" with recipes. Not really something embedded in Kubernetes.

**Comment by chenopis** [comment]
I'll work on rewriting the copy for the explanation of what Tasks are and maybe a high-level description of each grouping in the ToC.

**Comment by steveperry-53** [comment]
@chenopis, I'm fine with whatever solution you and @techtonik work out.

**Comment by chenopis** [comment]
@olalonde @techtonik I merged this PR and added some copy in https://github.com/kubernetes/kubernetes.github.io/pull/3593. Let me know if that works for you.

**Comment by olalonde** [comment]
@chenopis yes, that's better I think.

**Pull request merged**
