### PR TITLE
Updated spec.schedulername to spec.schedulerName.

### PR DESCRIPTION
**Pull request by k82cn**
xref https://github.com/kubernetes/kubernetes/pull/41859

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2588)

### CODE REVIEW

**Comment by chenopis** [comment]
@k82cn Is this related to a particular release?

**Comment by k82cn** [comment]
@chenopis , target is 1.6 ; but please wait for kubernetes/kubernetes#41770 merged, I'll ping you when it's ready :).

**Comment by chenopis** [comment]
@k82cn No problem. I just wanted to make sure I tag this correctly. Also, would you mind rebasing and switching the base to release-1.6? Thx

**Comment by k82cn** [comment]
@chenopis , sure, I'll rebase it to 1.6 branch :).

**Comment by chenopis** [comment]
@k82cn thx!

**Comment by chenopis** [comment]
@k82cn BTW, I moved this to the `release-1.6` branch for you. =)

**Comment by k82cn** [comment]
@chenopis , thanks very much :).

**Comment by k82cn** [comment]
@chenopis , can you help to merge this PR?  kubernetes/kubernetes#41770  was merged last night :).

**Comment by chenopis** [comment]
@k82cn Done! Thanks =)

**Pull request merged**
