### PR TITLE
Added a Recycler Pod Template Example

### PR DESCRIPTION
**Pull request by pospispa**
Recycle pod template example is missing in the documentation.

That's why it is now added.

Related Trello card: https://trello.com/c/WhCK1Ndv/86-5-add-checks-and-documentation-about-template-pods-for-recycling
Related source code pull request: https://github.com/kubernetes/kubernetes/pull/36221

cc: @jsafrane

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1636)

### CODE REVIEW

**Comment by saad-ali** [comment]
Documentation is good. However, I'm not sure if we want to add more documentation, in this case, for the recycle retention policy, considering we want to deprecate it.

CC @kubernetes/sig-storage

**Comment by pospispa** [comment]
I know that the recycle retention policy should be deprecated, however, I don't know when it should be deprecated. Is there a plan when it will be deprecated and when it will be removed from source code?

**Comment by saad-ali** [comment]
> Is there a plan when it will be deprecated and when it will be removed from source code?

@childsb @wattsteve?

**Comment by jsafrane** [comment]
I think it makes sense to document existing behavior with some note that dynamic provisioning is much better option and recyler should be used only when it's absolutely necessary.

**Comment by childsb** [comment]
I've re-opened a PR to add a deprecation statement for recycler.

Saad - can we merge this for 1.5? It's non functional and will start the count-down clock for recycler.

https://github.com/kubernetes/kubernetes/pull/36758

**Comment by devin-donnelly** [comment]
Fine from a Docs perspective. Can somebody give it a tech LGTM?

@jsafrane?

**Comment by saad-ali** [comment]
> I've re-opened a PR to add a deprecation statement for recycler.
> 
> Saad - can we merge this for 1.5? It's non functional and will start the count-down clock for recycler.
> 
> kubernetes/kubernetes#36760

Ack. @childsb could you do the tech review for this PR.

**Comment by jsafrane** [comment]
tech lgtm

**Comment by jsafrane** [comment]
@pospispa, please rebase

**Pull request merged**
