### PR TITLE
Stackdriver docs refactoring

### PR DESCRIPTION
**Pull request by Crassirostris**
Moved from https://github.com/kubernetes/kubernetes.github.io/pull/2096

Removed part of the manual on the Stackdriver Logging page, because it's outdated and we don't want to continuously renew it. Replaced with the links to the Stackdriver pages and one minimal example with CLI.

Enumerated system components, whose logs will be ingested from the node.

@piosz @devin-donnelly @steveperry-53 @sharbison3 Please take a look

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2142)

### CODE REVIEW

**Comment by Crassirostris** [comment]
@sharbison3 Thanks a lot for you comments from the previous version! I applied them all, PTAL

**Comment by Crassirostris** [comment]
@fejta Bot assigned me to my PR, is it OK?

**Comment by steveperry-53** [comment]
@Crassirostris, Could you make sure the **Allow edits by maintainers** box is checked. Thanks.

**Comment by Crassirostris** [comment]
@steveperry-53 Done, thanks!

**Comment by Crassirostris** [comment]
Whoops, accidentally closed

**Comment by steveperry-53** [comment]
@Crassirostris, See my two commits for suggested edits.

**Comment by Crassirostris** [comment]
@steveperry-53 Thanks a lot! I agree with almost all changes, except one in the `stackdriver.md`, where you corrected `Stackdriver Logging agents attaches` to `Stackdriver Logging agents attach` but this was my mistake in the first place and it should've been `Stackdriver Logging agent attaches`.

Meanwhile I had some input and will add some more information soon. I will mention you when it's ready.

Thanks again!

**Comment by Crassirostris** [comment]
> Meanwhile I had some input and will add some more information soon. I will mention you when it's ready.

Oh, sorry, this was addressed to other PR.

@steveperry-53 If you agree with the changes, could you please LGTM?

**Pull request merged**
