### PR TITLE
Update accessing-the-api.md

### PR DESCRIPTION
**Pull request by ronaldpetty**
Fixed two typos, happy new year!

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2069)

### CODE REVIEW

**Comment by ronaldpetty** [comment]
I signed it!

**Comment by ronaldpetty** [comment]
I sent a ticket in to check if my email is an issue, just a hunch, as I have successfully sent PR request in past.  I am using the GUI to update the docs versus a local cloned repo, so maybe using my active email (ronald.petty@gmail.com) versus CNCF email (ronald.petty@minimumdistance.com) might be the issue.

**Comment by jrnt30** [comment]
@ronaldpetty I had the same issue and had to setup an alternate email in my Github profile to match the one from CNCF explicitly.

**Comment by ronaldpetty** [comment]
Thanks Justin,

I will redo with the email!

Ron

**Comment by ronaldpetty** [comment]
I resubmitted as #2078 with the corrected CNCF email.

**Pull request closed without merging**
