### PR TITLE
Copying auto generated docs for federation binaries from kubernetes repo

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref https://github.com/kubernetes/kubernetes.github.io/issues/977

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @jaredbhatti @pwittrock

**Comment by pwittrock** [comment]
@nikhiljindal This should be in the kubernetes.github.io repo.

**Comment by pwittrock** [comment]
Resolved offline

**Comment by pwittrock** [comment]
@jaredbhatti @devin-donnelly

This doesn't appear to be showing up on the k8s.io page.  It looks like it may be related to the file _data/overrides.yml?  Any idea what is going on?

**Comment by nikhiljindal** [comment]
@jaredbhatti @devin-donnelly Any idea on what I need to do?

**Pull request merged**
