### PR TITLE
init containers in k8sv1.7

### PR DESCRIPTION
**Pull request by jianglingxia**
I think maybe copy in k8s1.6 to k8s1.7,so fix it !

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5646)

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
No, in v1.6, initContainer is beta. So it is not a typo. remainint it is OK.

**Comment by jianglingxia** [comment]
i know，in 1.6 is beta ，so in 1.7 is not beta？

**Comment by xiangpengzhao** [comment]
Init containers have graduated to GA in 1.6, i.e. exited beta, so we should leave the doc as-is.

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.6.md#node-components-1

`[stable] Init containers have graduated to GA and now appear as a field.`

**Comment by chenopis** [comment]
Ok, I'm closing this PR then.

**Pull request closed without merging**
