### PR TITLE
Update link to design principles

### PR DESCRIPTION
**Pull request by gilesvangruisen**
The document had moved from the kubernetes/kubernetes repo to kubernetes/community but this link had yet to be updated.

Thanks!

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2756)

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks much, @gilesvangruisen. Please sign the CLA so that this can be merged.

**Comment by bgrant0607** [comment]
@gilesvangruisen: Ping on CLA.

**Comment by bgrant0607** [comment]
Also, the doc has moved to:
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/concepts/overview/what-is-kubernetes.md

**Comment by chenopis** [comment]
@gilesvangruisen Please sign the CLA when you get a chance. Also, `/docs/whatisk8s.md` has moved to `/docs/concepts/overview/what-is-kubernetes.md`, so please apply your changes there. Thx

**Comment by chenopis** [comment]
@gilesvangruisen Thanks for the contribution. I'm going to apply these changes to `docs/concepts/overview/what-is-kubernetes.md`. Cheers

**Pull request closed without merging**
