### PR TITLE
docs/rkt: Update known issues for rktnetes for 1.4 release.

### PR DESCRIPTION
**Pull request by yifan-gu**
Suppress #1109 

File the PR against master wrt to the discussion on the old PR.

cc @janetkuo @euank @tmrts

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1171)

### CODE REVIEW

**Comment by janetkuo** [comment]
@kubernetes/docs

**Comment by janetkuo** [comment]
@yifan-gu you need a rebase

**Comment by devin-donnelly** [comment]
Docs LGTM; however, if this is for the 1.4 release, would you mind targeting it to the release-1.4 branch?

**Comment by yifan-gu** [comment]
@devin-donnelly  I made the PR against master based on https://github.com/kubernetes/kubernetes.github.io/pull/1109#issuecomment-244522759
> If this doc is about things in 1.4 only, you should push to 1.4 branch,
otherwise this will go live once merged.

**Comment by devin-donnelly** [comment]
I'm confused. This PR's title says it is updating known issues for rktnetes for the 1.4 release. That means this shouldn't be released until 1.4, correct?

If we merge this to Master it will go live too early.

**Comment by yifan-gu** [comment]
@devin-donnelly I agree, sorry for the confusion, I reopend https://github.com/kubernetes/kubernetes.github.io/pull/1109 which contains the same commits but it's against release-1.4 branch. PTAL, thank you!

**Comment by devin-donnelly** [comment]
Thanks. Closing this one and merging #1109 instead.

**Pull request closed without merging**
