### PR TITLE
Write new task: Determining the Reason for Pod Failure.

### PR DESCRIPTION
**Pull request by steveperry-53**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1720)

### CODE REVIEW

**Comment by pwittrock** [comment]
Looks good.  I might add something about a concrete use case, such as:

> This can be helpful for writing FATAL logs or termination messages for your pod to a location where they can easily be retrieved and surfaced by tools such as dashboards or monitoring software.

**Comment by steveperry-53** [comment]
@pwittrock I added this text:

Termination messages provide a way for containers to write information about fatal events to a location where it can be easily retrieved and surfaced by tools like dashboards and monitoring software. Termination messages are an alternative to the general [Kubernetes logs](/docs/user-guide/logging/).

**Comment by pwittrock** [comment]
Sounds good.  Super minor nit:

> Termination messages are an alternative to the general 

We should be clear that these actually should be used together, not one or the other.  In most cases it probably makes sense for the termination message to also appear in the logs.

**Comment by steveperry-53** [comment]
How about this?

Termination messages provide a way for containers to write
information about fatal events to a location where it can
be easily retrieved and surfaced by tools like dashboards
and monitoring software. In most cases, information that you
put in a termination message should also be written to
the general
[Kubernetes logs](/docs/user-guide/logging/).

On Fri, Nov 18, 2016 at 10:06 AM, Phillip Wittrock <notifications@github.com

**Comment by pwittrock** [comment]
lgtm

**Comment by pwittrock** [comment]
Thanks Steve.  I am loving this.

**Comment by steveperry-53** [comment]
Because we use Go templates (I think) in this example:

kubectl get pod termination-demo -o go-template="{{range
.status.containerStatuses}}{{.lastState.terminated.message}}{{end}}"

On Fri, Nov 18, 2016 at 10:24 AM, Phillip Wittrock <notifications@github.com

**Comment by pwittrock** [comment]
Oh i see

**Pull request merged**
