### PR TITLE
Update volume specification for vSphere in volumes.md

### PR DESCRIPTION
**Pull request by abrarshivani**
Fixes ```error validating data: found invalid field vsphereVirtualDisk for v1.Volume; if you choose to ignore these errors, turn validation off with --validate=false```

### CODE REVIEW

**Comment by pwittrock** [comment]
@abrarshivani Sorry I accidentally merged this before you signed the CLA, and had to revert it.  Would you file another PR and then sign the CLA.  Thanks for this fix.

**Comment by abrarshivani** [comment]
@pwittrock No problem I will create another PR for the same. It seems that this merge is not reverted since the change appears in master branch.

**Comment by pwittrock** [comment]
@abrarshivani Hm.  Well that is annoying.  Can you make sure you sign the cla while I figure out how to get all the i's dotted and t's crossed?

**Comment by pwittrock** [comment]
Alright, reverted here: #1041.  Really looking forward to this change @abrarshivani.  At-Mention me on the new PR.  e.g. `@pwittrock This is the new PR` and sign the CLA.

**Comment by abrarshivani** [comment]
@pwittrock I have already signed CLA before submitting this PR (I contributed to kubernetes repo before). I don't know why bot is not able to detect the same. Anyways, I have created another PR #1042

**Pull request merged**
