### PR TITLE
Update kubectl cli from 1.6 to 1.7

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
Update kubectl cli from 1.6 to 1.7

> NOTE: Please check the “Allow edits from maintainers” box (see image below) to  
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4253)

### CODE REVIEW

**Comment by chenopis** [comment]
I'm going to merge this for now, but we need to fix this upstream where this doc is autogenerated. @ahmetb Should we just change this to use the `{{page.version}}` variable?

**Comment by ahmetb** [comment]
@chenopis this should've been fixed with the `update-imported-docs.sh`. Did we run it for 1.7 release?

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis  Hi, Andrew 
After I check current version of kubernetes.github.io, I find about 30 files using kubectl v1.6. Should I update them all to v1.7?

**Comment by ahmetb** [comment]
@zhangxiaoyu-zidif if the file is saying "Auto generated" (just like the file you patched here did), please do not send update them.

**Comment by chenopis** [comment]
@ahmetb I don't think we did run `update-imported-docs.sh` for 1.7. Can you do that?

**Comment by ahmetb** [comment]
@chenopis will do. Do you mind drafting a quick doc on "how to make a docs release" with your experience so that we can add a checklist with this item.

**Comment by chenopis** [comment]
@ahmetb Yup! Been working on that. Just invited you to the doc.

**Pull request merged**
