### PR TITLE
Update kubectl curl to get latest version

### PR DESCRIPTION
**Pull request by rstarmer**
As some commands aliases have been updated in the latest release of kubectl, it
would be good to have a more current version defined as the default download. 
The page macro based version is quite old (1.3.0 vs. the now current 1.5.1)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1953)

### CODE REVIEW

**Comment by rstarmer** [comment]
I signed it!

**Comment by Starefossen** [comment]
It would be much better if the `{{page.version}}` variable was kept up to date according to the latest stable release version of Kubernetes.

**Comment by rstarmer** [comment]
True, but that creates a requirement on a manual update for at least every major version change. Is there a programmatic way to update the page version?

In addition, I don't see where the variable comes from, so it's not clear how it would be changed anyway.

**Comment by janetkuo** [comment]
The change LGTM. Maybe @kubernetes/sig-docs can help answer the question about `{{page.version}}`.

**Comment by rstarmer** [comment]
Thanks, I've dropped a note in the sig-docs channel, will see if anyone can
send me in the right direction.

Robert

**Comment by Starefossen** [comment]
This is defined as a default page variable in [_config.yaml](https://github.com/kubernetes/kubernetes.github.io/blob/master/_config.yml) (more about default Jekyll variables [here](https://jekyllrb.com/docs/configuration/#front-matter-defaults)). What we should do is update this to the latest stable version on a regular basis.

If it is not possible update the global default variable at this moment, we can locally override `{{ page.version }}` in the `minikube.md` file by adding it to the page metadata section like this:

```yaml
---
version: v1.5
assignees:
...
```

**Comment by janetkuo** [comment]
> {{ page.version }} is defined as a default page variable in _config.yaml

@Starefossen Thanks, I believe this needs to be updated. Filed #1970 for it

**Comment by janetkuo** [comment]
#1970 is merged

**Comment by Starefossen** [comment]
Great work @janetkuo 😄

**Comment by devin-donnelly** [comment]
@rstarmer , can you fix the merge conflicts? Then I can merge.

**Comment by Starefossen** [comment]
@devin-donnelly I would argue that this PR can be closed now that #1970 has been merged.

**Comment by devin-donnelly** [comment]
Thanks for the update.

**Pull request closed without merging**
