### PR TITLE
Update Task topics on resource management.

### PR DESCRIPTION
**Pull request by steveperry-53**
@vishh, When you get a chance, can you review these Task topics?

The purpose of this PR is to:
* Update and reorganize Task topics related to management of compute and API resources.
* Create Tasks that readers can actually do as they read through the topics.

In a followup PR, I would like to update the related Concept topics, especially for QoS and Node Allocatable.

Under Tasks > Configure Pods and Containers
    * [Assign Memory Resources to Containers and Pods](https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com/docs/tasks/configure-pod-container/assign-memory-resource/)
    * [Assign CPU Resources to Containers and Pods](https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com/docs/tasks/configure-pod-container/assign-cpu-resource/)
    * [Configure Quality of Service for Pods](https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com/docs/tasks/configure-pod-container/quality-service-pod/)

Under Tasks > Administer a Cluster > Manage Memory, CPU, and API Resources
    * [Configure Default Memory Requests and Limits for a Namespace](https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/memory-default-namespace/)
    * [Configure Default CPU Requests and Limits for a Namespace](https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/cpu-default-namespace/)
    * [Configure Minimum and Maximum Memory Constraints for a Namespace](https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/memory-constraint-namespace/)
    * [Configure Minimum and Maximum CPU Constraints for a Namespace](https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/cpu-constraint-namespace/)
    * [Configure Memory and CPU Quotas for a Namespace](https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/quota-memory-cpu-namespace/)
    * [Configure a Pod Quota for a Namespace](https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/quota-pod-namespace/)
    * [Configure Quotas for API Objects](https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/quota-api-object/)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4158)

### CODE REVIEW

**Comment by steveperry-53** [comment]
On https://deploy-preview-4235--kubernetes-io-vnext-staging.netlify.com/case-studies/,
Read about GolfNow goes to Pearson.
Also, there are rendering problems on case-studies/ and on case-studies/box.
I'll be out of the office now until around 4:30.
Others who could merge this PR after the few remaining things are fixed: @chenopis, @ryanmcginnis.

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 3d14ff23c00690b38f8d2f6f9dbc4d4987a26a80

https://deploy-preview-4158--k8sio-netlify-move.netlify.com

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 3d14ff23c00690b38f8d2f6f9dbc4d4987a26a80

https://deploy-preview-4158--kubernetes-io-master-staging.netlify.com

**Comment by chenopis** [comment]
@steveperry-53 BTW, I'm trying a Netlify feature where they automatically add a comment w/ the preview link. It's a little creepy that it shows up as me though. LOL

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 486b1cb04771e01cbdac9065fd11b5414aa2a7fb

https://deploy-preview-4158--k8sio-v1-6.netlify.com

**Comment by steveperry-53** [comment]
Andrew,
What's the advantage of having a comment generated? I can think of a couple
of disadvantages, like bloating the comment list in a PR and adding more
email to people's inboxes.

**Comment by chenopis** [comment]
@steveperry-53 I've found that most people are unaware that the preview exists because it is buried in the Checks section. Therefore, I'm trying to surface it more so that people will use it. However, I'm still working w/ Netlify right now to get the settings correct so that it doesn't spam the comment history.

**Comment by steveperry-53** [comment]
@vish, Can you give us an estimate of when you'll be able to review this? Thanks.

**Comment by vishh** [comment]
Woot. This is awesome. Thanks @steveperry-53!

/lgtm

**Pull request merged**
