### PR TITLE
Kubernetes 1.8 reference docs

### PR DESCRIPTION
**Pull request by pwittrock**
Release 1.8 API reference docs

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5632)

### CODE REVIEW

**Comment by steveperry-53** [comment]
Thanks @pwittrock. Do you want a tech review? Or should I go ahead and merge?

**Comment by pwittrock** [comment]
@steveperry-53 Would you mind manually browsing around and making sure everything looks good.  I a quick once-over and the links and formatting, but would be good to have a second look.

@mengqiy Would you mind looking over the 1.8 ref docs for kubectl and the apis on netlify and make sure there is nothing glaring?

**Comment by steveperry-53** [comment]
@pwittrock Did these docs get included?
https://github.com/kubernetes/kubernetes/pull/47934

**Comment by steveperry-53** [comment]
@pwittrock I'd like to see this included, if not now, soon after the 1.8 release.
https://github.com/kubernetes/kubernetes/pull/50532

**Comment by steveperry-53** [comment]
@pwittrock lgtm with one concern: I want to be sure the [cloud controller manager](https://github.com/kubernetes/kubernetes/pull/47934) docs are included.

**Comment by pwittrock** [comment]
@steveperry-53 Sounds like a good opportunity for @chenopis to get familiar with running the docs updates scripts

**Comment by pwittrock** [comment]
@steveperry-53 The cloud controller manager docs are unrelated to this.

**Comment by chenopis** [comment]
@steveperry-53 LGTM too, so let's merge this PR and handle the cloud controller manager in a separate one.

**Comment by steveperry-53** [comment]
@pwittrock Are you ready for us to merge this? Or do you want to wait for a review from @mengqiy?

**Comment by mengqiy** [comment]
@steveperry-53 Let me TAL really quick.

**Comment by mengqiy** [comment]
LGTM

@steveperry-53 kubernetes/kubernetes#50532 is included in this PR.
kubernetes/kubernetes#47934 is not, since it is managed by another script. I will send a PR to update that part shortly.

**Comment by steveperry-53** [comment]
@pwittrock @mengqiy Are the v1beta1 and v1beta2 sections in the correct place?

I see this at the top:
http://kubernetes-io-vnext-staging.netlify.com/docs/api-reference/v1.8/#deployment-v1beta1-apps

And I see this lower down under OLD API VERSIONS
http://kubernetes-io-vnext-staging.netlify.com/docs/api-reference/v1.8/#deployment-v1beta2-apps

**Comment by mengqiy** [comment]
They should be move up.

**Pull request merged**
