### PR TITLE
Update kubectl-cheatsheet.md

### PR DESCRIPTION
**Pull request by alexanderilyin**
Missing dependencies.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2137)

### CODE REVIEW

**Comment by jaredbhatti** [comment]
Can you sign the CLA, please? :)

**Comment by alexanderilyin** [comment]
@jaredbhatti I signed it!

**Comment by chenopis** [comment]
@alexanderilyin thanks!

**Pull request merged**
