### PR TITLE
Init container exists beta in 1.6.

### LINKED ISSUE #3649: Update doc for init continer
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
[CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#pod)

>Init containers have graduated to GA and now appear as a field. The beta annotation value will still be respected and overrides the field value. (#38382, @hodovska)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

### PR DESCRIPTION
**Pull request by gyliu513**
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

Fixed #3649

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3665)

### CODE REVIEW

**Comment by chenopis** [comment]
@gyliu513 Sorry, I made a change to the text in init-containers.md so you'll need to resolve that conflict.

**Comment by gyliu513** [comment]
@chenopis updated, thanks.

**Comment by gyliu513** [comment]
@smarterclayton @chenopis  can you please help commit this as well?

**Pull request merged**
