### PR TITLE
Moving etcd topic to Concepts.

### PR DESCRIPTION
**Pull request by iphutch**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2898)

### CODE REVIEW

**Comment by chenopis** [comment]
@iphutch I added the Storage section to the Concepts ToC in a previous PR, which is why there's a conflict. :( Looks good otherwise, so if you just merge `master` into your branch and resolve the conflict, I can merge this. Thanks again for helping out!

**Comment by steveperry-53** [comment]
@iphutch, Because there's a parallel effort in the 1.6 branch, let's hold off on this until after the 1.6 launch.

**Comment by chenopis** [comment]
FYI, 1.6 is live now.

**Comment by steveperry-53** [comment]
@iphutch, As part of this PR, let's also move the new file docs/admin/etcd_upgrade. I think this new file could be moved to docs/concepts/storage.

Also, could you take a look at these two file and see whether you think they should be separate or combined:

* docs/admin/etcd
* docs/admin/etcd_upgrade

**Comment by chenopis** [comment]
bump

**Pull request merged**
