### PR TITLE
Updated prereqs.md for windows

### PR DESCRIPTION
**Pull request by faizan82**
Added explicit steps for windows for setting up kubectl

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2370)

### CODE REVIEW

**Comment by bgrant0607** [comment]
@michmike Could you PTAL?

**Comment by michmike** [comment]
@jbhurat will do that.

**Comment by chenopis** [comment]
@faizan82 you might want to put some explicit line breaks in. It's showing up wrapped into a couple of lines for me:
screen shot 2017-01-27 at 11 01 21 am

**Comment by faizan82** [comment]
I verified it via preview tab but let me check again

**Comment by chenopis** [comment]
@faizan82 I think there was an issue w/ the Netlify preview that I was looking at. Should be fine. As soon as @michmike gives his LGTM, I will merge. Thx

**Comment by michmike** [comment]
I would like to see a few changes before this can go through.
1. We should put quotes around paths in windows to ensure they are properly interpreted
2. mv is not a command in windows, so that would not work
3. we should describe to users how to change the environment variables in windows (optiona)

**Comment by faizan82** [comment]
I totally agree with Michael's point but please clarify on points below:

1. curl is not available for windows and hence I assumed that there is some
shell or utilities available for windows where the installation is being
run from
2. Shall we detail installation of shell utilities for windows as well or
shall we assume that some default is available to us?

**Comment by chenopis** [comment]
@michmike ?

**Comment by michmike** [comment]
fyi, you can use curl on windows. i use it all the time :)
I don't see any changed files here. am i missing something?

**Comment by michmike** [comment]
On the question below, you don't have to detail installation instructions for utilities. just mention what you plan to use
--
2. Shall we detail installation of shell utilities for windows as well or
shall we assume that some default is available to us?

**Comment by chenopis** [comment]
@faizan82 ?

**Comment by chenopis** [comment]
@faizan82 Ping. Just wanted to check-in to see what's going on w/ this PR. If there hasn't been any movement on it by the end of next week, I will close it to help keep the PR queue fresh.

**Comment by chenopis** [comment]
@faizan82 I'm closing this for now, but feel free to reopen it if need be. Cheers

**Pull request closed without merging**
