### PR TITLE
Updated architecture graphic in MEANstack tutorial

### PR DESCRIPTION
**Pull request by paulzim**
I created a new architecture graphic fo the MEANstack tutorial using Google assets and saving as an SVG file. This is for issue #84

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Thanks! :) Please sign the CLA, as googlebot COMMANDS you to do. Also, if possible, I'm seeing weird white boxes where there should be transparency and it would be preferable if it were tightly cropped with no/minimal margins around the images.

**Comment by paulzim** [comment]
OK, will fix!

PZ

**Comment by paulzim** [comment]
I signed it!

[http://www.cisco.com/web/europe/images/email/signature/logo05.jpg]

Paul Zimmerman
MANAGER.DEVNET OPERATIONS
pzimmerm@cisco.com
Phone: +1 408 525 8950

Cisco Systems Limited
560 McCarthy Blvd.
MILPITAS
CALIFORNIA
95035
US
Cisco.com<http://www.cisco.com/>





[Think before you print.]Think before you print.

This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.
For corporate legal information go to:
http://www.cisco.com/web/about/doing_business/legal/cri/index.html

**Comment by paulzim** [comment]
I fixed the white around the text and cropped it as close as I could

**Comment by johndmulhausen** [comment]
Thank you sir! Looks great.

**Pull request merged**
