### PR TITLE
[WIP] Administrators and User Can Specify in Which Zone(s) a PersistentVolume Shall Be Created

### PR DESCRIPTION
**Pull request by pospispa**
Administrators can specify in which zone(s) users may create PersistentVolumes using dynamic provisioning.
A user can specify a group of zone(s) in which a dynamically provisioned PersistentVolume shall be created.

Related source code pull request: https://github.com/kubernetes/kubernetes/pull/37497

Related Trello cards:
- [GCE provisioner, parse pvc.Selector](https://trello.com/c/CyemTzsK/259-finish-gce-provisioner-parse-pvc-selector-dynamic-provision)
- [AWS provisioner, parse pvc.Selector](https://trello.com/c/2XjouSWw/260-finish-aws-provisioner-parse-pvc-selector-dynamic-provision)

cc: @jsafrane

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1794)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
Fine by me, but needs a second set of eyes for technical correctness.

**Comment by pospispa** [comment]
The implementation was reworked because of [code review comments](https://github.com/kubernetes/kubernetes/pull/37497) that's why the documentation will have to be reworked too.

**Comment by devin-donnelly** [comment]
@pospispa Has that change been merged yet? We probably shouldn't merge the docs change until the code change is in. Please ping me with a direct mention when the code has been merged.

**Comment by pospispa** [comment]
@devin-donnelly the code has not been merged yet. Sure, I'll ping you as soon as the code is merged.

**Comment by chenopis** [comment]
@pospispa Just checking to see what the status of this PR is. Thx

**Comment by chenopis** [comment]
@pospispa This PR looks stale, so I'm going to close it for now. Feel free to reopen it if you have plans to complete it. Cheers

**Pull request closed without merging**
