### PR TITLE
Fix to ensure that ConfigMaps volume does create file(s) in container

### PR DESCRIPTION
**Pull request by dims**
Document the fix proposed originally in:
https://github.com/kubernetes/kubernetes/issues/23392#issuecomment-209663941

Tested with:
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}

### CODE REVIEW

**Comment by spiralman** [comment]
You might want to document, in the prerequisites, that docker should be running with `MountFlags=shared` (per #23392), or, if you're using docker-machine (at least with virtualbox/boot2docker), you need to first run this command:

```
docker-machine ssh $(docker-machine active) sudo mount --make-shared /
```

**Comment by dims** [comment]
@spiralman In my environment, i still have "MountFlags=slave" in /lib/systemd/system/docker.service So i did not want to add it. Also since there is no mention of docker-machine on that page. it does not seem appropriate to add a reference to the --make-shared command

**Comment by spiralman** [comment]
@dims I certainly understand about `MountFlags=slave` (it's unclear from the referenced issue when or why that option needs to be enabled). And, more generally, I understand the need to keep the Getting Started guide simple, without documenting all the minutia of upstream projects.

That said, the documentation as changed in this PR will not work if you follow the default instructions for installing and configuring Docker Machine, and will fail on the very first command you try to run. 

I think Docker Machine is widely used on developers' development machines, where they are likely to be playing with Kubernetes for the first time, and it's frustrating if the first command in the getting started guide fails with a cryptic error message.

(More frustrating is I found no documentation whatsoever on how to map the `MountFlags` parameter from the systemd config to any other environment. That's an issue with the Docker project's docs, not this project's, but still relevant to a user new to the system).

There is also already a mention of docker-machine on that page, in the "Download `kubectl`" section, about setting up an SSH tunnel (confusingly, it says "On OS X", rather than explicitly saying "When using Docker Machine").

Perhaps there should be a separate section or page documenting specific issues/caveats related to running Kubernetes inside Docker Machine?

**Comment by dims** [comment]
@spiralman - am a n00b here and this was my 2nd(?) PR :) So i'll let others comment.

Also, +1 to "Perhaps there should be a separate section or page documenting specific issues/caveats related to running Kubernetes inside Docker Machine?"

**Comment by marun** [comment]
I'm afraid this issue is not limited to docker machine.  Any installation of docker whose process isn't configured with non-private mount propagation is affected, and this includes installation of upstream docker on a host with systemd (explicitly sets MountFlags=private in the unit file).

**Comment by kelseyhightower** [comment]
This looks good as a standalone thing. New PRs can be submitted to add more context, but this fixes the original issue. @dims Thanks for your contribution.

**Pull request merged**
