### PR TITLE
Deprecate federation-up/deploy.sh doc.

### PR DESCRIPTION
**Pull request by madhusudancs**
Ref: Issue #2809

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2889)

### CODE REVIEW

**Comment by madhusudancs** [comment]
cc @kubernetes/sig-docs-maintainers

**Comment by csbell** [comment]
Is there a reason to keep the old doc around? If there's 1.5 documentation that's available on k8s.io then we should just keep the short blurb that redirects to kubefed.

**Comment by madhusudancs** [comment]
@csbell there are two reasons why I think this doc should stay with a deprecation notice

1. I don't think it is possible to reach the previous version of the doc on [k8s.io/docs](https://k8s.io/docs). Not 100% sure though. @chenopis is this possible?

2. I want the documentation to follow the release distribution. We are not removing the scripts from the release in v1.6. So I want the documentation to stay and state that they are deprecated. When we remove the scripts in v1.7, we can remove this doc if there is a way to reach the previous versions of the doc.

**Comment by chenopis** [comment]
Currently, we don't have a good way to differentiate between docs that are tied to particular versions (e.g. 1.5 vs 1.6). However, part of the plan to is to start tagging features based on their dev state (alpha, beta, stable, deprecated) and which releases they are tied to. I won't be able to get to that until after we finish the documentation refactoring and 1.6 is out.

I agree that for now we should leave the old doc up w/ the deprecation notice. That way we won't break any inbound links. Also, we have started using a multi-step deprecation process that spreads things out (i.e. notice, URL redirects, removal of page and link from index) over several weeks so that people aren't surprised by sudden changes in the documentation. If this way of setting up a cluster federation has been used a lot and for multiple versions, I personally would spread out the docs deprecation over this next quarter so that people get a chance to adopt 1.6 and then finish the deprecation when 1.7 is released.

**Comment by madhusudancs** [comment]
@chenopis thanks for those details. I will watch out for the new tagging mechanism. That will be useful.

> If this way of setting up a cluster federation has been used a lot and for multiple versions, I personally would spread out the docs deprecation over this next quarter so that people get a chance to adopt 1.6 and then finish the deprecation when 1.7 is released.

Those scripts never really worked out of the box. But some people used modified versions of those scripts to make it work for them. So in a sense they were not just deprecated from a long time, but dead-on-arrival. But I don't want them to disappear overnight. 

The plan is to deprecate them now with a notice and to remove these completely in v1.7 along with the docs.

**Comment by devin-donnelly** [comment]
This is fine to stay with the deprecation notice for 1.6, but we should cut them in 1.7.

**Pull request merged**
