### PR TITLE
Fixed spelling error on cluster.svg for module 1 under training

### PR DESCRIPTION
**Pull request by jpeterson88**
This fix is for issue #1767 
https://github.com/kubernetes/kubernetes.github.io/issues/1767

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1769)

### CODE REVIEW

**Comment by jpeterson88** [comment]
I signed it!

**Comment by foxish** [comment]
CLA check

**Comment by jpeterson88** [comment]
Hello,Yes, I sent a pull request to fix the spelling on the .svg under the kubernetes tutorial 

    On Tuesday, November 22, 2016 5:09 PM, Anirudh Ramanathan <notifications@github.com> wrote:
 

 CLA check—

**Comment by foxish** [comment]
@jpeterson88 Thanks for sending a PR. It seems like your email is not set on your commit correctly, which is why the bot is refusing to acknowledge that you have signed the CLA. You may need to do https://help.github.com/articles/setting-your-email-in-git/, to match the email set on your commits with that on github.

**Comment by jpeterson88** [comment]
Anirudh, it looks like I pushed the repo from my work email. I changed the email on that repo and made a minor modification and did another commit. It's still seems that error from CLA is present. Any suggestions?

    On Tuesday, November 22, 2016 6:05 PM, Anirudh Ramanathan <notifications@github.com> wrote:
 

 @jpeterson88 Thanks for sending a PR. It seems like your email is not set on your commit correctly, which is why the bot is refusing to acknowledge that you have signed the CLA. You may need to do https://help.github.com/articles/setting-your-email-in-git/, to match the email set on your commits with that on github.—

**Comment by foxish** [comment]
@jpeterson88, The offending older commit is still by the old author. So, I think you'd have to recreate the commit and push.
Additionally, the image itself appears to have changed significantly. Could you please undo the changes other than the typo fix?
Thanks!

docs/tutorials/kubernetes-basics/cluster-intro/ v/s https://deploy-preview-1769--kubernetes-io-vnext-staging.netlify.com/docs/tutorials/kubernetes-basics/cluster-intro/

**Comment by devin-donnelly** [comment]
This has been fixed in a separate PR.

**Pull request closed without merging**
