### PR TITLE
Fix proxy environment variable names

### PR DESCRIPTION
**Pull request by gangefors**
According to the [vagrant-proxyconf plugin](https://github.com/tmatilai/vagrant-proxyconf#environment-variables) the environment variables should be named VAGRANT_.

I tested using the KUBERNETES_ names but the master timed out during
==> master: Prepare package manager
with a timeout error.

Using VAGRANT_ works, adding the proxy settings to /etc/environment in the vagrant machine.

### CODE REVIEW

**Comment by gangefors** [comment]
I signed it!

**Comment by johndmulhausen** [comment]
@gangefors can you fix the merge conflict so this PR can be salvaged?

**Comment by gangefors** [comment]
I'll fix it when I'm back from vacation. So some time after July the 4th.

**Comment by gangefors** [comment]
I've never rebased a pull request before, did the best I could. I hope the merge commits that github software on OSX added doesn't interfere with merging this PR.

**Comment by gangefors** [comment]
Also seems that the section I modified was removed when readding it in a previous commit. So the commit message is not correct. I'll try to fix it tomorrow.

**Comment by gangefors** [comment]
I think I've updated this correctly. You should be able to merge this now. Sorry for the delay.

**Pull request merged**
