### PR TITLE
Cleaner use of awk

### PR DESCRIPTION
**Pull request by rbtcollins**

### CODE REVIEW

**Comment by Kashomon** [comment]
Looks good, but can you sign the CLA and then we can get this merged?

**Comment by rbtcollins** [comment]
@Kashomon as far as I know I have signed the CLA - I contacted our legal team who maintain the k8s CLA agreement and they vetted everything.

**Comment by Kashomon** [comment]
So there are two routes to sign the CLA: 1) you can manually sign it or 2) Have your company have an agreement with Google. But in both cases, I believe you need to add your email address to your github account. Also, make sure that the email address is used as the git author email address. I.e., if your company has an agreement with Google and you use like an @gmail name instead of your company CLA, the CLA bot won't know that you've signed the CLA.

**Comment by rbtcollins** [comment]
Thats likely it, I used the github UI to do this particular patch, and it will have used a bong email. I'll put it down and fix the author up.

**Comment by rbtcollins** [comment]
Done; the author is now robertc at vmware dot com

**Comment by Kashomon** [comment]
Is it set for both git/github? Looks like it's still failing, sadly.

**Comment by kelseyhightower** [comment]
@rbtcollins Can you be sure to add robertc@vmware.com to your GitHub account? I do see that VMware has signed the corporate CLA, but it's not being picked up here.

**Comment by rbtcollins** [comment]
I've added that address to my github account.

**Comment by pwittrock** [comment]
@rbtcollins You will need to re-push the commit + PR after setting the user in your git client to be the vmware address.

**Comment by rbtcollins** [comment]
It already is:
```
git show
commit 00572183a9112f0709b8cc1399768c1a632ed60a
Author: Robert Collins <robertc@vmware.com>
Date:   Fri Jul 29 10:56:49 2016 +1200

    Cleaner use of awk

diff --git a/docs/user-guide/namespaces.md b/docs/user-guide/namespaces.md
index f497488..b7368b0 100644
--- a/docs/user-guide/namespaces.md
+++ b/docs/user-guide/namespaces.md
@@ -62,7 +62,7 @@ context.
 First get your current context:

 ```shell
-$ export CONTEXT=$(kubectl config view | grep current-context | awk '{print $2}')
+$ export CONTEXT=$(kubectl config view | awk '/current-context/ {print $2}')
 ```

 Then update the default namespace:
```

**Comment by rbtcollins** [comment]
And I've added the same address to github's email list

**Comment by kelseyhightower** [comment]
@rbtcollins Seems we are having trouble getting this patch through. Do you mind if I create a new PR based on this one? Or you can try closing this one and creating a new one. I would also suggest singing the CLA again from the `robertc@vmware.com` account.

**Comment by kelseyhightower** [comment]
@rbtcollins If creating a new PR does not work, we can try to debug your CLA status offline.

**Comment by kelseyhightower** [comment]
@rbtcollins I'm going to close this PR. Please try signing the CLA again (I know it should be working, but I'm not able to verify the CLA was signed for `robertc@vmware.com`). Then submit a new PR that I'll be happy to review and merge.

**Pull request closed without merging**
