### PR TITLE
ZTE-SH-CN-run-application-run-stateless-application-deployment-pr-201…

### PR DESCRIPTION
**Pull request by jianglingxia**
…7-09-18-1414

> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.8 Features: set Milestone to `1.8` and Base Branch to `release-1.8`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box (see image below) to
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5514)

### CODE REVIEW

**Comment by jianglingxia** [comment]
cc @zhangxiaoyu-zidif  I add cn but always failed,can you help me?thanks

**Comment by steveperry-53** [comment]
@jianglingxia Please rebase your branch so that it picks up 99fbc2b. That will fix the deploy/netlify failure. Thanks.

**Comment by jianglingxia** [comment]
cc @zhangxiaoyu-zidif 
need add /cn now?or remove it?

**Comment by zhangxiaoyu-zidif** [comment]
@tengqm 
This is a re-opened docs, this is lgtm to me.
I wait for your approval. =)

**Comment by jianglingxia** [comment]
@tengqm can you review the pr?if no problem please approve it,thanks!

**Pull request merged**
