### PR TITLE
Fixes Azure cluster creation fails and exits with an undefined 

### PR DESCRIPTION
**Pull request by albertoarias**
@bgrant0607 

https://github.com/kubernetes/kubernetes/pull/23498
https://github.com/kubernetes/kubernetes/issues/21067

Is the reverse/forward integration between the two repos automated?

### CODE REVIEW

**Comment by albertoarias** [comment]
@ShadySQL FYI

**Comment by pwittrock** [comment]
@albertoarias No the integration is not automated.  :(  We should really replace the old repo docs with redirects.

**Comment by bgrant0607** [comment]
cc @colemickens

**Comment by colemickens** [comment]
I'm not super familiar with this bring-up to be honest. Are you, @errordeveloper? If not, I can try to validate this PR at least...

**Comment by albertoarias** [comment]
Thanks folks, let me know if there is anything you need from me.

**Comment by errordeveloper** [comment]
There is another PR that updates the bringing docs and points to an
external repo under Weaveworks...

**Comment by errordeveloper** [comment]
I was referring to https://github.com/kubernetes/kubernetes.github.io/pull/314, which goes along with https://github.com/kubernetes/kubernetes/pull/23818.

**Comment by errordeveloper** [comment]
@albertoarias looks like #314 might finally get merged. Could please make a PR to https://github.com/weaveworks-guides/weave-kubernetes-coreos-azure and mention @errordeveloper?

**Comment by kelseyhightower** [comment]
Looks like this change is no longer required because #314 got merged. If that is not the case please feel free to rebase this and resubmit for review.

**Pull request closed without merging**
