### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
According to the context. The word should be "underspecified" meaning "insufficient".

> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2991)

### CODE REVIEW

**Comment by chenopis** [comment]
It's not clear to me that "underspec'd" means "underspecified" in this context.  "spec" is usually short for "specification," so although only slightly different, it could mean that the specification is currently insufficient.

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif Although I don't like the usage of "underspec'd," I've looked around and people do use that terminology. In any case, as a matter of policy, we shouldn't make statements in the documentation about the current state of something that is likely to change. Otherwise, we will accumulate a lot of outdated statements. Also, I think that sentence needs to be reworded slightly. My suggestion would be:

"HTTP server: The kubelet can also listen for HTTP requests and respond to a simple API call to submit a new manifest."

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis Thank you for your help. You are welcome~

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif Thank you! =)

**Pull request merged**
