### PR TITLE
Fix use of on-premises terminology

### PR DESCRIPTION
**Pull request by heidecke**
Fix for the use of on-premise vs. correct terminology of on-premises.

Additional file since #3730 (it's a plague!).

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4413)

### CODE REVIEW

**Comment by pwittrock** [comment]
This seems incorrect to me

**Comment by chenopis** [comment]
@heidecke I think we should stick w/ the abbreviated "on-prem" because that is pretty standard usage. It seems that people may not aware of the distinction between "on-premise" vs. the correct terminology of "on-premises".

**Comment by heidecke** [comment]
@chenopis I would recommend that we commit over abbreviate to on-prem (somewhere we would/should still define the full term, yeah?). I'm having a hard time finding precedence for the use of "on-prem" in documentation or marketing materials though. In verbal communication, on-prem is still fine by me. ;)

Industry usage of on-premises|premise is a bit of a wash, depending on multiple factors that I'm sure we could over analyze. Amazon tends to be fairly consistent with on-premises. Google uses a mix. In this blog (https://cloudplatform.googleblog.com/2017/07/going-Hybrid-with-Kubernetes-on-Google-Cloud-Platform-and-Nutanix.html), they use both! Microsoft Azure seems to be consistent with on-premises. I don't see any using the abbreviated on-prem term. OpenStack is all over the map (on-premise, on-premises, and private cloud).

The vendors/service providers that are building on top of Kubernetes seem to be fairly consistent with on-premises.

**Comment by heidecke** [comment]
It's also a good idea to clarify the usage of on-premises, where someone means OpenStack or Bare Metal. I can take another look at the docs that I edited to see if an alternate term may be more appropriate in some of these instances.

**Comment by chenopis** [comment]
@heidecke Ok, then I think we should standardize on "on-premises" and scrub the docs to get rid of "on-premise". =P But are there actually keys in config files, etc. that use the incorrect "on-premise"?

**Comment by heidecke** [comment]
@chenopis The only mention was an error message and comment in the AWS provider, which I happen to have already fixed. https://github.com/kubernetes/kubernetes/pull/49261

**Comment by heidecke** [comment]
I'll fix the conflict in ingress.md and push another commit.

**Comment by chenopis** [comment]
@heidecke Ok, cool. /lgtm Anything else you want to throw into this PR before I merge?

**Comment by heidecke** [comment]
@chenopis merged from latest master and resolved the conflict.

**Pull request merged**
