### PR TITLE
Cleaner use of awk

### PR DESCRIPTION
**Pull request by rbtcollins**

### CODE REVIEW

**Comment by rbtcollins** [comment]
@kelseyhightower  here is a new PR.

I've clicked on the cla.developers.google.com link; I then click 'for my company', and then it takes me through to a form to setup a company CLA - which VMWare has already done - and I'm not authorised to sign on behalf of the company :). So - I think perhaps we need to debug this - is there a specific checklist, or a description of the algorithm, so that I can figure out whats going on?

**Comment by kelseyhightower** [comment]
@rbtcollins How about I make this simple one line change, then maybe we can figure out what's going on with the CLA?

**Comment by rbtcollins** [comment]
There's also a change blocked on the same issue on kubernetes itself :/. But sure, I'm fine any which way - this was a drive by fix up after all, a trivial change.

**Comment by kelseyhightower** [comment]
@rbtcollins Ok, I've fixed this on the master branch. Let's resolve this issue on the main Kubernetes repo. I'm not sure what's going on, but I'm sure we'll get it resolved. Thanks for taking the time to contribute!

**Pull request closed without merging**
