### PR TITLE
Update ingress.md

### PR DESCRIPTION
**Pull request by caiyixiang**
Corrected a document link and a spelling mistake

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2179)

### CODE REVIEW

**Comment by chenopis** [comment]
@caiyixiang I think "loadbalancer" should be singular, not plural since it's referring to only 1 component. Just remove the 's'. Thx

**Comment by caiyixiang** [comment]
@chenopis Thanks，it has been updated

**Comment by chenopis** [comment]
@caiyixiang also, I noticed you need a '/' at the beginning of "docs/user-guide/deploying-applications" for the link to work properly, so it should be "/docs/user-guide/deploying-applications)". Thx

**Comment by caiyixiang** [comment]
@chenopis Thanks,it has been updated

**Pull request merged**
