### PR TITLE
Modify allocatable storage to ephemeral-storage

### PR DESCRIPTION
**Pull request by jingxu97**
Update the doc to use ephemeral-storage instead of storage

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5490)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@jingxu97, Please change the base branch to release-1.8. Thanks.

**Comment by saad-ali** [comment]
Thanks for the PR Jing!

Let's make sure that, in addition to Allocatable, Pod resource requests and limits are also updated to mention the new `ephemeral-storage` resource

**Comment by jingxu97** [comment]
The request/limits doc change is in PR https://github.com/kubernetes/kubernetes.github.io/pull/5522

**Pull request merged**
