### PR TITLE
Update multiple-schedulers doc 

### PR DESCRIPTION
**Pull request by foxish**
Addresses https://github.com/kubernetes/kubernetes/issues/39032
Updates the documentation to reflect new paths and commands where needed.
Adds `--leader-elect=false` to the example.

cc @kubernetes/sig-scheduling-misc

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2063)

### CODE REVIEW

**Comment by chenopis** [comment]
@davidopp Do you have time to review this? If not, can you suggest an alternate reviewer? Thx

**Comment by chenopis** [comment]
@foxish There seems to be some conflicts now, so if you can resolve them, I can merge this PR. Thx!

**Comment by foxish** [comment]
@chenopis Fixed conflicts. Thanks!

**Comment by chenopis** [comment]
Thanks @foxish!

**Pull request merged**
