### PR TITLE
update .../pods/index.md

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
change "clean" to "cleaning"

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2798)

### CODE REVIEW

**Comment by BlueMonday** [comment]
I think the existing sentence is correct and does not require any changes.

**Comment by zhangxiaoyu-zidif** [comment]
“clean” is a verb, while "cleaning" is a noun. That's why I want to change it.

**Comment by BlueMonday** [comment]
I still think the existing wording is correct. The full sentence is essentially: "Pod is exposed as a primitive in order to facilitate clean composition of Kubelet-level functionality with cluster-level functionality".

**Comment by BlueMonday** [comment]
> “clean” is a verb, while "cleaning" is a noun. That's why I want to change it.

In this particular case "clean" is an adjective and "composition" is the noun (clean is describing the composition).

**Comment by zhangxiaoyu-zidif** [comment]
You are right. I close it. Thank you.

**Pull request closed without merging**
