### PR TITLE
Delete redundant '\n'

### PR DESCRIPTION
**Pull request by chenhonggc**
Delete redundant `\n`.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5906)

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
if you think format of yaml is wrong, could you send one PR containing them, such as#5904, #5902

**Comment by chenhonggc** [comment]
I don't understand what you mean.

**Comment by zhangxiaoyu-zidif** [comment]
I mean that could you gather one kind of PRs into one PR, which will be convenient to assign reviewer.

**Comment by chenhonggc** [comment]
Thanks. :smile:

**Pull request merged**
