### PR TITLE
Fix copy/paste errors in federated secrets docs

### PR DESCRIPTION
**Pull request by mwielgus**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1824)

### CODE REVIEW

**Comment by madhusudancs** [comment]
@mwielgus LGTM!

**Comment by madhusudancs** [comment]
@devin-donnelly @jaredbhatti This is a trivial change, I would just rather merge it instead of waiting for docs review. Can I?

**Comment by devin-donnelly** [comment]
Should these be fixed now? Or are the contingent on changes in the 1.5 launch?

**Comment by madhusudancs** [comment]
@devin-donnelly this should be fixed now.

**Comment by devin-donnelly** [comment]
Okay, I'll merge it.

**Comment by madhusudancs** [comment]
@devin-donnelly thanks!

**Pull request merged**
