### PR TITLE
Update LICENSE to CC BY SA 4.0

### PR DESCRIPTION
**Pull request by craigbox**
Text copied from https://creativecommons.org/licenses/by/4.0/legalcode.txt.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1763)

### CODE REVIEW

**Comment by craigbox** [comment]
Associated w/corporate CLA.

**Comment by jaredbhatti** [comment]
Docs LGTM, but waiting on lawyercats.

**Comment by dankohn** [comment]
+1 That this follows the intent of the CNCF charter.

**Comment by jaredbhatti** [comment]
LGTM.

**Pull request merged**
