### PR TITLE
fix the command output

### PR DESCRIPTION
**Pull request by chenhuan12**
fix the command output

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5518)

### CODE REVIEW

**Comment by tengqm** [comment]
May I know what is being fixed by this patch?

**Comment by steveperry-53** [comment]
@chenhuan12 Please rebase your branch so that it picks up 99fbc2b. That will fix the deploy/netlify failure. Thanks.

**Comment by chenhuan12** [comment]
cc @zhangxiaoyu-zidif

**Comment by zhangxiaoyu-zidif** [comment]
@chenhuan12 
Hi， could you tell us your *kubernetes version*

**Comment by chenhuan12** [comment]
# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.9+a3d1dfa6f4335", GitCommit:"eb26ffbbf057d8e42362444ae2b91d74ac1febb7", GitTreeState:"dirty", BuildDate:"2017-09-12T20:36:51Z", OpenPaasKubernetesVersion:"v1.03.03", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.9+a3d1dfa6f4335", GitCommit:"eb26ffbbf057d8e42362444ae2b91d74ac1febb7", GitTreeState:"dirty", BuildDate:"2017-09-12T20:36:51Z", OpenPaasKubernetesVersion:"v1.03.03", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by zhangxiaoyu-zidif** [comment]
which version do you test it? @chenhuan12
Because you want this PR to merge into master branch, I recommand you to use recent verion. Thanks.

**Comment by steveperry-53** [comment]
@zhangxiaoyu-zidif @markthink @chenhuan12 Please comment so we can either move forward or close this.

Same for #5516

**Comment by zhangxiaoyu-zidif** [comment]
I recommend to close it currently. If this output from the recent version, that would be reasonable, but if it is from a older version, that would be unnecessary. Same as #5516

**Pull request closed without merging**
