### PR TITLE
make docker daemon on Minikube VM  use proxy 

### PR DESCRIPTION
**Pull request by WanLinghao**
I am a fresh man from China,you must know about the terrible GWF.
When I use Minikube ,I faced the problem that how to configure Internet setting correctly to make everything work.
Due to the proxy on my PC,the Docker daemon in Minikube can't  access Internet.I have tried the way 
on document as follows:
$ minikube start --docker-env HTTP_PROXY=http://$YOURPROXY:PORT \
                 --docker-env HTTPS_PROXY=https://$YOURPROXY:PORT
However,seems it doesn't work,I checked the log on Minikube Virtual Machine which reveals that the Docker still connect network directly rather than use proxy.
The content I added into the document is the way that works on my computer.Docker daemon in Minikube works successfully base on these.
Hope it  helps.^_^

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4414)

### CODE REVIEW

**Comment by dlorenc** [comment]
Hey,

It looks like this might be a bug in minikube itself, if you have to make the change this way. Would you mind opening an issue in the minikube repo and we can fix it there rather than have to make this documentation change?

**Comment by WanLinghao** [comment]
@dlorenc  ok，thanks

**Comment by WanLinghao** [comment]
@dlorenc  minikube repo:#1723

**Comment by chenopis** [comment]
@dlorenc So, can I close this PR then?

**Comment by dlorenc** [comment]
Yeah you should be able to close this.

**Pull request closed without merging**
