### PR TITLE
Update out-of-date text about NewInCluster()

### LINKED ISSUE #1491: NewInCluster info is out of date
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The line in http://kubernetes.io/docs/user-guide/accessing-the-cluster/#accessing-the-api-from-a-pod about `NewInCluster` is (a) out of date and (b) pointing to a broken link.

**Proposed Solution:**

The link should be https://github.com/kubernetes/client-go/blob/master/examples/in-cluster/main.go

The text should talk about `InClusterConfig` and `NewForConfig`

**Page to Update:**
http://kubernetes.io/docs/user-guide/accessing-the-cluster

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #1491

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1495)

### CODE REVIEW

**Comment by bboreham** [comment]
Oops, the example seems to have moved again.  Deleted in https://github.com/kubernetes/client-go/commit/75399f68c88d27167979821ac280936cfb13cfd6

**Comment by bboreham** [comment]
I changed the URL to use the `1.4` branch instead of `master`.

**Comment by bboreham** [comment]
The examples directory was added back in https://github.com/kubernetes/client-go/pull/23; is it better to link to `master` which might disappear or `1.4` which will eventually go out of date (but then, so may the surrounding text) ?

**Comment by devin-donnelly** [comment]
@janetkuo, can you verify that the link to the example is going to the correct spot?

**Comment by janetkuo** [comment]
re-assigning to @caesarxuchao since it's client-go related

**Comment by bboreham** [comment]
Can I do anything to help move this along?

**Comment by bboreham** [comment]
> I changed the URL to use the 1.4 branch instead of master.

But the 1.4 branch disappeared :disappointed: I have moved the link back to `master`.

**Comment by caesarxuchao** [comment]
Thanks @bboreham!

**Comment by jaredbhatti** [comment]
Can you address the conflicts?  I'll merge afterwards.

**Comment by bboreham** [comment]
Conflict was caused by you merging a slightly worse fix to the same issue.

**Comment by bboreham** [comment]
Rebased again

**Pull request merged**
