### PR TITLE
Rename docs/getting-started-guides/windows/README

### PR DESCRIPTION
**Pull request by saad-ali**
Rename docs/getting-started-guides/windows/README.md to index.md

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1915)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
Works for me. LGTM.

**Comment by devin-donnelly** [comment]
Works for me. LGTM.

**Comment by janetkuo** [comment]
@devin-donnelly @saad-ali https://deploy-preview-1915--kubernetes-io-vnext-staging.netlify.com/docs/getting-started-guides/windows/ still gives me 404?

**Comment by saad-ali** [comment]
It required PR https://github.com/kubernetes/kubernetes.github.io/pull/1927 as well. See https://deploy-preview-1930--kubernetes-io-vnext-staging.netlify.com/docs/getting-started-guides/windows/

**Pull request merged**
