### PR TITLE
Update user-guide/node-selection/index.md to include pod affinity/anti-affinity

### PR DESCRIPTION
**Pull request by davidopp**
and addd an example. Also clean up user-guide/node-selection/index.md a bit.

I'm not sure why the code include lines aren't working; it seems to be following the directions in 
http://kubernetes.io/editdocs/
for how to include text from another file.

@kubernetes/docs to review and hopefully answer the question above

cc/ @kevin-wangzefeng @janetkuo

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1148)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/user-guide/node-selection/index.md, line 99 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1148#-KQh8S8ieIV9BBMAHTQq:-KQh8S8ieIV9BBMAHTQr:b6kkdkk) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/9efec7563ed90efa6b12f5601b00dc4d1fd5038b/docs/user-guide/node-selection/index.md#L99)):*
> ```Markdown
> ### Node affinity (alpha feature)
> 
> Node affinity was introduced in Kubernetes 1.2. The design doc is [here](https://github.com/kubernetes/kubernetes/blob/{{page.githubbranch}}/docs/design/nodeaffinity.md).
> ```

I'd move the design doc link to the end of the section as a "for more information" type thing; lead with what Node Affinity actually does (third sentence).

---

*[docs/user-guide/node-selection/index.md, line 131 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1148#-KQh8EdkVp5Sqg3h27Cy:-KQh8EdkVp5Sqg3h27Cz:b5zc992) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/9efec7563ed90efa6b12f5601b00dc4d1fd5038b/docs/user-guide/node-selection/index.md#L131)):*
> ```Markdown
> ### Inter-pod affinity and anti-affinity (alpha feature)
> 
> Inter-pod affinity and anti-affinity were introduced in Kubernetes 1.4. The design doc is [here](https://github.com/kubernetes/kubernetes/blob/{{page.githubbranch}}/docs/design/podaffinity.md).
> ```

I'd put the design doc link at the end so as not to bury the lead (i.e. what Inter-pod affinity and anti-affinity allow you to do).

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1148)*

**Comment by devin-donnelly** [comment]
Docs LGTM pending a couple of suggestions.

**Comment by davidopp** [comment]
Updated.

**Comment by devin-donnelly** [comment]
If we can retarget this PR to the release-1.4 branch, I can merge it now. Otherwise, it'll have to wait until 1.4 goes out.

**Comment by kevin-wangzefeng** [comment]
LGTM, thanks!

**Comment by davidopp** [comment]
New commit pushed.

**Comment by davidopp** [comment]
OK I was able to resuscitate the files I accidentally deleted. PTAL.

**Comment by devin-donnelly** [comment]
Looks good. Merging now.

**Pull request merged**
