### PR TITLE
Update configure-pod-configmap.md to use correct a key in given pod deployment yaml

### PR DESCRIPTION
**Pull request by saborse**
Key is defined as "log_level" in Configmap viz. "env-config", and should be used as is, in pod definition.

> NOTE: Please check the “Allow edits from maintainers” box (see image below) to  
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4484)

### CODE REVIEW

**Comment by saborse** [comment]
Done with CLA procedure.

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 1eaef67a9e8bb15af1bdf52e68d0f25d9cbfa564

https://deploy-preview-4484--kubernetes-io-master-staging.netlify.com

**Comment by chenopis** [comment]
@tengqm I've seen this change elsewhere. Can you confirm that it's correct? Thx

**Comment by zacharysarah** [comment]
@saborse 👋 Closing this issue in favor of #4794.

**Pull request closed without merging**
