### PR TITLE
Add link to IBM SoftLayer instructions

### PR DESCRIPTION
**Pull request by patrocinio**
This is a continuation of PR 1183 (https://github.com/kubernetes/kubernetes.github.io/pull/1183), which I messed up when I rebased.

--- Original comments:

Originally, I created a page describing the turn-key solution to deploy Kubernetes in IBM SoftLayer, but the reviewer on the following PR #313 asked me to host the information in another repository.

So this PR is to create a link to the external repository containing the instructions.

Thanks!

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1198)

### CODE REVIEW

**Comment by patrocinio** [comment]
@devin-donnelly I need to create a new PR because I messed up during rebase.

**Comment by devin-donnelly** [comment]
LGTM. Thanks. Is this ready for immediate publication? If so, I'll merge.

**Comment by patrocinio** [comment]
Yes, it is. Thanks for doing it!

**Comment by janetkuo** [comment]
@patrocinio maybe you'd want to update the [table of solutions](http://kubernetes.io/docs/getting-started-guides/#table-of-solutions) too?

**Comment by patrocinio** [comment]
@janetkuo Good point... I'll update the table of solutions. I thought they were not for turn-key ones, but I see GCE there.

I'll work on it in another PR.

**Pull request merged**
