### PR TITLE
redundnacy => redundancy

### PR DESCRIPTION
**Pull request by JWimsingues**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2459)

### CODE REVIEW

**Comment by JWimsingues** [comment]
I signed it! 

-- 
Jérémy Wimsingues 


De: "k8s-ci-robot" <notifications@github.com> 
À: "kubernetes/kubernetes.github.io" <kubernetes.github.io@noreply.github.com> 
Cc: "jeremy wimsingues" <jeremy.wimsingues@insa-lyon.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 8 Février 2017 11:28:50 
Objet: Re: [kubernetes/kubernetes.github.io] redundnacy => redundancy (#2459) 



Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA). 

📝 Please follow instructions at https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ to sign the CLA. 

Once you've signed, please reply here (e.g. "I signed it!") and we'll verify. Thanks. 


    * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits . 
    * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized. 


Instructions for interacting with me using PR comments are available here . If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository. I understand the commands that are listed here .

**Comment by chenopis** [comment]
@JWimsingues Can you check to see if you signed the CLA using the same email address as your GitHub account? Thx

**Comment by JWimsingues** [comment]
just linked the accounts, sorry about that..

**Comment by chenopis** [comment]
@JWimsingues Hmmm. It's still not passing the CLA check.

**Comment by JWimsingues** [comment]
Should be good, sorry didn't manage to do it before

**Comment by chenopis** [comment]
Thanks @JWimsingues !

**Pull request merged**
