### PR TITLE
Create case study page for Box

### PR DESCRIPTION
**Pull request by alexcontini**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.7 Features: set Milestone to `1.7` and Base Branch to `release-1.7`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4230)

### CODE REVIEW

**Comment by alexcontini** [comment]
Hello,

I have signed the CLA. Let me know if there are any problems!

Alex

**Comment by steveperry-53** [comment]
Put case-studies/style_box.css in this PR, and then close PR 4231. Then click Show all checks > deploy/netlify Details to see the topic staged.

**Comment by chenopis** [comment]
@alexcontini @steveperry-53 We need to expedite these PRs for the Box case study because the main blog article about the v1.7 has a link to it: http://blog.kubernetes.io/2017/06/kubernetes-1.7-security-hardening-stateful-application-extensibility-updates.html

**Comment by chenopis** [comment]
I'm going to close this since it looks like it's being taken care of in https://github.com/kubernetes/kubernetes.github.io/pull/4235.

**Pull request closed without merging**
