### PR TITLE
tutorials/guestbook, tutorials/cassandra: import latest

### PR DESCRIPTION
**Pull request by ahmetb**
Importing from kubernetes/examples repository.

/assign @cody-clark

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4775)

### CODE REVIEW

**Comment by chenopis** [comment]
ping @cody-clark

**Comment by ahmetb** [comment]
I just updated this PR to import `guestbook`, as well as `cassandra` tutorials.

@cody-clark to check the rendering
/assign @chenopis to merge

**Comment by cody-clark** [comment]
@chenopis Something weird is happening for the .yaml excerpt on line 192. It renders fine in the [Github Preview](https://screenshot.googleplex.com/su7VRv0pNQ9.png) and in my own [Github Pages site](https://cody-clark.github.io/2017/08/04/test.html), but becomes a [codeblock paragraph](https://screenshot.googleplex.com/3yK7q30yzqS.png) in the Netlify preview.

**Comment by ahmetb** [comment]
Try with 2, 4, 6, 8 spaces of indentation. One of them should work. I can update the commit if you find a solution.

I promise I'll bring the tutorial contents back here soon so we don't have to go through this import dance again.

**Comment by chenopis** [comment]
@cody-clark Yeah, you might want to try 8 spaces. Also, check to see how many spaces are in front of `{: .note}`. If it's only 3, then try making it 4.

Have I mentioned lately that I hate markdown? LOL

**Comment by cody-clark** [comment]
@chenopis @ahmetb Any strong opinions against just deleting the excerpt? It doesn't really add to the documentation and it's blocking some important updates like working download links. 

Or we could merge this and fix the block when this repo is independent and trial and error checking is more forgiving.

And I love that Markdown's consistently inconsistent :) It adds a new dimension to "no two days are the same." :')

**Comment by jaredbhatti** [comment]
@cody-clark I suggest deleting the excerpt or just removing the "note:" callout field and leaving the text.

**Comment by ahmetb** [comment]
It's a minor rendering issue I think we can fix separately after merging if no objections.

**Comment by cody-clark** [comment]
@chenopis LGTM

**Comment by chenopis** [comment]
@ahmetb Ok, let's fix the md rending issue in a different PR. /lgtm

**Comment by chenopis** [comment]
@ahmetb Can you fix the merge conflict?

**Comment by ahmetb** [comment]
Done

**Pull request merged**
