### PR TITLE
Fix typos in running zookeeper article

### PR DESCRIPTION
**Pull request by guillaumebreton**
I fixed 2 typos regarding the zkGenConfig.sh script : one was called ```zkConfig.sh``` and the other was called ```zkConfigGen.sh```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2562)

### CODE REVIEW

**Comment by foxish** [comment]
@guillaumebreton Thanks for the PR! 
Could you please sign the CLA so that we can get this merged?

**Comment by guillaumebreton** [comment]
I signed it!

**Comment by guillaumebreton** [comment]
@foxish do you want me to update the branch with the master ?

**Comment by foxish** [comment]
@guillaumebreton I think it's not needed. @chenopis can update the branch and merge this.

**Comment by chenopis** [comment]
Yeah, I usually merge w/ the rebase option.

**Pull request merged**
