### PR TITLE
AppArmor documentation

### PR DESCRIPTION
**Pull request by timstclair**
Adds full documentation for AppArmor.

Original proposal: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/apparmor.md
Feature issue: https://github.com/kubernetes/features/issues/24

Note: 2 features referenced in this document have not yet been merged:

- Profile loader DaemonSet: https://github.com/kubernetes/contrib/pull/1658
- NodeStatus ready condition: https://github.com/kubernetes/kubernetes/pull/31659

/cc @thockin @jfrazelle @pwittrock @dchen1107 @matchstick

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1132)

### CODE REVIEW

**Comment by timstclair** [comment]
cc @kubernetes/docs

**Comment by timstclair** [comment]
@devin-donnelly This needs to be merged by 1.4, if you don't have time to review please reassign.

**Comment by pwittrock** [comment]
This should probably be in the v1.4 branch

**Comment by timstclair** [comment]
@pwittrock Does that mean I should close this PR and reopen it against the `release-1.4` branch?

**Comment by timstclair** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes.github.io/pull/1147

**Pull request closed without merging**
