### PR TITLE
NetworkPolicy updates for v1

### PR DESCRIPTION
**Pull request by danwinship**
First commit does some miscellaneous rewriting (see commit message), second commit just updates things to use the v1 API stuff.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3721)

### CODE REVIEW

**Comment by danwinship** [comment]
/assign @caseydavenport 
since you wrote the original stuff...

**Comment by caseydavenport** [comment]
/approve 
/lgtm 

Thanks @danwinship!

**Comment by bboreham** [comment]
Why was this change made to the live docs when we are still debating the change to the code and several weeks away from releasing the new code?

**Comment by danwinship** [comment]
I had already written the docs, so I filed the PR so it could be reviewed and then it basically accidentally got committed, and it looked at that point like the code PR was about to merge so I figured it didn't matter much. I didn't realize this would affect the live docs though; it was only meant to be for 1.7+.

Given that this is not going to be entirely correct even for 1.7, maybe we should just revert it now and I'll fix it again later.

**Comment by caseydavenport** [comment]
Yeah, I didn't spot that this was against master and not the `release-v1.7` branch. 

This should be reverted.

**Pull request merged**
