### PR TITLE
Missing executable in docker command line

### PR DESCRIPTION
**Pull request by jimmyjones2**

### CODE REVIEW

**Comment by jimmyjones2** [comment]
I signed it!

**Comment by mikedanese** [comment]
Is this neccessary? The default command is:
```
["/bin/sh" "-c" "/opt/bin/flanneld"]
```

https://quay.io/repository/coreos/flannel/image/7db3dc782eb5fd83fa147f9ba5ca73d7e4dd1f97bae8d5887689a0e9091e86b1

**Comment by jimmyjones2** [comment]
The makes the docs match the worker node docker invocation and master.sh. My old (1.7.1) docker appeared to barf without it.

**Comment by luxas** [comment]
@mikedanese It is. `CMD` is `["/bin/sh" "-c" "/opt/bin/flanneld"]` but no `ENTRYPOINT` is specified. That makes the arguments override `CMD` without pointing to a executable file.
If `ENTRYPOINT` would have been `/opt/bin/flanneld` there wouldn't be an issue.

**Pull request merged**
