### PR TITLE
Add diagram for `kubectl rolling-update` cmd

### PR DESCRIPTION
**Pull request by andreykurilin**
Related issue: #528

### CODE REVIEW

**Comment by johndmulhausen** [comment]
@andreykurilin -- so, to which document are you hoping to add this diagram?

**Comment by andreykurilin** [comment]
@johndmulhausen hi! It looks like another pr to kubernetes/kubernetes was not linked to #528 issue :( 
I want to add this diagram to description of command(see https://github.com/kubernetes/kubernetes/pull/25810 for more details)

**Comment by andreykurilin** [comment]
@bgrant0607 hi! Could you review this diagram?

**Comment by janetkuo** [comment]
Thanks for the diagram! Although I feel that it contains implementation details and therefore is more suitable for developers rather than end users. WDYT?

**Comment by andreykurilin** [comment]
@janetkuo Sorry for delay. 
I think you are right. I will reduce details and try to make this diagram more user-oriented

**Comment by janetkuo** [comment]
@andreykurilin sounds good, thanks much!!

**Comment by andreykurilin** [comment]
@janetkuo Could you check current svg?

**Comment by janetkuo** [comment]
A couple of thoughts/suggestions:

1. `Get old RC foo --> RC foo is not found --> T/F` is less intuitive than `Get old RC foo --> Found/Not found` IMO
2. Source Id Annotation is implementation detail, consider making the path starting from "RC foo is not found --> T" more general (less implementation details)
3. Should we make the arrow for --> T look different from --> F? (e.g. one with dotted lines)
4. Should we separate exit with/without error?

**Comment by andreykurilin** [comment]
@janetkuo done

**Comment by janetkuo** [comment]
@andreykurilin Looks good, thanks!

**Comment by andreykurilin** [comment]
@janetkuo thanks!
Could you look at kubectl doc change too?

**Pull request merged**
