### PR TITLE
New "Why containers?" diagram

### PR DESCRIPTION
**Pull request by mindymo**
Would fit well on http://kubernetes.io/docs/whatisk8s/, in the "Why containers?" section. 

Diagram created from WSO2Con slides 4-5. 

Ref: https://github.com/kubernetes/kubernetes.github.io/issues/84

### CODE REVIEW

**Comment by mindymo** [comment]
CLA signed!

**Comment by johndmulhausen** [comment]
Looks great but can you crop it super tight and re-save the SVG? We need a version with absolutely no borders; I can always add whitespace if I need but it's very hard to take away.

**Comment by mindymo** [comment]
Updated! No more whitespace. :) 

Commit reference: 375ae260272e1d19e98374820d8f2d9304b8dfa9

**Comment by johndmulhausen** [comment]
Looks fantastic! Can you ping me with an email address so I can send you your bounty? :)

**Comment by mindymo** [comment]
Hey, @johndmulhausen ! Thanks for the merge, it was great to help with this project! You can reach me at mindy.moreland@puppet.com .

**Pull request merged**
