### PR TITLE
Rely more official Jekyll plugins for common behavior

### PR DESCRIPTION
**Pull request by benbalter**
This pull request is a series of (hopefully) atomic commits, with some targeted suggestions for how the site could rely on some of the official Jekyll Plugins a bit more, but I'm equally as glad to break this up into several PRs, or help cherry-pick as desired.

Looking at the site to debug a GitHub Pages issue, I noticed there were several opportunities to rely on several of the official Jekyll plugins, many of which are simply shared, battle-tested templates, that better account for edge cases and enforce many Jekyll style conventions, with the goal of reducing overall complexity and the maintainability burden (if there's less custom code in the repo, there's less to update and less that can go wrong).

There's more details in each commit, but here's what I'm proposing in this pull request:

## Use the GitHub Pages Gem (ad99f86c357b45ceeb2e9eb6e82ab3a0d8c72dc3, e971f9cb)

The GitHub Pages Gem (https://github.com/github/pages-gem) is a meta-gem that does two things:

1. It locks dependencies to the same version used by GitHub Pages ensuring that when you build the site locally, you're using the same version of plugins and other dependencies used in production.

2. When loaded as part of the :jekyll_plugins group, it allows the Gem to set certain configuration defaults and overrides (such as activating default plugins) to ensure, once again that your local preview replicates the production version as closely as possible.

Rather than lock each dependency explicitly (which will cause the local and staging preview to differ from production as it does today), let the Pages Gem manage the dependency versions for us.

## Use Jekyll Feed to generate the Atom feed (	f08e807)

Jekyll Feed (https://github.com/jekyll/jekyll-feed) is an official Jekyll plugin which should replicate the existing feed nearly identically, but with a shared, battle-tested template that accounts for all sorts of edge cases like relative links in feed entries.

It should be a drop in replacement and "just work" without any additional configuration. That said, it doesn't appear that there are any posts, as the existing feed is blank. It may be best to remove the feed all together?

## Use Jekyll Sitemap to generate the sitemap (8f1f8d4, 5de1103)

Jekyll Sitemap (https://github.com/jekyll/jekyll-sitemap) is an official Jekyll plugin, which should serve as a drop-in replacement for the existing sitemap.xml. The resulting sitemap should be largely
similar to the existing sitemap, but with a shared, battle-tested template that accounts for all sorts of edge cases, handles collections and static files, etc.

Here's what the sitemap looks like today:

screen shot 2016-12-13 at 2 22 26 pm

And here's what it looks like with the plugin:

screen shot 2016-12-13 at 2 22 17 pm

The lastmod fields are removed, because they're the time the *site* is last modified, and thus are largely ignored/inaccurate.

## Add title and description to _config.yml (cb9c9dc)

Although the title already has a "name" entry, this commit replicates the name as "title", and adds a "description" entry, both of which are shared across common, official Jekyll plugins like jekyll-feed
and jekyll-sitemap.

This allows the feed and sitemap to properly output the title and description in various places (along with Jekyll SEO tag). I grabbed the description from the existing human-readable subhead.

## Remove "baseurl" from _config.yml (69a6958)

Remove `baseurl` from the config for three reasons:

1. It's not used anyplace within the site

2. The site’s base URL is only to be used when the resulting site lives at a subpath of the domain. Otherwise, the subpath should be nil, not / (see http://ben.balter.com/jekyll-style-guide/config/#baseurl)

3. When the Pages Gem is loaded as part of the :jekyll_plugins group, baseurl and url are set automatically.

## Use the `absolute_url filter to generate the canonical URL (91634d1)

Starting with Jekyll v3.3, Jekyll ships with `relative_url` and `absolute_url` filters. Rather than manual concatenating strings, we can rely on Jekyll to handle the logic in Ruby land, which takes into account the site's URL (locally and in production), and handles things like double "/"s.

While less important for the canonical URL, for other URLs, when previewed locally, the URL will be `http://localhost:4000`, rather than the live URL, allowing you to use the filter for things like assets, without frustration or local overrides.

## 	Use Jekyll SEO Tag to generate the search engine HEAD meta (731f5ba, e6675060)

This change is the most "aggressive", and I'd be glad to talk through it more. There may be some incompatibilities with the site's custom logic, but at first glance, it appears to work as expected. The change moves the site to use the official Jekyll SEO Tag plugin (https://github.com/jekyll/jekyll-seo-tag) to generate the search-engine meta in the HEAD of each page. The title and canonical URL output should be largely the same as before, but with additional metadata, such as JSON-LD (for richer indexing), Twitter card metadata, etc.

Like the other plugins, this should largely work out-of-the-box, with no additional day-to-day configuration, but is customizable where desired.

Here's the title SEO metadata now for the homepage:

```html
  <title>Kubernetes - Production-Grade Container Orchestration</title>
```

And here's what it'd look like with the plugin:

```html
	<!-- Begin Jekyll SEO tag v2.1.0 -->
<title>Kubernetes - Production-Grade Container Orchestration</title>
<meta property="og:title" content="Kubernetes" />
<meta name="description" content="Production-Grade Container Orchestration" />
<meta property="og:description" content="Production-Grade Container Orchestration" />
<link rel="canonical" href="http://localhost:4000/" />
<meta property="og:url" content="http://localhost:4000/" />
<meta property="og:site_name" content="Kubernetes" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@kubernetesio" />
<script type="application/ld+json">
{"@context": "http://schema.org",
"@type": "WebSite",
"name": "Kubernetes",
"headline": "Kubernetes",
"description": "Production-Grade Container Orchestration",
"publisher": {"@type": "Organization",
"logo": {"@type": "ImageObject",
"url": "http://localhost:4000/images/favicon.png"}},
"url": "http://localhost:4000/"}</script>
<!-- End Jekyll SEO tag -->
```

There's a lot there, and again, I'm glad to talk through any of the above, or break the commits into individual pull requests, but I believe that relying more heavily on the Jekyll community may help simplify the day-to-day workflow of building and maintaining the site.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1942)

### CODE REVIEW

**Comment by jaredbhatti** [comment]
Thanks for these changes. Can you sign the CLA for the linux foundation?

**Comment by jessfraz** [comment]
wow thanks so much

**Comment by jessfraz** [comment]
wow this looks a lot better, thanks so much, as far as I can tell all the changes look good!
LGTM (after the cla of course)

**Comment by benbalter** [comment]
> Can you sign the CLA for the linux foundation?

I believe my colleague @bluemazzoo initiated the process of establishing a corporate CLA on behalf of GitHub this afternoon. GitHub ❤️ Kubernetes.

**Comment by benbalter** [comment]
I *believe* I should now be a member of the CNCF - GitHub organization, which means that there should be a valid CLA on file, under which my contribution is covered.

**Comment by steveperry-53** [comment]
@jessfraz, https://github.com/kubernetes/kubernetes.github.io/issues/1959

**Pull request merged**
