### PR TITLE
Trying to create a main header

### PR DESCRIPTION
**Pull request by andrewwatson**
It's using the first sub-header about volumes as the header of the page.  I'm thinking this might fix that?

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1955)

### CODE REVIEW

**Comment by andrewwatson** [comment]
wait, i think i might see what the real culprit is here...

**Comment by bgrant0607** [comment]
Related to #1942 ?

**Comment by andrewwatson** [comment]
Yes, quite possibly!

**Comment by devin-donnelly** [comment]
The titling issue got fixed by #1942. I'll go ahead and close this to avoid duplicate titling.

**Pull request closed without merging**
