### PR TITLE
Remove outdated Calico / Fedora guide.

### PR DESCRIPTION
**Pull request by caseydavenport**
I thought we removed this guide a while ago, but somehow it's still there!  See this PR: https://github.com/kubernetes/kubernetes/pull/22475

It's way out of date.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1131)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@caseydavenport, thanks! LGTM.
@devin-donnelly Do you know if I need to apply other label to get this merged?

**Comment by jaredbhatti** [comment]
Please remove the link to this file from the left nav as well: 
kubernetes.github.io/_data/guides.yml

**Comment by caseydavenport** [comment]
@jaredbhatti - thanks, fixed.

**Comment by devin-donnelly** [comment]
Thanks! Merged and closed.

**Pull request merged**
