### PR TITLE
Update documentation of configuration of dynamic provisioning

### PR DESCRIPTION
**Pull request by jsafrane**
Add/update docs according to current code scheduled for Kubernetes 1.5

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1594)

### CODE REVIEW

**Comment by saad-ali** [comment]
Tech changes LGTM.

If these changes are only for 1.5, then they should go in the release-1.5 branch first (once it is cut), and then be cherry-picked back to master.

CC @devin-donnelly

**Comment by jsafrane** [comment]
The changes are for kubernetes >= 1.5, I hope it won't be changed again in 1.6.

**Comment by jaredbhatti** [comment]
Please rebase this PR against the 1.5 release branch.

**Comment by jsafrane** [comment]
rebased to release-1.5

**Comment by jsafrane** [comment]
removing do-not-merge,I want it in 1.5

**Pull request merged**
