### PR TITLE
Change RDB typo to RBD

### PR DESCRIPTION
**Pull request by rickypai**
I assume this is referring to `RBD (Ceph Block Device)` and not something else

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1436)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@rickypai you need to sign the linuxfoundation CLA

**Comment by rickypai** [comment]
done

**Comment by mikedanese** [comment]
Please drop the merge commit.

**Comment by rickypai** [comment]
done

**Pull request merged**
