### PR TITLE
Added missing APIs to reference left-nav

### PR DESCRIPTION
**Pull request by erictune**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1806)

### CODE REVIEW

**Comment by erictune** [comment]
Based on #1802.  Only look at last commit of this PR.

**Comment by erictune** [comment]
Adds the following to the left-nav for Reference.

- Apps API (fyi @kubernetes/sig-apps)
- Authentication API (fyi @kubernetes/sig-auth)
- Authorization API fyi @kubernetes/sig-auth)
- Batch API for v2alpha1 (fyi @kubernetes/sig-apps)
- Certificates API (fyi @gtank @mikedanese)
- Policy API (fyi @davidopp)
- RBAC Authorization API (fyi @kubernetes/sig-auth)
- Storage API (fyi @kubernetes/sig-storage)

**Comment by erictune** [comment]
These should all be referenced from the various concept guides.

**Comment by soltysh** [comment]
LGTM

**Comment by devin-donnelly** [comment]
@janetkuo @erictune I think a duplicate PR just addressed some of these same issues. Can this be closed?

If not, this should retarget Master; release-1.5 has been merged and is functionally defunct.

**Comment by janetkuo** [comment]
I'm closing this PR just because GitHub doesn't allow updating target branch in a PR. Feel free to open a new one targeting `master` branch.

**Pull request closed without merging**
