### PR TITLE
Move Commands and Capabilities out of User Guide.

### PR DESCRIPTION
**Pull request by steveperry-53**
This is part of our overall plan to move content out of the User Guide and into Tasks, Tutorials, and Concepts.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2386)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@chenopis, Will you be the reviewer for this.

**Comment by chenopis** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2386)*

**Comment by steveperry-53** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/user-guide/containers.md, line 7 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2386#-Kblti-p0w2lohR4pBIa-r1-7:-Kbvx86kBZXGHRHNCOC8:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/3185b43411363d83692fd19d73cf48915120688d/docs/user-guide/containers.md#L7)):*
<details><summary><i>Previously, chenopis (Andrew Chen) wrote…</i></summary><blockquote>

Please rename file to user-guide-content-moved.md
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/2386)*

**Comment by steveperry-53** [comment]
@chenopis, Can you figure out how to resolve the Reviewable thing? This is stopping me from merging this PR.

**Comment by chenopis** [comment]
@steveperry-53 Sorry, I won't use that in the future.

**Pull request merged**
