### PR TITLE
reorganization

### PR DESCRIPTION
**Pull request by jessfraz**
This does a few things:
- cleans up indenting to make HTML templates more readable
- create a "basic" template to use for case-studies, index, partners, community
  to help with not repeating self and re-using header and footer components
- inline styles for case-studies pages are now a stylesheet loaded specifically
  for those
- separate head-header.html into head.html and header.html so the opening body
  tag is not oblivious to the template
- move google analytics scripts to footer-scripts.html so it can be used
  globally

So overall mostly this is trying to make it so the community, case-studies, index, and partners page don't all use different templates defined by that page, some were even missing specific things like analytics scripts because they were doing their own thing. This makes it so they use the "basic" template I made to make sure all the header and footer elements are used globally.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1450)

### CODE REVIEW

**Comment by jessfraz** [comment]
no rush on this, I mostly just couldn't unsee, and it was going to drive my OCD crazy

**Comment by devin-donnelly** [comment]
Hey @jessfraz , the community and partners pages got rearranged out from under us a little bit, which caused some merge conflicts in this PR. Can you check it out?

**Comment by jaredbhatti** [comment]
@jessfraz can you resolve the conflicts here?

**Comment by jessfraz** [comment]
Going to close and reopen as some smaller PRs

**Comment by jessfraz** [comment]
ping @jaredbhatti rebased

**Comment by jessfraz** [comment]
i have no idea why netlify failed it works locally for me

**Comment by jessfraz** [comment]
@jaredbhatti I split this into different commits so you could see everything that changed and how this will be much more maintainable now.

**Comment by devin-donnelly** [comment]
@jessfraz What's the status on this? Feel free to ping me directly, but there are still some merge conflicts here.

**Comment by jessfraz** [comment]
Ah sorry they might have happened right after... I'll rebase again

**Comment by jaredbhatti** [comment]
Huh, can you try resolving the conflicts that popped up?

**Comment by jessfraz** [comment]
rebased, ping @devin-donnelly @jaredbhatti :)

**Comment by jaredbhatti** [comment]
Thanks for all your work on this!

**Pull request merged**
