### PR TITLE
Fixed a tiny typo

### PR DESCRIPTION
**Pull request by r4j4h**
Kubernets -> Kubernetes

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2467)

### CODE REVIEW

**Comment by r4j4h** [comment]
I signed it!

**Comment by chenopis** [comment]
@r4j4h The CLA check is still failing. Can you check to see if you signed the CLA w/ the same email address as is associated w/ your GitHub account? Thx

**Comment by r4j4h** [comment]
I signed it!

Sorry about that I have multiple emails attached to this GitHub and used the wrong one, should be good to go now.

**Comment by Crassirostris** [comment]
@r4j4h LGTM, thanks a lot for your contribution!

@steveperry-53 could you please merge?

**Comment by chenopis** [comment]
Thanks @r4j4h and @Crassirostris !

**Pull request merged**
