### PR TITLE
Removed _italics_ from top-level docs titles

### PR DESCRIPTION
**Pull request by ElijahCaine**
The italics formatting (like `_Daemon Set_`) in the top-level of the docs do not render correctly on kubernetes.io/docs.
This pull request corrects that problem.

cc @erictune, @sttts, @soltysh, @janetkuo, @bgrant0607, @janetkuo, @pweil-, @Kashomon, @bprashanth, @madhusudancs. I touched your docs ❤️ 

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1982)

### CODE REVIEW

**Comment by ElijahCaine** [comment]
I signed it!

**Comment by bprashanth** [comment]
Oh, oddly no one noticed. Thanks!

**Comment by soltysh** [comment]
@ElijahCaine LGTM.
On a side note, it would be nice to have all resource names in the titles be Title Case, wdyt? Can be here or as a followup.

**Comment by ElijahCaine** [comment]
@soltysh Can you elaborate on that or give me an example? I'd be happy to update this PR to include that change, I just want to make sure I don't do it wrong.

**Comment by soltysh** [comment]
@ElijahCaine look through your changes, Daemon Set, Cron Job, Systctl are all title case, but job, pod, replication controller are all small case. It would be nice to those aligned, iow. all title case.

**Comment by ElijahCaine** [comment]
@soltysh In going through this I think it'd be best to just create a second PR that corrects the CamelCase inconsistency in the docs. If you're okay with waiting a bit I'll create a second PR and we'll merge this one now. If you think it'd be best to keep this PR and tack on the changes I'm making we can do that too.

**Comment by ElijahCaine** [comment]
@soltysh I made the changes you requested. I also went ahead and changed *some* of them to be ConsistentlyFormatted throughout the document. I didn't do it for some because I was unsure it was the correct thing to do. let me know what other edits you'd like and I'll get those done ASAP.

Thank you so much for the feedback.

**Comment by devin-donnelly** [comment]
@ElijahCaine , this has a bunch of merge conflicts that need to be resolved before I can move on it.

**Comment by ElijahCaine** [comment]
@devin-donnelly Fixed the merge conflicts and squashed my commits. Let me know if we can merge this now.

**Pull request merged**
