### PR TITLE
Updated latest Kubernetes version to variable

### PR DESCRIPTION
**Pull request by idvoretskyi**
Added method to set a Kubernetes variable to the latest actual version.

Updated command with added variable.

### CODE REVIEW

**Comment by luxas** [comment]
`docker.md` is extremely old, is it by design that you have `release-1.1` docs? 

@johndmulhausen You really should update to `release-1.2` for this new site. `docker.md` has changed a lot and this isn't by far enough to fix that. For comparison, see the latest version: https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/getting-started-guides/docker.md

**Comment by johndmulhausen** [comment]
getting-started-guides/ now has its 1.2 changes. Are you sure this PR is necessary?

Please do not submit PRs or bugs relating to missing 1.2 changes until the docs freeze has ended per an announcement on kubernetes-dev. See this announcement for more information:
https://groups.google.com/forum/#!topic/kubernetes-dev/UedwIYb-fHg

**Comment by idvoretskyi** [comment]
@johndmulhausen I suppose, this PR is still useful for users with 1.1.* version.

Anyway, I'll take a look at 1.2 docs for the similar improvements.

Thank you.

**Comment by johndmulhausen** [comment]
If the info here is useful for 1.1 docs only, then open a new PR against the release-1.1 branch. Since this seems to be an inactive/obsolete PR that now has merge conflicts, closing for now.

**Comment by idvoretskyi** [comment]
Outdated doc.

**Pull request closed without merging**
