### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
Change "state" to "states". rc's replicas may have different states.

> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2971)

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
But I think it can only one current state. Am I missing something? I'm not a native speaker, but maybe @DirectXMan12 can help here.

**Comment by chenopis** [comment]
My suggestion for that sentence would be: "Scale is an interface that allows you to dynamically set the number of replicas and examine each of their current states."

**Comment by zhangxiaoyu-zidif** [comment]
@fgrzadkowski There is one state of rc's replicas in the final showing of kubectl-cli.

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif @fgrzadkowski Does Scale actually let you examine each replica or just the overall set? If the latter, then the sentence should be: "Scale is an interface that allows you to dynamically set the number of replicas and examine the current state of the replica set."

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis I will do some tests and then give you feadback.

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif Ok, great. Thanks!

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis @fgrzadkowski  I did some checks about "scale" of rc. 
The result is:
I think "states" may be better. The analysis is below:
The replicas scaling by rc share one state group with label "status" in output file of rc by command "kubectl get rc <rc's name> -o json > <output file>".
The state group contains "replicas", "fullyLabeledReplicas", "readyReplicas", and "observedGeneration".
replicas is a parameter that can be set. The others are the examined informations.
Hope it is convinced.

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif Ok, in that case, I agree. Let's go w/ the current version. Thanks for doing the research! =)

**Pull request merged**
