### PR TITLE
Fixed apostrophe

### PR DESCRIPTION
**Pull request by cliffburdick**
> NOTE: Please check the “Allow edits from maintainers” box (see image below) to  
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4586)

### CODE REVIEW

**Comment by cliffburdick** [comment]
@vishh I'm not sure what else I can do about the CLA. I made a new account through my company and the emails match everywhere. However, I'm not getting an email to sign the document.

**Comment by chenopis** [comment]
@cliffburdick One other thing you can try is to [login into the Linux Foundation](https://identity.linuxfoundation.org/?destination=node/285/individual-signup) using your GitHub account.

Click on *Login with GitHub*.
screen shot 2017-08-02 at 2 39 26 pm

You should see this form:
screen shot 2017-08-02 at 2 39 10 pm

**Comment by cliffburdick** [comment]
Hi @chenopis, when I log in to that site I don't get that screen you do. When I log in all I see is:
image

**Comment by cliffburdick** [comment]
@chenopis it looks good now. All signed and ready to go I think. The email was just delayed.

**Pull request merged**
