### PR TITLE
Change title of ZooKeeper tutorial

### PR DESCRIPTION
**Pull request by ahmetb**
"CP" in the title of this tutorial is not explained anywhere and is not
relevant to the tutorial.

/assign @enisoc

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3851)

### CODE REVIEW

**Comment by enisoc** [comment]
@kow3ns is the one who wrote this. Let's see what he thinks. :)

/assign @kow3ns

**Comment by ahmetb** [comment]
@kow3ns 

> The CP is relevant, and the intended audience will likely know what it means in this context.

I don't think the assumption of the knowledge of the CAP theorem for Kubernetes beginners following the tutorials is correct. I think we need to explain the CP concept and its relevance to the tutorial in this case.

ZooKeeper is probably different things to different people, but I can’t see how the CP property of ZK is applied or exercised in the tutorial, therefore I claimed that it is not relevant.

> Also the title you propose is wrong. ZooKeeper is not a key,value store,

Do you mind explaining why ZK is not a kv store? From https://en.wikipedia.org/wiki/Apache_ZooKeeper, I read: "It is essentially a distributed hierarchical key-value store." While it’s not intended to be Cassandra-like, technically the term is correct although it might not be the most explanatory way to describe ZK. 

I'm open to changes, but I think the current title is not helping anyone. We can use "Zookeeper, a Distributed Synchronization Service", would it be better?

**Comment by kow3ns** [comment]
1. Please take a look at the [documentation] (https://zookeeper.apache.org/doc/r3.4.10/zookeeperOver.html#ch_DesignOverview) for a concise explanation of what ZooKeeper is and what's its intended use cases are. 
1. I'd be fine with updating the tutorial to explain what CP means in this context.
1. I'd also be fine with updating the title to just say ZooKeeper, even though the scope was a little larger than that.
1. I think that if someone is attempting to deploy a distributed system, coordination service on Kubernetes they are, a priori, not a beginner. The are attempting to deploy a distributed system that is complex enough to require another distributed system to coordinate itself.

**Comment by ahmetb** [comment]
@kow3ns (2) sounds great. Do you mind adding a brief paragraph or section about this?

**Comment by chenopis** [comment]
@ahmetb @kow3ns So, what do we want to do w/ this PR then?

**Comment by ahmetb** [comment]
@chenopis we can close (or keep this as an open issue) to track the work proposed above.

**Comment by chenopis** [comment]
@ahmetb Ok, I'm going to close this for now. Can you open an Issue for this and assign me? Thx

**Pull request closed without merging**
