### PR TITLE
Added solution Madcore.Ai

### PR DESCRIPTION
**Pull request by styk-tv**
Adding new free tool Madcore CLI tool to deploy Kubernetes infrastructure in AWS. Focused on devops using Jenkins DSL and has many ready to use Jobs that interact directly with K8S.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3336)

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
bump the CLA check

**Comment by styk-tv** [comment]
@brendandburns i've been trying to decipher travis complaint as to to build failure latest

Full log https://s3.amazonaws.com/archive.travis-ci.org/jobs/221244047/log.txt
Based on build https://travis-ci.org/kubernetes/kubernetes.github.io/builds/221244046

```
# golang.org/x/net/http2
../../golang.org/x/net/http2/writesched_priority.go:58: undefined: WriteScheduler
../../golang.org/x/net/http2/writesched_priority.go:254: undefined: writeQueuePool
# k8s.io/apimachinery/pkg/runtime/schema
../apimachinery/pkg/runtime/schema/generated.pb.go:44: undefined: proto.GoGoProtoPackageIsVersion2
../apimachinery/pkg/runtime/schema/generated.pb.go:47: undefined: proto.RegisterFile
# k8s.io/apimachinery/pkg/util/intstr
../apimachinery/pkg/util/intstr/generated.pb.go:47: undefined: proto.GoGoProtoPackageIsVersion2
../apimachinery/pkg/util/intstr/generated.pb.go:357: undefined: proto.RegisterFile
# k8s.io/apimachinery/pkg/api/resource
../apimachinery/pkg/api/resource/generated.pb.go:45: undefined: proto.GoGoProtoPackageIsVersion2
../apimachinery/pkg/api/resource/generated.pb.go:56: undefined: proto.RegisterFile
FAIL	k8s.io/kubernetes.github.io/test [build failed]
```

Any hints as to what's causing it to fail? Doesn't look like anything I've caused with 3 lines of text added but might be wrong on that. Please double check when you have a sec.

**Comment by styk-tv** [comment]
Seems above went away with last update from master. Good to go.

**Comment by chenopis** [comment]
@styk-tv FYI, the Travis check was failing because of changes that happened to upstream repositories we are dependent on. You're changes look good. /lgtm

**Comment by styk-tv** [comment]
thanks for the FYI @chenopis

**Comment by chenopis** [comment]
no prob :)

**Pull request merged**
