### PR TITLE
Move update-demo and liveness images to kubernetes/test/images

### PR DESCRIPTION
**Pull request by mkumatag**
Part of https://github.com/kubernetes/kubernetes/pull/49196 already kitten, nautilus and liveness images are moved to https://github.com/kubernetes/kubernetes/tree/master/test/images, hence this PR is to remove content from here and add redirect note.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4536)

### CODE REVIEW

**Comment by luxas** [comment]
LGTM, but you have to more all references to it as well:
```
$ ./verify-docs-format.sh
Error: docs/user-guide/liveness/image/README.md doesn't have an entry in the table of contents under _data/*.yml
Error: docs/user-guide/liveness/image/README.md doesn't have a proper title defined!
Error: docs/user-guide/update-demo/images/kitten/README.md doesn't have an entry in the table of contents under _data/*.yml
Error: docs/user-guide/update-demo/images/kitten/README.md doesn't have a proper title defined!
Error: docs/user-guide/update-demo/images/nautilus/README.md doesn't have an entry in the table of contents under _data/*.yml
Error: docs/user-guide/update-demo/images/nautilus/README.md doesn't have a proper title defined!
Found 3 files without entries. For how to fix it, see http://kubernetes.io/docs/home/contribute/write-new-topic/#creating-an-entry-in-the-table-of-contents
```
Thanks for adding the redirect link!

cc @ixdy for approval after fixing that up

**Comment by chenopis** [comment]
@mkumatag Since they are README.md files, you can add those 3 files to `/skip_toc_check.txt` and `/skip_title_check.txt`. That will solve the Travis check failure.

**Comment by mkumatag** [comment]
Thanks @chenopis , I've added the README.md files to `/skip_toc_check.txt` and `/skip_title_check.txt`. Now travis run should pass.

**Pull request merged**
