### PR TITLE
Fixed doc typo

### PR DESCRIPTION
**Pull request by gregoplex**
s/Pob/Pod/

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2277)

### CODE REVIEW

**Comment by gregoplex** [comment]
signed CLA!

**Comment by janetkuo** [comment]
@pwittrock are these docs auto-generated?

**Comment by pwittrock** [comment]
Yikes.  Yeah these are generated in https://github.com/kubernetes-incubator/reference-docs

**Comment by gregoplex** [comment]
makes since, typo is there too. =]

**Comment by pwittrock** [comment]
@gregoplex Would you mind updating that source and I will regenerate the docs?

**Comment by pwittrock** [comment]
Here https://github.com/kubernetes-incubator/reference-docs/blob/4fddb44e00244a35861b14e7a856b78c3052cb8c/gen_open_api/examples/pod/pod.yaml

**Comment by pwittrock** [comment]
Or I can update it, wasn't sure if you wanted your name attached to the commit.

**Comment by gregoplex** [comment]
Whatever is easier, just trying to help. @pwittrock Created a pr https://github.com/kubernetes-incubator/reference-docs/pull/6

**Comment by pwittrock** [comment]
@gregoplex Thanks!  Finding these sorts of issues and fixing them is a big help :)

**Pull request merged**
