### PR TITLE
Missing a single quote in Rolling Update command

### PR DESCRIPTION
**Pull request by goutamtadi1**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5444)

### CODE REVIEW

**Comment by goutamtadi1** [comment]
Updated my company email address. Please re-verify.

**Comment by xiangpengzhao** [comment]
@k8s-ci-robot bot, verify @goutamtadi1 CLA please

**Comment by xiangpengzhao** [comment]
@goutamtadi1 seems like there is still issue with your CLA, please check it. (BTW, if the CLA is OK, bot can detect it after a new comment, see: https://github.com/kubernetes/kubernetes.github.io/pull/5433#issuecomment-329340137)

**Comment by goutamtadi1** [comment]
@k8s-ci-robot bot, verify @goutamtadi1 CLA please

**Comment by xiangpengzhao** [comment]
Cool!

/lgtm

**Pull request merged**
