### PR TITLE
Add alternative way to install kubectl

### PR DESCRIPTION
**Pull request by FuriKuri**
Hi,

I've added an alternative way to install kubectl for homebrew users. With homebrew it's a little bit easier to install and keep kubectl up to date.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1399)

### CODE REVIEW

**Comment by FuriKuri** [comment]
I signed it!

**Comment by bgrant0607** [comment]
@FuriKuri What release of kubectl does homebrew install?

Right now, we strongly recommend that the release of kubectl match the release of the K8s cluster. How would homebrew allow them to be kept in sync?

cc @kubernetes/kubectl

**Comment by FuriKuri** [comment]
The current version, which homebrew will install, is v1.3.7.

To my knowledge, it's necessary to create a pull request to the homebrew-core repository, to update the version of a formula. So homebrew depends on PR from the community.

**Comment by AdoHe** [comment]
Personally I like the homebrew installation way, but I worry about how we can keep in sync.

**Comment by fabianofranz** [comment]
Yeah, I understand the convenience that `brew` adds for Mac users but I don't think we should explicitly promote it in our guides, unless we decide to officially maintain it (not the case currently AFAIK).

https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubernetes-cli.rb

**Comment by AdoHe** [comment]
Yeah, consider we will not officially maintain it as for now, no need to explicitly promote it in our user guides.

**Comment by devin-donnelly** [comment]
Should this PR be closed then?

**Comment by fabianofranz** [comment]
> Should this PR be closed then?

Yes, anyway thanks @FuriKuri!

**Comment by pwittrock** [comment]
FYI there is a discussion about mentioning brew install in a more comprehensive kubectl install guide here:

https://github.com/kubernetes/kubernetes.github.io/pull/1508#issuecomment-255497615

**Comment by jaredbhatti** [comment]
Closing this pull request per the discussion.

**Pull request closed without merging**
