### PR TITLE
Added require('http'); in sample

### PR DESCRIPTION
**Pull request by ctrath**
http.createServer doesn't work because 'http' isn't initialized:

var http = require('http');

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2104)

### CODE REVIEW

**Comment by jaredbhatti** [comment]
Can you sign the CLA, please? :)

**Comment by ctrath** [comment]
I signed it!

**Comment by chenopis** [comment]
@ctrath looks like there is a conflict that needs to be resolved before we can merge the PR.

**Comment by chenopis** [comment]
Looks like the conflict was the same fix in another PR so I'm closing this.

**Pull request closed without merging**
