### PR TITLE
fix command

### PR DESCRIPTION
**Pull request by zs1379**
fix command and sign cla

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4242)

### CODE REVIEW

**Comment by zs1379** [comment]
why the cla still not sign.....

**Comment by chenopis** [comment]
@zs1379 Did you sign the CLA from the email they sent after you registered on the Linux Foundation CNCF site?

**Comment by zs1379** [comment]
check again...

**Comment by chenopis** [comment]
@zs1379 I'm still not seeing it.

**Pull request closed without merging**
