### PR TITLE
Update scheduling-gpus.md

### PR DESCRIPTION
**Pull request by shaklee3**
Fixed apostrophe.

> NOTE: Please check the “Allow edits from maintainers” box (see image below) to  
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4580)

### CODE REVIEW

**Comment by shaklee3** [comment]
Signed CLA

**Comment by chenopis** [comment]
@shaklee3 Which path did you follow in the CLA signing? If it was individual, there might be an email w/ a link to a doc that you'll need to eSign.

**Comment by shaklee3** [comment]
Hi @chenopis , I followed the instructions here by creating a new individual account:

https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ

I clicked the activate link in my email, and I don't see any follow-up email with where to sign. I followed up by creating an account on Hellosign per the instructions, but it says there are no documents available. Should I create a new account from my company email and re-do the pull request?

**Comment by chenopis** [comment]
@shaklee3 The emails have to match -- the one used in the GitHub commit and the one used to sign the CLA. Here are a couple of links that might help:

https://help.github.com/articles/setting-your-email-in-git/
http://stackoverflow.com/questions/2919878/git-rewrite-previous-commit-usernames-and-emails

If everything is setup correctly, you can also just try closing this PR and opening a new one.

**Comment by cliffburdick** [comment]
@chenopis I will open a new PR. Thanks

**Pull request closed without merging**
