### PR TITLE
Update max number of Nodes

### PR DESCRIPTION
**Pull request by gmarek**
cc @wojtek-t

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1137)

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by jaredbhatti** [comment]
Can you rebase?  Then we can merge.

**Comment by devin-donnelly** [comment]
Is this change for version 1.4, or can it go out now?

**Comment by gmarek** [comment]
This can go out now - it should have been done for 1.3, but we missed it in this doc. Sorry.

**Comment by devin-donnelly** [comment]
Okay, great. Thanks. I'll merge it now.

**Pull request merged**
