### PR TITLE
Updating DC/OS getting started guide with the new integration.

### PR DESCRIPTION
**Pull request by smugcloud**
Updating DC/OS getting started guide with the new integration from Mesosphere.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5547)

### CODE REVIEW

**Comment by smugcloud** [comment]
Testing the GitHub-->Linux foundation syncing for CLA.

**Comment by smugcloud** [comment]
Testing one more time to get CLA synced.

**Comment by smugcloud** [comment]
Hi @chenopis,

Do you have any feedback on this?

**Comment by zacharysarah** [comment]
@smugcloud :wave: Please resolve the merge conflicts on this branch. Thanks!

**Comment by smugcloud** [comment]
Thanks @zacharysarah.  Merge conflicts resolved.

**Pull request merged**
