### PR TITLE
fixes for 2293 and 2361

### PR DESCRIPTION
**Pull request by CreaturesInUnitards**
[2361](https://github.com/kubernetes/kubernetes.github.io/issues/2361)
added #b3b3b3 border to search field

[2293](https://github.com/kubernetes/kubernetes.github.io/issues/2293)
removed last 3 "oceanNodes"
swapped out homepage video banner image

_**Also...**_
**_base.sass**: fixed 2 loose commas
**index.html**: deleted dead vendorStrip code

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2433)

### CODE REVIEW

**Comment by CreaturesInUnitards** [comment]
I signed it!

**Comment by chenopis** [comment]
@CreaturesInUnitards Can you make sure you signed the CLA using the same email address as is associated with your GitHub account? Thx

**Comment by jaredbhatti** [comment]
Weird. Still waiting on you to sign the CLA.  It's different from the google CLA you signed originally.  Can you verify that it's signed?

**Comment by CreaturesInUnitards** [comment]
Ok signed it again — apparently my profile update didn't take the first time :/

**Comment by chenopis** [comment]
@CreaturesInUnitards Thanks for signing the CLA.

The preview for the main page looks off. Removing the 3 "oceanNodes" but leaving the video leaves a strange blank space in the middle of the page.

**Comment by chenopis** [comment]
Not sure why the CLA is no longer valid.

**Comment by chenopis** [comment]
@CreaturesInUnitards Should I just close this for now until we can decide how to refactor the home page?

**Comment by CreaturesInUnitards** [comment]
@chenopis I'm no longer with United Creations, and therefore no longer on this project. If Bob Hrdinsky is still leading the marketing effort, I'd probably run it by him.

**Comment by chenopis** [comment]
@CreaturesInUnitards Ok, thanks for letting me know. I'm going to have to close this PR for now then.

**Pull request closed without merging**
