### PR TITLE
Create ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by a-mccarthy**
Created issue temple.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1229)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
Thanks! Can you sign the CLA so I can merge?

**Comment by a-mccarthy** [comment]
@googlebot I signed it!

I should be a part of the Apprenda, Inc CLA.

**Comment by a-mccarthy** [comment]
@devin-donnelly, sorry for the delay here. I have having a problem with the CLA. I should be covered by company signed CLA for Apprenda, but it doesn't look like I am being recognized.  I have been trying to troubleshoot the problem, but i'm not sure what's wrong. Any ideas on what the issue could be?

**Comment by devin-donnelly** [comment]
I'm honestly not sure. Let me look into it.

**Comment by jeffmendoza** [comment]
Here it the git log:

```
commit 8cd4a087a1a6b033f4d2bd05f40530a1f98d5aa2
Author: a-mccarthy <a-mccarthy@users.noreply.github.com>
Date:   Wed Sep 14 16:34:06 2016 -0400

    Create ISSUE_TEMPLATE.md
    
    Created issue temple.

```

In your github setting there is a setting for whether to use an email for on-website edits or a noreply email. You'll need to change that to use your email, and set your Apprenda email as "Primary".

Alternatively you could use the git cli, set your git config user.email to your Apprenda email, and git commit --amend --reset-author on your branch and force push it back up

**Comment by a-mccarthy** [comment]
I was able to create this under a new PR with a CLA.  PR:#1274 https://github.com/kubernetes/kubernetes.github.io/pull/1274

Thank you, @jeffmendoza for all the help :)

**Pull request closed without merging**
