### PR TITLE
Get rid of git dependency in kubeadm guide

### PR DESCRIPTION
**Pull request by errordeveloper**
cc @lukemarsden

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1518)

### CODE REVIEW

**Comment by lukemarsden** [comment]
Is this guaranteed to install the namespace first?

**Comment by errordeveloper** [comment]
> Is this guaranteed to install the namespace first?

Yes, as it's done with an explicit `kubectl create namespace sock-shop` command.

**Comment by errordeveloper** [comment]
Why this is not assigned to anyone? // cc @kubernetes/sig-cluster-lifecycle

**Comment by luxas** [comment]
@errordeveloper This kubeadm doc doesn't have any assignees, only the kubeadm ref doc has it because I added it there earlier

This LGTM

**Pull request merged**
