### PR TITLE
Remove comma

### PR DESCRIPTION
**Pull request by FengyunPan**
Fix error: no matches for /, Kind=Service,

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4013)

### CODE REVIEW

**Comment by bprashanth** [comment]
this LGTM, think you need a rebase

**Comment by FengyunPan** [comment]
@bprashanth OK

**Comment by chenopis** [comment]
Addressed by PR #4036

**Comment by FengyunPan** [comment]
@chenopis Sorry,I have a issue. Why not merge my pr firstly?

**Comment by chenopis** [comment]
@FengyunPan Yes, I should have merged your PR first and closed the other one. Sorry about that.

**Pull request closed without merging**
