### PR TITLE
Premises, not premise!!

### PR DESCRIPTION
**Pull request by StevenWColby**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.7 Features: set Milestone to `1.7` and Base Branch to `release-1.7`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3730)

### CODE REVIEW

**Comment by chenopis** [comment]
@StevenWColby Thanks for catching these. When you get a chance, can you sign the CLA? I can then merge this PR. Thx

**Comment by chenopis** [comment]
@StevenWColby Are you have any trouble signing the CLA?

**Comment by StevenWColby** [comment]
@chenopis Hi Andrew - oops, I kinda forgot about it.  Sorry, trying to get a product release out at work.  This PR is kinda old now - let's crush it and I'll fixup the spelling starting with a new HEAD commit.

**Comment by chenopis** [comment]
@StevenWColby Ok, no worries!

**Pull request closed without merging**
