### PR TITLE
Added `--register-with-taints` for node.md.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed part of #2737

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2768)

### CODE REVIEW

**Comment by aveshagarwal** [comment]
FYI: @mburke5678

**Comment by mburke5678** [comment]
LGTM

**Comment by gyliu513** [comment]
This is target for 1.6, can we have this merged soon? @aveshagarwal @mburke5678 @dchen1107

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
