### PR TITLE
Use in-page titles to generate sidebar nav

### PR DESCRIPTION
**Pull request by benbalter**
A follow up to and based on https://github.com/kubernetes/kubernetes.github.io/pull/1976, this updates the tables of contents to only list the *path* to the referenced file, and at build time, Jekyll will pull the title for the sidebar navigation entry from the page itself.

That way, each page can contain its own title, and will have its title and build time (where other plugins can expected it), and there's no risk of them getting out of sync with the table of contents. The behavior for external links (and resulting output) is unchanged.

Previously, we were rendering the `tree.html` include nearly 400 times. Since the lookup for the Page title is more expensive than iterating through the table of contents, this became considerably slower. To counteract this, I create a quick [partial caching plugin](https://github.com/benbalter/jekyll-include-cache), which means this PR actually builds slightly *faster* than master (by rendering the tree 8 times, instead of 400).

You can build this branch locally with the following command `DISABLE_WHITELISET=1 bundle exec jekyll serve`.

If the maintainers like this approach, I can go ahead and get the caching plugin whitelisted so you can use it on GitHub Pages without any further maintenance or upkeep (which would need to be done before this PR could be merged).

/cc @jessfraz

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1994)

### CODE REVIEW

**Comment by janetkuo** [comment]
@benbalter Thanks! This needs a rebase

**Comment by janetkuo** [comment]
Not sure why netlify build failed

**Comment by jessfraz** [comment]
```
 Liquid Exception: Liquid syntax error (line 41): Unknown tag 'include_cached' in /_layouts/docwithnav.html
jekyll 3.3.1 | Error:  Liquid syntax error (line 41): Unknown tag 'include_cached'
```

**Comment by benbalter** [comment]
@janetkuo @jessfraz Instructed Netifly to temporarily disable the plugin whitelist via 22f31bd so that the preview should build. As alluded to in the OP, if everyone is 👍 with this approach, I'll get the plugin added to GitHub Pages, making this additional complexity unecessary.

**Comment by jessfraz** [comment]
This LGTM thanks!

**Comment by jessfraz** [comment]
I will wait to merge til you say it's safe

**Comment by benbalter** [comment]
Working on whitelisting via https://github.com/github/pages-gem/issues/373.

**Comment by benbalter** [comment]
Okay! Via github/pages-gem#373, Jekyll-Include-Cache has been whitelisted and should work automatically, locally, in staging, and on GitHub Pages.

To be explicit, in terms of maintenance going forward (to continue to build the sidebar nav):

1. Page titles should be stored in the page's YAML front matter (e.g., `title: foo`). This PR (which if merged, should close https://github.com/kubernetes/kubernetes.github.io/pull/1976), moves the titles from the existing Table of contents to each page's YAML front matter, with no substantive changes (I used a quick script).

2. To control the sidebar nav hierarchy, the existing files in `_data` are still used, just as before. The  only change, is for links to in-site pages, you just need to add the path to the page, rather than a has with the title and URL. For external links, you continue to use the title and path, just as before.

The advantage here, is that since we're keeping the title in the page, rather than in a separate data file, we have a philosophical separation of concerns (e.g., the page now knows its title), but more practically, things like the title meta tag should be properly set, other plugins won't get confused by the lack of in-page title, etc. 

To support this, and keep the build time under a minute, I added a new Jekyll-Include-Cache plugin, which means we only build the sidebar nav once per section, rather than 300+ times as we were before.

**Comment by jessfraz** [comment]
Thanks so much!! Seriously this is beyond valuable

**Comment by benbalter** [comment]
I might submit a follow up PR to clean up some of the whitespace, but clicked around the live site, and everything looks ✨ . Feel free to @mention me on any issues if you're experience any pain/frustration/whatever in terms of Jekyll/GitHub Pages and glad to take a pass.

**Pull request merged**
