### PR TITLE
Add Nuage Networks as networking solution

### PR DESCRIPTION
**Pull request by hasahni**
Nuage Networks provides policy-based networking for Kubernetes. The github page for the Kubernetes integration artefacts is located here https://github.com/nuagenetworks/nuage-kubernetes

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1299)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
LGTM. Once the CLA is working, I'll merge.

**Comment by devin-donnelly** [comment]
Still waiting on a rebase and a CLA sign.

**Comment by hasahni** [comment]
Waiting for google bot to be replaced by CNCF bot for Kubernetes.

**Comment by jaredbhatti** [comment]
Can you please sign the CLA?

**Comment by jaredbhatti** [comment]
@hasahni  Please sign the CLA.

**Comment by caseydavenport** [comment]
Once this is rebased, please make sure that the list is still alphabetically sorted!

**Pull request closed without merging**
