### PR TITLE
Update the references to federation control plane images/binaries in the federation admin guide.

### PR DESCRIPTION
**Pull request by madhusudancs**

### CODE REVIEW

**Comment by nikhiljindal** [comment]
thanks, LGTM.
Not sure if master is the right branch to change or is there a 1.4 branch.

Maybe @pwittrock knows?

**Comment by pwittrock** [comment]
@jaredbhatti Where should 1.4 docs go?

**Comment by jaredbhatti** [comment]
We should start a 1.4 branch.

**Comment by madhusudancs** [comment]
@jaredbhatti Should I send a new PR (with the changes here) targetting the 1.4 branch?

**Comment by pwittrock** [comment]
@madhusudancs If this is for a feature being developed for 1.4, the PR should go to the 1.4 branch.

**Comment by madhusudancs** [comment]
@pwittrock Sure, thanks.

Superseded by #945. Closing this PR.

**Pull request closed without merging**
