### PR TITLE
Can't pass endpoint in glusterfs StorageClass

### PR DESCRIPTION
**Pull request by gnufied**
As evidence from https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/glusterfs/glusterfs.go#L676 . We can no longer pass endpoint option in this class. 

cc @rootfs  @humblec

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1751)

### CODE REVIEW

**Comment by saad-ali** [comment]
@rootfs @jsafrane @kubernetes/sig-storage Is this a regression? Can we get this triaged ASAP as a blocker or not for the 1.5 release?

**Comment by rootfs** [comment]
in 1.5 endpoint is generated rather than passed. This is documented in doc
https://github.com/kubernetes/kubernetes/tree/master/examples/experimental/persistent-volume-provisioning#glusterfs

**Comment by devin-donnelly** [comment]
If this update is not relevant until 1.5 is released, please retarget this PR to the release-1.5 branch.

**Comment by rootfs** [comment]
@devin-donnelly yes, it should target 1.5

**Comment by gnufied** [comment]
@devin-donnelly yes, this is not relevant until 1.5. We should document the process by which these doc changes are targeted. For example - is current docs available at kubernetes.io are from release-1.4 branch here or are from master?

**Comment by gnufied** [comment]
Closing this pull request in favor of https://github.com/kubernetes/kubernetes.github.io/pull/1753 which targets `release-1.5` branch.

**Comment by devin-donnelly** [comment]
@gnufied, see the current [contributor guide](http://kubernetes.io/docs/contribute/create-pull-request/).

Because kubernetes.io is served via GitHub pages, any changes merged to master go live IMMEDIATELY. GitHub Pages prevents you from serving out of any branch besides "master" or "gh-pages", so none of the release branches are actually published. They are staged elsewhere via Netlify.

**Pull request closed without merging**
