### PR TITLE
Add playgrounds to Task and Tutorial prerequisites.

### PR DESCRIPTION
**Pull request by steveperry-53**
Addresses https://github.com/kubernetes/kubernetes.github.io/issues/4252

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4550)

### CODE REVIEW

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 53b8d8f667707e59f96590c3f91ef8d15ef93d87

https://deploy-preview-4550--kubernetes-io-master-staging.netlify.com

**Comment by steveperry-53** [comment]
attn: @BenHall @marcosnils

**Comment by BenHall** [comment]
Thank you, LGTM

**Comment by chenopis** [comment]
closes #4252

**Pull request merged**
