### PR TITLE
Replace docker-machine's "env" command with "ip"

### PR DESCRIPTION
**Pull request by damselem**
The "ip" command simply returns the IP address of the Docker Machine.

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Docs LGTM but you need to sign the CLA @damselem

**Comment by damselem** [comment]
Just registered my account as a Googler. In this case I don't think I have
to sign it right?

**Comment by johndmulhausen** [comment]
Not sure; it might be good to hit the URL just in case. 
Of course now, there are merge conflicts. So you need to handle those. :(

**Comment by johndmulhausen** [comment]
If it gets to be too much of a pain to handle the merge conflict, let me know and we can close the PR and do a new one with a properly based fork. Since it's a minor change that might be easier.

**Comment by damselem** [comment]
Yes, let's close this PR and I'll open a new one. This time I might be able to avoid signing the CLA, we'll see...

**Pull request closed without merging**
