### PR TITLE
Make job page findable by search engines and shortcuts

### PR DESCRIPTION
**Pull request by craig-day**
Couldn't find this page by googling for "Job" or by searching around on other pages.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2990)

### CODE REVIEW

**Comment by craig-day** [comment]
I signed it!

**Comment by chenopis** [comment]
@craig-day Is your git email set to the same one you used for the CLA?

**Comment by chenopis** [comment]
@steveperry-53 Should we add "job" to the title of finite workloads?

**Comment by chenopis** [comment]
Bump to see if the robot picked up the CLA.

**Comment by craig-day** [comment]
@chenopis yeah, verify my account at https://identity.linuxfoundation.org/user/me and it has the same github username and email address

**Comment by chenopis** [comment]
@craig-day I am unable to see your Linux Foundation profile, but under the "Social network logins" tab, have you tried adding GitHub as an Authentication provider?

screen shot 2017-04-17 at 1 04 46 pm

**Comment by steveperry-53** [comment]
@chenopis, I'm fine with whatever you and @craig-day work out here.

**Comment by chenopis** [comment]
@craig-day It's be retitled "[Jobs - Run to Completion](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/)". Will that suffice?

**Comment by craig-day** [comment]
perfect. Thanks!

**Comment by chenopis** [comment]
@craig-day Ok, cool. I'm going to close this PR then. Thx!

**Pull request closed without merging**
