### PR TITLE
Edited out dated Fedora Manual single node doc

### PR DESCRIPTION
**Pull request by surajssd**
Updated the out-dated Fedora Manual installation doc, updated information contains new ports of etcd as 2379, some edits in the document to make it more readable.

### CODE REVIEW

**Comment by surajssd** [comment]
I signed it!

**Comment by surajssd** [comment]
@johndmulhausen is this good to go?

**Comment by surajssd** [comment]
ping: @johndmulhausen

**Comment by johndmulhausen** [comment]
Strange that it isn't telling me what changed line by line but this LGTM.

**Comment by kelseyhightower** [comment]
@surajssd We are running into a bandwidth issue which has caused us to consider moving docs like this outside of the main documentation repo. The goal is to give documentation owners the ability to control the content for guides like this and simply link to them from here. 

I would like to propose the next step for this PR is to host a new running Kubernetes manually on Fedora doc on an external website or repo and allowing us to link to it from here. That would mean a new PR should be submitted that deletes this entire guide and replaces it with a single link to the outside document.

@surajssd Again thanks for taking the time to contribute, but I'm going to close this PR for the reasons stated above. If you would like to create the external guide and send a PR to link to it, I'd be happy to review it. Thanks.

**Pull request closed without merging**
