### PR TITLE
Fix broken links in api-reference docs

### PR DESCRIPTION
**Pull request by xiangpengzhao**
The links of `Schema` field in API operations pages are broken. They show a `404 Error` because of invalid relative path.

Check if the fix works:
http://xiangpengzhao.github.io/docs/api-reference/v1/operations/

This is my first pull request. I find that all the commits are included in this pull request. What should I do if I just want the last commit (7861127) to be pulled? Thanks! @johndmulhausen

### CODE REVIEW

**Comment by johndmulhausen** [comment]
There are a couple problems here:

1) We can't delete the CNAME file
2) Editing the contents of the home page to be this is a no-go: http://xiangpengzhao.github.io/

Unfortunately, to answer your question, pull requests always pull the entire difference between a fork and the origin. GitHub is based on a fork/merge model where all differences are being accounted for in a pull request. 

If you would like to narrow this down to just the reference files and their broken links, probably your best bet is to start over in a new fork. There are more unwanted changes than wanted changes so it would likely be easier than backing out each change you don't want. You can always keep your fork up to date with these instructions: https://help.github.com/articles/syncing-a-fork/

Let me know if you're going to retry with this fork. If you are going to start a new one I will close this PR.

**Comment by xiangpengzhao** [comment]
Thanks @johndmulhausen
I will start a new fork to push the useful changes. Please close this PR, thanks!

**Comment by bgrant0607** [comment]
@xiangpengzhao These files are auto-generated. We need to update the generator.

cc @caesarxuchao

**Comment by caesarxuchao** [comment]
The generator is updated in https://github.com/kubernetes/kubernetes/pull/25432.

Can this one be closed? I see the changes to the link are merged in #369.

**Comment by bgrant0607** [comment]
Thanks, @caesarxuchao

**Comment by xiangpengzhao** [comment]
Thanks, @caesarxuchao @bgrant0607

**Pull request closed without merging**
