### PR TITLE
Add description of protobuf and clarify versioning policy

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes kubernetes/kubernetes#8132 (for 1.3 branch)

### CODE REVIEW

**Comment by johndmulhausen** [comment]
We'll merge into the 1.3 branch at release time, so don't worry about doing things twice. :)

**Comment by smarterclayton** [comment]
Updated with the comments from #668

**Comment by johndmulhausen** [comment]
Thanks, @smarterclayton  :)

**Comment by wojtek-t** [comment]
@smarterclayton - thanks; lgtm

**Pull request merged**
