### PR TITLE
typo

### PR DESCRIPTION
**Pull request by keglevich3**

### CODE REVIEW

**Comment by jaredbhatti** [comment]
Docs LGTM.  Please accept the CLA so we can merge this with the k8s repo!

**Comment by keglevich3** [comment]
How do I accept the CLA?

2016-07-28 1:03 GMT+03:00 Jared <notifications@github.com>:

**Comment by keglevich3** [comment]
Done.

2016-07-28 8:53 GMT+03:00 צ'אק צ'אקי <keglevich2@gmail.com>:

**Comment by kelseyhightower** [comment]
CLA signed. Merging.

**Pull request merged**
