### PR TITLE
Describe the new podManagementPolicy for statefulsets

### PR DESCRIPTION
**Pull request by smarterclayton**
Documents https://github.com/kubernetes/features/issues/272

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4162)

### CODE REVIEW

**Comment by chenopis** [comment]
Moving this into the `release-v1.7` branch and tagging it w/ Milestone 1.7.

**Comment by chenopis** [comment]
@janetkuo Do you have a sec to take a quick look at this? It's only a couple paragraphs. Thx

**Comment by smarterclayton** [comment]
Or @kow3ns

**Comment by chenopis** [comment]
FYI, all feedback must be addressed and LGTMs given by EOD Tue, June 27th so that this can be merged for the 1.7 release on June 28th.

**Comment by chenopis** [comment]
@erictune You available to take a quick look at this? Thx

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-apps-pr-reviews

**Comment by kargakis** [comment]
lgtm but needs a rebase

**Comment by chenopis** [comment]
@smarterclayton Once you resolve the conflict, I will merge this. Thx

**Comment by smarterclayton** [comment]
I think this has been folded into @kow3ns #4174

**Pull request closed without merging**
