### PR TITLE
getting-started-guides: add CoreOS Tectonic

### PR DESCRIPTION
**Pull request by robszumski**
Adding Tectonic as a turn key solution. It kind of fits in multiple categories, but I think this is the best.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2605)

### CODE REVIEW

**Comment by robszumski** [comment]
Rebased/amended commit with correct email. CoreOS has signed the CLA.

**Comment by robszumski** [comment]
I signed it!

**Comment by chenopis** [comment]
@robszumski Please make sure you sign the CLA using the same email address as your GitHub account. That's the most common reason why the CLA check still fails. Thx

**Comment by robszumski** [comment]
@chenopis My commits should be signed with my @coreos.com email and this email is linked to by Github account. Does it need to be a "public email"?

**Comment by chenopis** [comment]
@robszumski Hmmm. That's strange then. No, it doesn't need to be a public email. Many of the contributors sponsored by their companies are coming through corp accounts.

**Comment by robszumski** [comment]
I will close/reopen and see if that helps. might not have liked my amend

**Comment by chenopis** [comment]
Ok, no problem. I'll check on the status of this again later.

**Pull request closed without merging**
