### PR TITLE
Cleanup deprecation-policy

### PR DESCRIPTION
**Pull request by xiangpengzhao**
`docs/deprecation-policy.md` has been moved to `/docs/home/deprecation-policy.md`. Since `docs/deprecation-policy.md` is no longer referenced anywhere, it's ok to delete it. And `support-content-moved.md` is only referenced by `docs/deprecation-policy.md`, it's ok to delete it, too.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3370)

### CODE REVIEW

**Comment by chenopis** [comment]
@steveperry-53 This okay w/ you?

**Comment by steveperry-53** [comment]
@xiangpengzhao, @chenopis, We're working on this issue across the entire Kubernetes doc set. Let's hold off on this PR for a few more days. 
Question/Comment: My understanding is that robots.txt should not list files with the .md extension. The extension should be .html, because that's what the robot will find on the web site. Am I misunderstanding something?

**Comment by chenopis** [comment]
@steveperry-53 I don't think the pages actually resolve to a URL ending in .html, so maybe we need to redo the robots.txt file. According to [Create a robots.txt file](https://support.google.com/webmasters/answer/6062596?hl=en), we can use the pattern matching syntax like `Disallow: /docs/admin/daemons.*` to match any of the filename extensions. However, since the site is setup to serve the pages without their extensions, maybe `Disallow: /docs/admin/daemons/` would be more correct. We need to [test and verify](https://support.google.com/webmasters/answer/6062598?hl=en&ref_topic=6061961) the robot behavior.

**Comment by xiangpengzhao** [comment]
Thanks @chenopis @steveperry-53 !

I added `deprecation-policy.md` to robots.txt with incorrect extension by mistake. Addressed.

I don't know how robot works. So let you folks check and decide what's the best format.

BTW, if we visit a URL like this `https://kubernetes.io/docs/home/contribute/style-guide.html`, the server will throw a 404 error first and then redirect to `https://kubernetes.io/docs/home/contribute/style-guide`. I wonder if robots.txt works as expected to disallow the real page being robot-ed.

**Comment by chenopis** [comment]
What we have found out is that when the site is built, the .md files are rendered into index.html files. For example, `/path/to/a/topic.md` is rendered into `/path/to/a/topic/index.html`. Consequently, I am recommending that we change the robots.txt file to use disallow entries with a `/*` at the end, e.g.: `Disallow: /path/to/a/topic/*` I am working on that in PR #3534.

**Comment by spiffxp** [comment]
FYI `deprecation-policy.md` got moved to `/docs/reference/deprecation-policy.md` via #3427 and presently 404's on the site (related: #3366)

**Comment by xiangpengzhao** [comment]
Thanks Aaron! Will update.

**Comment by chenopis** [comment]
@xiangpengzhao Sorry, I just modified robots.txt, so you'll need to resolve the conflict for that file.

**Comment by xiangpengzhao** [comment]
@chenopis Rebased.

**Pull request merged**
