### PR TITLE
Remove vagrant from the UI. 

### PR DESCRIPTION
**Pull request by vishh**
It hasn't been working reliably on OS X for many people. We can introduce it again once it is possible to set up a vagrant based cluster reliably and more importantly, quickly!

### CODE REVIEW

**Comment by janetkuo** [comment]
Do we have an open issue for setting up a vagrant based cluster, so that we don't forget about it?

**Comment by janetkuo** [comment]
Just found that vagrant doc is also linked in 

- docs/getting-started-guides/index.md
- docs/getting-started-guides/locally.md


We need to remove it there as well.

**Comment by johndmulhausen** [comment]
Please address Janet's comments and also if you're going to de-expose the file, you should also delete it outright. Doesn't make sense to leave an orphaned topic floating around the filesystem.

**Comment by vishh** [comment]
@janetkuo: #303

@johndmulhausen 
There is a CoreOS vagrant setup as well. I'm mainly concerned about the local clusters. I don't want to cleanup all the cluster setups in this PR. I have cleanup vagrant referencing a bit. PTAL.

**Comment by pwittrock** [comment]
I don't think we should delete the document altogether since I think the RedHat team may use this for development and folks 'in the know' should be able to access it.  I'd rather just bury it so you have to look for it to find it.

**Comment by vishh** [comment]
That was my original intention. Make it hard to reach.

**Comment by johndmulhausen** [comment]
I don't want "dead" docs in this repo though. Cluttering up the filesystem and creating SEO probems by having intentional detritus is not the way. 

How about this compromise: move the file under _data/archives where won't populate a URL on the live site any longer.

**Comment by vishh** [comment]
The vagrant setup docs are still available in the main kube repo.

**Comment by johndmulhausen** [comment]
Thanks, @vishh !

**Pull request merged**
