### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by seperry53test**
Do not merge.

The **Allow edits from maintainers** box is checked.

This is an experiment to see if seperry53test can create a pull request. As seperry53test, I do not even have Read permissions.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5873)

### CODE REVIEW

**Comment by seperry53test** [comment]
@heckj Can you do a review. Just kidding. I just wanted to see if seperry53test could request a review.

**Comment by heckj** [comment]
reviewing! I could even merge this _totally_ amazing piece of work :-)

/lgtm

**Comment by seperry53test** [comment]
This is interesting. Even though I have extremely limited permissions, I was able to influence the Assignees list. By asking @heckj a question, I triggered the bot, and it assigned heckj.

I'm just kicking the tires here to see what the options are for establishing a reviewer. I think the options are fairly open ended.

**Comment by heckj** [comment]
@seperry53test actually, when I invoked the `/lgtm` in my review it assigned me - so I think it was my action, not yours, that triggered that

**Comment by seperry53test** [comment]
@heckj Yeah, that makes sense.

**Pull request closed without merging**
