### PR TITLE
Update generated docs

### PR DESCRIPTION
**Pull request by erictune**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1802)

### CODE REVIEW

**Comment by erictune** [comment]
I'm not sure why the script changed the files under `_includes/v1.4/...`

**Comment by erictune** [comment]
Changes as a result of this automated regeneration:

- Lots of whitespace changes
- `http://releases.k8s.io/release-1.4/docs/devel/api-conventions.md` links now point to `http://releases.k8s.io/HEAD/docs/devel/api-conventions.md`
- `http://releases.k8s.io/release-1.4/docs/user-guide/identifiers.md` links now point to `http://kubernetes.io/docs/user-guide/identifiers`
- LocalSubjectAccessReview and SelfSubjectAccessReview added to authorization api group
- `certificates.k8s.io/v1alpha1` added; fyi @mikedanese @gtank 
- Deployment `progressDeadlineSeconds`
- `policy/v1alpha1` to `policy/v1beta1`; fyi @davidopp 
-  many  docs added under `docs/federation/...`; fyi @kubernetes/sig-cluster-federation.  
  - `docs/federation/README.md` needs to have the links moved to point to kubernetes.io once this merges. 
  - `docs/federation/api-reference/...` added which seems to duplicate a lot of what is in `docs/api-reference/...`
- Various flag and description changes in `docs/user-guide/kubectl/...`.
- Removes PetSet Kind. Adds StatefulSet Kind. Apps group's version move from v1alpha1 to v1beta1
- PhotonPersistentDisk volume type

**Comment by nikhiljindal** [comment]
> -  many  docs added under `docs/federation/...`; fyi @kubernetes/sig-cluster-federation.  

We do not need these docs under `docs/federation`. api reference docs should just be under `docs/federation/api-reference`. This PR seems to be duplicating them at both locations.

>   - `docs/federation/README.md` needs to have the links moved to point to kubernetes.io once this merges. 

`docs/federation/api-reference/README.md` contains relative links so that should be fine. No need to add `docs/federation/README.md`.

>   - `docs/federation/api-reference/...` added which seems to duplicate a lot of what is in `docs/api-reference/...`
> 

This is WAI. `docs/federation/api-reference` contains definitions of API resources that are supported in federation which is a subset of kubernetes API resources.

**Comment by nikhiljindal** [comment]
Review status: 0 of 135 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/api-reference/extensions/v1beta1/operations.md, line 4 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1802#-KXpDxFlqJ-xgpDhzMgK:-KXpDxFlqJ-xgpDhzMgL:bvua237) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/e6f9f1f81196bd80a98a9295d565469c6c7c74c2/docs/api-reference/extensions/v1beta1/operations.md#L4)):*
> ```Markdown
> ---
> 
> {% include v1.4/extensions-v1beta1-operations.html %}
> ```

You will also need to fix the script to update _includes/v1.5 instead of _includes/v1.4. Or leave this file as is.

---

*[docs/federation/api-reference/extensions/v1beta1/operations.html, line 1 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1802#-KXpESk52rYRGkDdzuC8:-KXpESk52rYRGkDdzuC9:buzzrho) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/6f18069143bc4d9d629ed7f74d512a3a61165543/docs/federation/api-reference/extensions/v1beta1/operations.html#L1)):*
> ```HTML
> ---
> ```

This change is not required. Not sure if it will break anything.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1802)*

**Comment by devin-donnelly** [comment]
Can we fix these issues and re-target to Master? Or failing that, re-import the docs now that 1.5 has launched?

**Comment by janetkuo** [comment]
I'll take over.

**Comment by janetkuo** [comment]
Superseded by #1802

**Pull request closed without merging**
