### PR TITLE
AppArmor documentation

### PR DESCRIPTION
**Pull request by timstclair**
Adds full documentation for AppArmor.

Original proposal: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/apparmor.md
Feature issue: https://github.com/kubernetes/features/issues/24

Note: 2 features referenced in this document have not yet been merged:

- Profile loader DaemonSet: https://github.com/kubernetes/contrib/pull/1658
- NodeStatus ready condition: https://github.com/kubernetes/kubernetes/pull/31659

/cc @thockin @jfrazelle @pwittrock @dchen1107 @matchstick @kubernetes/docs

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1147)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/admin/apparmor/index.md, line 7 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes.github.io/1147#-KRG-DaZSUfpN8oTIH8i:-KRG-DaZSUfpN8oTIH8j:bxx1lhm) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/3f800304b59ec941cf4dec914cbd312a99aafa04/docs/admin/apparmor/index.md#L7)):*
> ```Markdown
> ---
> 
> AppArmor is a Linux kernel enhancement that can reduce the potential attack surface and provide
> ```

For clarity, I'd recommend changing to "reduce the potential attack surface of an Application and provide greater defense in depth."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes.github.io/1147)*

**Comment by devin-donnelly** [comment]
Overall excellent. One very minor issue, but Docs LGTM.

**Comment by timstclair** [comment]
Thanks! Done.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/admin/apparmor/index.md, line 7 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes.github.io/1147#-KRG-DaZSUfpN8oTIH8i:-KRG0eNcwa4Va3sg3zoZ:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/3f800304b59ec941cf4dec914cbd312a99aafa04/docs/admin/apparmor/index.md#L7)):*
<details><summary><i>Previously, devin-donnelly wrote…</i></summary>
> For clarity, I'd recommend changing to "reduce the potential attack surface of an Application and provide greater defense in depth."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes.github.io/1147#-:-KRG0g2-fsdT-0cxvuZ7:b4855pb)*

**Comment by dchen1107** [comment]
LGTM

**Comment by timstclair** [comment]
Squashed commits.

**Comment by devin-donnelly** [comment]
Looks good, merging to release-1.4 line.

**Pull request merged**
