### PR TITLE
Fix init containers link

### PR DESCRIPTION
**Pull request by saschagrunert**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3585)

### CODE REVIEW

**Comment by saschagrunert** [comment]
.

**Comment by chenopis** [comment]
@saschagrunert When you get a chance, can you sign the CLA using the same email address as your git email. Thx

**Comment by saschagrunert** [comment]
@chenopis the thing is that I keep my mail private and pushed via the GitHub web interface. I will recreate the pull request with my real mail.

**Comment by chenopis** [comment]
@saschagrunert Ok, sounds good. Thx!

**Pull request closed without merging**
