### PR TITLE
Fix error links from v1_5 to v1.6

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
Fix error links from v1_5 to v1.6

> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3151)

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
As same as PR3146, close it.

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis I finish the task updating links from v1.5 to v1.6 or v1_5 to v1.6. Please feel free to tell me if you want me to do some verification test or some bug fixing. I am very pleased to do some researching and maintaining works of kubernetes.

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif Thanks again for all of your help! Yes, I can probably use more of your help doing verification tests or bug fixes. Let me see if I can find some that I can assign to you. Check back with me next week if you don't hear from me by Tuesday. Thanks!

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis do you have something that  I can help. :)

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif Thanks for reminding me! Yes, since we have just finished moving all of the User Guides content into Tasks, Tutorials, and Concepts, I need some help updating all of the links that go to the old locations. I can generate a list if you have some time to update and check the links. If you do, email me at [chenopis@google.com](mailto:chenopis@google.com). We can then communicate directly. Thanks!

**Comment by zhangxiaoyu-zidif** [comment]
@chenopis  I have emailed to you and I am willing to accept this task. But because of Chinese "great wall firewall", I am really not sure that you can receive my email or I can receive your email. If you received my acceptance email, please reply it and tell me that here. I need know whether there is a trouble on our connection. Thanks very much.

**Comment by chenopis** [comment]
@zhangxiaoyu-zidif I received your email. Let me know if you get my reply.

**Pull request closed without merging**
