### PR TITLE
Adding Callouts to Docs

### PR DESCRIPTION
**Pull request by cody-clark**
This uses kramdown syntax to apply a .class in Markdown. It lets us avoid using liquid tags and makes more semantic sense. For example, a note is {: .note} and a warning is {. warning}.

I removed the .note::before, etc lines to automatically insert labels that my demo included to avoid potential confusion.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4535)

### CODE REVIEW

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 00350eb81fddc9e9cd5baac15fa655d18858c47c

https://deploy-preview-4535--kubernetes-io-master-staging.netlify.com

**Comment by ahmetb** [comment]
This looks dope. Looks like there are several issues with the rendering at https://deploy-preview-4535--kubernetes-io-master-staging.netlify.com/docs/home/contribute/style-guide/#callout-formatting

image

**Comment by ahmetb** [comment]
This is very useful. I wonder what the plan would be to have existing docs/tasks use these callouts. Is anybody planning to actively go ahead and make this work with existing docs anytime soon?

**Comment by cody-clark** [comment]
It'll build some character to do some stereotypical intern work :) I'm willing to update the docs to use this.

**Comment by chenopis** [comment]
@zacharysarah Do we need to have a UX person look at this before we merge?

**Comment by zacharysarah** [comment]
@chenopis This looks awesome. I'm fine with merging it now and inviting UX to make iterative improvements. 

I think it would be a good idea to add the standards for use to the [style guide](https://kubernetes.io/docs/home/contribute/style-guide/).

**Comment by cody-clark** [comment]
@zacharysarah I did make a [style guide entry](https://deploy-preview-4535--kubernetes-io-master-staging.netlify.com/docs/home/contribute/style-guide/#callout-formatting)! Or did you have something else in mind?

**Comment by cody-clark** [comment]
Ah, thanks, @zacharysarah!

**Comment by ahmetb** [comment]
:shipit:

**Comment by chenopis** [comment]
Hold on to your hats, I'm merging this!

**Pull request merged**
