### PR TITLE
Update cpu-management-policies.md

### PR DESCRIPTION
**Pull request by lcfang**
Fixed the bad link.
Modified "cpu" to "CPU".
Added more 'yaml' as supplement.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5407)

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
Part of the diff might conflict with #5332, but I think that one should merge first.

**Comment by derekwaynecarr** [comment]
tech review LGTM

**Comment by steveperry-53** [comment]
@lcfang, Capitalize Container and Pod. Otherwise, lgtm.

After you resolve the merge conflicts, we can merge this PR.

**Pull request merged**
