### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by tailnode**
fix some wrong links (change `http://kubernetes.io/docs/user-guide/node-selection/README` to `http://kubernetes.io/docs/user-guide/node-selection`)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2602)

### CODE REVIEW

**Comment by chenopis** [comment]
@tailnode There seems to be some conflicts. If you can resolve those, I can merge this PR. Thx

**Comment by chenopis** [comment]
@tailnode can you merge `master` into this branch to update it? Thx

**Comment by tailnode** [comment]
@chenopis after merge, the travis ci build failed. when i fix this problem, i will let you know. Thx

**Comment by tailnode** [comment]
@chenopis @kelseyhightower , i found the latest four travis-ci of pr are both failed because of`panic: /tmp/go-build117414098/k8s.io/kubernetes.github.io/test/_test/test.test flag redefined: log_dir`. these four pr only modified .md or .html files, is it possible that the test cases or ci configs have some thing wrong. thanks.

**Comment by chenopis** [comment]
@tailnode Yes, I'll look into it to see what happened, but they seem to be completely unrelated to your changes.

**Pull request merged**
