### PR TITLE
admin-kube-apiserver-pr-cn

### PR DESCRIPTION
**Pull request by xiaosuiba**
Chinese version.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5109)

### CODE REVIEW

**Comment by abiogenesis-now** [comment]
@chenopis I have two questions about this PR:

(1) What is the review process for translations? I can't actually read any of this content---is the `Need CN Review` Github tag sufficient?

(2) The `kube-apiserver` docs are autogenerated from Cobra/Go code---do we have a process in place (e.g. a verification script) to ensure that translations are manually updated when the English docs are auto-updated?

**Comment by markthink** [comment]
@abiogenesis-now  We are already doing this work。

link: https://k8smeetup.github.io

**Comment by markthink** [comment]
@chenopis I am from caicloud, and the review looks good to me..

**Comment by chenopis** [comment]
@abiogenesis-now 

1. Yes, the `Need CN Review` tag is sufficient. Then assign it to `markthink`.
1. I don't know how they're handling the translation of the auto-generated docs. @markthink When you said "We are already doing this work," did you mean you already have a process to address auto-generated docs?

**Pull request merged**
