### PR TITLE
ZTE-SH-CN-define-environment-variable-container

### PR DESCRIPTION
**Pull request by YuxiJin-tobeyjin**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.8 Features: set Milestone to `1.8` and Base Branch to `release-1.8`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5382)

### CODE REVIEW

**Comment by YuxiJin-tobeyjin** [comment]
CC @zhangxiaoyu-zidif

**Comment by markthink** [comment]
@YuxiJin-tobeyjin Please close PR, update to k8smeetup library, unified submission..Do not submit a single file..

update table:
https://docs.google.com/spreadsheets/d/1FDFCv9RK5nSMgLXhPrJ5k7r5QvHnNEFnXbvoFiM8v20/edit#gid=1015862274

**Comment by markthink** [comment]
@YuxiJin-tobeyjin 首先感谢你的贡献，翻译内容需要统一管理，不建议单个文件提交，翻译文件需要在K8SMeetup的翻译库提交，在预览库显示没有问题，才能统一往上游推。

向上游推送的文档，应该是可以正常访问的中文，而不是中英文混合文件..

欢迎加入K8SMeetup中文翻译组织,我们每周会维护周报更新。

https://github.com/k8smeetup/kubernetes.github.io/blob/master/contribution.md

**Comment by zhangxiaoyu-zidif** [comment]
@markthink
Please do not send any comment about "close PR".
We hope you can join to review.
Currently we have no plan to join k8smeetup.
I think we can do the translation independently, and review here.

**Comment by YuxiJin-tobeyjin** [comment]
Format problem, close this one and pull a new one later

**Pull request closed without merging**
