### PR TITLE
Context on `finalizers` when creating namespaces

### PR DESCRIPTION
**Pull request by arnaldopereira**
Minor explanation on `finalizers` when creating namespaces before pointing to the right documentation.

### CODE REVIEW

**Comment by kelseyhightower** [comment]
@arnaldopereira Can you rebase this so I can complete the review?

**Comment by derekwaynecarr** [comment]
Tech review lgtm.

**Comment by kelseyhightower** [comment]
@arnaldopereira Let me know if you can rebase this in the next few days. If not I'll attempt to rebase and commit on your behalf.

**Comment by arnaldopereira** [comment]
@kelseyhightower got busy with other things, I'll do it in a few hours -- sorry the delay!

**Comment by kelseyhightower** [comment]
@arnaldopereira Thanks for taking the time to document this, can't wait to get it merged!

**Comment by arnaldopereira** [comment]
@kelseyhightower rebased

**Pull request merged**
