### PR TITLE
Remove Tools section.

### PR DESCRIPTION
**Pull request by steveperry-53**
Do not merge. Wait until after the 1.6 branch is merged.

> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2966)

### CODE REVIEW

**Comment by chenopis** [comment]
FYI, 1.6 is live now.

**Comment by janetkuo** [comment]
@steveperry-53 @chenopis why do we remove the tools section and where should it be discovered in kubernetes.io?

**Comment by cdrage** [comment]
Hey @steveperry-53 

I'm dissapointed that none of us at the Kompose team we're notified (not even @janetkuo ) regarding the changes.

Nevertheless, I'm creating a PR to update this outdated doc!

**Comment by steveperry-53** [comment]
@cdrage, Sorry about the surprise. We are in the process of reorganizing the table of contents for the entire Kubernetes docs set. This has involved moving content:
* Out of the Guides section and into the Tasks, Tutorials, and Concepts sections. 
* Out of the Tools section and into Tasks, Tutorials, Concepts.
* Out of Reference:Glossary and into Tasks, Tutorials, Concepts.

We are using a move-first-edit-later approach, so I've been working fairly quickly to just get topics moved. In my haste, I've probably been too casual about keeping people notified.

I did reply to @janetkuo with this explanation:

A few weeks ago, several of us met to discuss the overall TOC for the Kubernetes docs. The discussion about the Tools element in the top nav went both ways, and we eventually settled on removing it. Here are some of the reasons, to the best of my memory:
* We don't want the top nav to get too big.
* There didn't seem to be enough under Tools to justify a position in the top nav.
* The topics under Tools could be put in reasonable locations elsewhere in the TOC.
* This document has a few notes from the discussion.

Currently, the TOC is in transition. For example, many topic under GUIDES and under REFERENCE:Glossary are still there, but just contain notes about where the topics have been relocated.

Examples:
https://kubernetes.io/docs/tutorials/clusters/multiple-schedulers/
https://kubernetes.io/docs/concepts/cluster-administration/master-node-communication/
https://kubernetes.io/docs/user-guide/jobs/

Also, we're working on a new SETUP element for the top nav that will have most of what is now under GUIDES:Creating a Cluster. PR 3227

Eventually, we think the top nav should look like this:

HOME  SETUP  TASKS  TUTORIALS  CONCEPTS  REFERENCE  SAMPLES

By mid April, most of the topics with the Moved notices will be removed from the TOC, and the docs will be in version 1 of their new format. At that point, we will need to revisit the discussion about the overall design.

**Pull request merged**
