### PR TITLE
document problem with SELINUX

### PR DESCRIPTION
**Pull request by oz123**
see https://github.com/kubernetes/kubernetes/issues/33544

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1320)

### CODE REVIEW

**Comment by oz123** [comment]
I signed the agreement.

**Comment by oz123** [comment]
@rustyrobot well, if there is fix for that already maybe, it should not be merged. Or maybe merged, and then removed when a newer version is released?

**Comment by dgoodwin** [comment]
I believe we have freedom to publish kubeadm releases as necessary given our alpha status and the work we've done on packaging. I would suggest we get #33555 merged ASAP and rebuild. Fully disabling selinux is a pretty drastic system-wide step and something we've been trying to avoid throughout this process.

**Comment by dgoodwin** [comment]
Looks like @lukemarsden has already picked up a setenforce 0 in his docs update PR here: https://github.com/kubernetes/kubernetes.github.io/pull/1321

**Comment by lukemarsden** [comment]
@mikedanese took the decision to release stable with this in but we'll fix it very _very_ soon.

**Comment by lukemarsden** [comment]
Also yes no need for this change given https://github.com/kubernetes/kubernetes.github.io/pull/1321 - thanks!

**Comment by devin-donnelly** [comment]
I'll close this PR, as it's been made obsolete by #1321.

**Pull request closed without merging**
