### PR TITLE
Move mungedocs tool to the docs repo.

### PR DESCRIPTION
**Pull request by thockin**
If this passes muster, it could be applied to other branches

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5178)

### CODE REVIEW

**Comment by thockin** [comment]
We could probably move the md-check repo too :)

**Comment by thockin** [comment]
Which branches do I need to recreate this against?

**Comment by cblecker** [comment]
Looks like the release branches for 1.5 through 1.8 all use mungedocs.

Perhaps if we're going to do cherry pick this PR back anyways, we also want to bump the golang version on line 3 from go1.8.1 to go1.8.3 which includes a security fix :)

**Comment by thockin** [comment]
By your command!

**Comment by steveperry-53** [comment]
Thank you @thockin, @dims, @cblecker.

**Pull request merged**
