### PR TITLE
Add Bundler to staging a doc request page

### PR DESCRIPTION
**Pull request by jaredbhatti**
Fixing the following PR: https://github.com/kubernetes/kubernetes.github.io/pull/1796

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2145)

### CODE REVIEW

**Comment by mikedanese** [comment]
This works best if we add github-pages gem to the gemfile.

**Comment by mikedanese** [comment]
e.g. https://github.com/kubernetes/test-infra/pull/1508/files

**Comment by chenopis** [comment]
@jaredbhatti is this good to go or are there more changes that need to be made?

**Comment by jaredbhatti** [comment]
@mikedanese What's the specific fix for the instructions?

**Comment by mikedanese** [comment]
It's probably not a big deal, this looks fine

**Pull request merged**
