### PR TITLE
Adding more details for running minikube without a Docker registry

### PR DESCRIPTION
**Pull request by king-julien**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1887)

### CODE REVIEW

**Comment by king-julien** [comment]
I signed it!

**Comment by king-julien** [comment]
@dlorenc I have no clue how to get "cla/linuxfoundation " check passed. I actually signed it and updated my git repo with the correct email address.

**Comment by king-julien** [comment]
I signed it!

**Comment by king-julien** [comment]
@k8s-ci-robot I signed it!

**Comment by dlorenc** [comment]
@king-julien, looking in your commits it looks like @JaisonJohn also authored one. I'm guessing that commit is the one that's causing trouble.

**Comment by dlorenc** [comment]
Hey, any idea if you can get @JaisonJohn to sign or figure out how he's showing up in the commits?

**Comment by king-julien** [comment]
Closing this PR for fixing cncf-cla

**Comment by king-julien** [comment]
created a new [PR](https://github.com/kubernetes/kubernetes.github.io/pull/1995). @dlorenc please take a look when you get a chance. Thanks.

**Pull request closed without merging**
