### PR TITLE
Validate docs/user-guide/pod-security-policy/psp.yaml

### PR DESCRIPTION
**Pull request by php-coder**
Related to https://github.com/kubernetes/kubernetes.github.io/pull/3010#issuecomment-290143236

PTAL @chenopis

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3100)

### CODE REVIEW

**Comment by chenopis** [comment]
@php-coder /lgtm Based on the logs, looks like everything ran correctly. Just going to get a second set of eyes to sign off on this.

**Comment by chenopis** [comment]
@jeffmendoza Can you take a quick look? Thx

**Comment by php-coder** [comment]
Ping.

**Comment by chenopis** [comment]
@jeffmendoza Can you recommend someone that can do a quick code review of this? Thx

**Comment by php-coder** [comment]
Any updates on that?

**Comment by chenopis** [comment]
@php-coder I've tested this and am not seeing any problems w/ it, so I'm going to merge this PR. Thanks for the contribution!

**Pull request merged**
