### PR TITLE
Fix typo in md.

### PR DESCRIPTION
**Pull request by joeint**
Fix typo in md from web.yml to web.yaml

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1986)

### CODE REVIEW

**Comment by joeint** [comment]
I signed it under joeint@google.com

**Comment by janetkuo** [comment]
@joeint looks like the bot didn't see your signed CLA. Would you verify it?

> - If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

**Comment by devin-donnelly** [comment]
@joeint Seems like we still have a CLA issue. I can merge it as soon as that's resolved.

**Comment by joeint** [comment]
@devin-donnelly @janetkuo I resigned it with the same github email.  Please let me know if there's anything else

**Pull request closed without merging**
