### PR TITLE
Add object fields to style guide.

### PR DESCRIPTION
**Pull request by steveperry-53**
I think we need style guidance for object field names and object field values. This PR has my suggestions for some new guidelines. Discussion welcome.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2418)

### CODE REVIEW

**Comment by steveperry-53** [comment]
cc: @chenopis, @jaredbhatti, @pwittrock

**Comment by steveperry-53** [comment]
attn: @devin-donnelly

**Comment by chenopis** [comment]
I personally prefer a different style than normal for string and integer field values to set them apart from the regular text, but if that's the convention here, that's fine. I'm cool w/ everything else.

**Comment by steveperry-53** [comment]
> I personally prefer a different style than normal for string and integer field values to set them apart from the regular text, but if that's the convention here, that's fine. I'm cool w/ everything else.

Well, we don't really have a convention yet. The current docs use all kinds of different styles for field values. Let's see what some of the others think.

**Pull request merged**
