### PR TITLE
remove rbac super user reference

### PR DESCRIPTION
**Pull request by deads2k**
This should be a part of 1.6 docs.

https://github.com/kubernetes/kubernetes/pull/38121 removes the rbac super user.

@kubernetes/sig-auth

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1858)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
@deads2k If this isn't live until 1.6, this PR is going to sit here for a while.

**Comment by jheiss** [comment]
Maybe it should be obvious to me, but how is a user supposed to get themselves into the system:masters group in order to bootstrap themselves into RBAC? It seems like this doc should either explain that or provide a pointer to some place that does.

**Comment by deads2k** [comment]
> Maybe it should be obvious to me, but how is a user supposed to get themselves into the system:masters group in order to bootstrap themselves into RBAC? It seems like this doc should either explain that or provide a pointer to some place that does.

Every authenticator is allowed to specify groups.  Certificate authentication would be my first choice since you could mint the file and keep it local on the API server machine itself.  An certificate signed for the `system:masters` organization (see local-up-cluster.sh for an example) works.  It's not particular though, anything authenticator can do it.

 This doc doesn't cover those topics, but I'll try to sort out how to add a link to them.

**Comment by jheiss** [comment]
Sorry, I thought that I had read somewhere that the "system:" namespace of users and groups was reserved and that outside entities like an authenticator shouldn't interact in that space. But now I can't find that reference, presuming I didn't just imagine it. If it is fine for any authenticator to add appropriate users to system:master then that is relatively straightforward.

**Comment by chenopis** [comment]
@deads2k FYI, the kubernetes:release-1.6 branch is now available. Please change the base branch to that. Thx

**Comment by chenopis** [comment]
@deads2k Just checking in. Is this PR still slated for the 1.6 release? If so, can you resolve the conflicts and change the base branch from `kubernetes:master` to `kubernetes:release-1.6`? Thx

**Comment by deads2k** [comment]
@liggitt did you already get this in another doc for 1.6?

**Comment by liggitt** [comment]
yeah, already in https://github.com/kubernetes/kubernetes.github.io/pull/2618/

**Pull request closed without merging**
