### PR TITLE
Mention OpenShift Dedicated and Online as hosted solutions

### PR DESCRIPTION
**Pull request by smarterclayton**
Both offer Kubernetes + additional developer tools and management policy
on top. OpenShift Online is free for anyone to simply kick the tires on Kubernetes.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1627)

### CODE REVIEW

**Comment by mikedanese** [comment]
LGTM

**Comment by smarterclayton** [comment]
gentle ping on a merge here

**Comment by devin-donnelly** [comment]
There's a merge conflict. Would you mind resolving it?

**Comment by smarterclayton** [comment]
Resolved, sorry for the delay.

**Pull request merged**
