### PR TITLE
Fix code and fix link to code.

### PR DESCRIPTION
**Pull request by steveperry-53**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2206)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@pwittrock, I've been happily doing pull requests for many moons. Starting today, my PRs are failing the Travis CI build. Any idea what's going on?

**Comment by pwittrock** [comment]
Hm, has something to do with this file:

https://github.com/kubernetes/kubernetes.github.io/blob/b77ebe2cc5cb7baea7cfd2f22e695ac2e978a06e/test/examples_test.go

**Comment by pwittrock** [comment]
@jeffmendoza Is this an area you are familiar with?

**Comment by jeffmendoza** [comment]
Yes, the travis tests do a go get on kubernetes code directly (not vendored), so sometimes changes in the main repo cause breakages in our tests. This looks like one of those times. I'm not available to look at this tomorrow, but have time Friday.

**Comment by steveperry-53** [comment]
Adding comment to see if Travis check will pass.

**Comment by steveperry-53** [comment]
@waprin, Can you take a look and LGTM.

**Comment by steveperry-53** [comment]
Fixes https://github.com/kubernetes/kubernetes.github.io/issues/2181.

**Comment by waprin** [comment]
Sorry, LGTM

**Pull request merged**
