### PR TITLE
Some small style tweaks to make pandoc working

### PR DESCRIPTION
**Pull request by adieu**
I was trying to generate pdf handbooks for kubernetes from official documents using pandoc. There were some errors preventing pandoc doing its work.

One of them is because some files are in the dos format with extra ^M. I fixed it with one commit.

In order to improve the quality of the result pdf files, I also make some small changes to tweak the header level and table width. It's in the other commit.

I could create another PR for the pandoc environment if someone finds it useful.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes.github.io/1144)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
Can you verify that these changes don't have any negative effect on how the documentation renders?

**Comment by adieu** [comment]
For the first commit it just removed unnecessary ^M which would not change the document render at all.

For the second commit I make some small changes to the content like modifying header level and fixing a broken link for the image. I think they're good improvements.

**Comment by devin-donnelly** [comment]
Please rebase and resolve all merge conflicts and I'll check it via automatic staging.

**Comment by adieu** [comment]
rebased

**Comment by devin-donnelly** [comment]
I spot-checked most of the files. Looks okay. However, many of these files are going to be touched in 1.4, so this PR is going to cause a large number of merge conflicts at launch. I'm going to hold off.

**Comment by devin-donnelly** [comment]
Post 1.4 launch, this has merge conflicts that need to be resolved.

**Comment by adieu** [comment]
I'll do a rebase soon.

**Comment by adieu** [comment]
rebased

**Pull request merged**
