### PR TITLE
revert WordPress and MySQL PV doc changes to use apps/v1beta2 APIs

### PR DESCRIPTION
**Pull request by crimsonfaith91**
Revert the changes of PR #5424 as the PR targeted the wrong branch.
The auto revert mechanism does not work.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5461)

### CODE REVIEW

**Comment by foxish** [comment]
/lgtm
PTAL @steveperry-53

**Comment by crimsonfaith91** [comment]
@steveperry-53 I found out that you merged branch `master` into `release-1.8`. I think you can skip this PR when fast-forwarding the changes later on. You can tell me if you fast-forwarded this PR, so that I can send out another PR targeting `release-1.8`.

**Comment by steveperry-53** [comment]
@crimsonfaith91, I'm not sure I now how to skip a PR when fast forwarding. My plan is to merge master into release-1.8 often (every day is the plan).

**Comment by crimsonfaith91** [comment]
Noted - I will send out the PR targeting branch `release-1.8` tomorrow or next Monday so that the change can be reflected to the branch eventually.

**Pull request merged**
