### PR TITLE
init container feature has been moved to Beta stage

### PR DESCRIPTION
**Pull request by keglevich3**
init container feature has been moved to Beta stage.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1509)

### CODE REVIEW

**Comment by erictune** [comment]
LGTM.  You need to rebase.

See also https://github.com/kubernetes/kubernetes.github.io/pull/1701/files.

**Comment by keglevich3** [comment]
I clicked on "Update branch" is that enough?

**Comment by devin-donnelly** [comment]
I don't see any changed files here.

**Comment by erictune** [comment]
Looks like this is fixed now.  Thanks though.

**Pull request closed without merging**
