### PR TITLE
getting-started-guides: add CoreOS Tectonic

### PR DESCRIPTION
**Pull request by robszumski**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2648)

### CODE REVIEW

**Comment by robszumski** [comment]
Are there separate CLAs for this repo vs the regular Kubernetes repo? I have successfully used this email in the past on the other repo.

**Comment by chenopis** [comment]
It should be the same since it's the CNCF. When you went through that process, did you login using your GitHub account or one of the other paths? 

This is screenshot of what I see as a confirmation w/ mine:
screen shot 2017-02-28 at 4 11 44 pm

**Comment by robszumski** [comment]
@chenopis I believe our CTO signed a blanket agreement for the entire company or something of that sort.

**Comment by chenopis** [comment]
@robszumski Ok, cool, so it should have a record of your org. Did you go through the employee path on the CLA site [https://identity.linuxfoundation.org/projects/cncf](https://identity.linuxfoundation.org/projects/cncf)? I'm trying to figure out why the bot is not associating you correctly.

**Comment by robszumski** [comment]
@chenopis No, I don't think I did. Is that required with the blanket agreement?

**Comment by chenopis** [comment]
@robszumski Yes, you should go through the employee path on that site to link your email address w/ your organization's blanket agreement. That should do the trick.

**Comment by robszumski** [comment]
I signed it!

**Comment by chenopis** [comment]
@robszumski Awesome, thank you!

**Pull request merged**
