### PR TITLE
Fixed typos in services-firewalls.md

### PR DESCRIPTION
**Pull request by TheStalwart**
Fixed two typos: blancer -> balancer

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2760)

### CODE REVIEW

**Comment by TheStalwart** [comment]
I'm trying to sign CLA, but https://identity.linuxfoundation.org/projects/cncf rejects me with an error:
The requested page "/projects/cncf" could not be found.

**Comment by chenopis** [comment]
@TheStalwart I wonder if that was a temporary issue. Do you still get that error? I'm not seeing that at the moment. If you're still seeing it though, could it be some network security policy on your local network that's blocking it?

**Comment by TheStalwart** [comment]
@chenopis i can access the page now. I will go through the procedure when i have a spare time

**Comment by chenopis** [comment]
@TheStalwart Cool, thx!

**Comment by TheStalwart** [comment]
Now i have another problem with CLA. When i login, it denies me access. When i retry after logging in, it states "A Contributor License Agreement has been sent to your email address", but it in fact hasn't been. I have some older CLA signup link in my inbox from previous attempts, but it's now expired, and i can't get the new one.

This CLA thing is getting really annoying.

**Comment by TheStalwart** [comment]
@chenopis After another retry i've received a confirmation of CLA being signed

**Comment by chenopis** [comment]
@TheStalwart Awesome, that's great! Now there's just the small issue of a merge conflict with that file. If you can resolve that, I will be able to merge this PR. Thanks! =)

**Comment by TheStalwart** [comment]
@chenopis Please confirm my merge was correct

**Comment by chenopis** [comment]
@TheStalwart Yup, looks good! Thanks!

**Pull request merged**
