### PR TITLE
Remove the docker-multinode guide as it's not working anymore

### PR DESCRIPTION
**Pull request by luxas**
ref: https://goo.gl/VxSaKx

cc @jbeda @brendandburns @bgrant0607 @justinsb @mikedanese

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3436)

### CODE REVIEW

**Comment by chenopis** [comment]
@luxas Looks like there are some merge conflicts.

**Comment by mikedanese** [comment]
tech lgtm

**Comment by chenopis** [comment]
@luxas BTW, some of this was moved to the Setup section, so you will need to modify the /_data/setup.yml file as well (i.e. line 97: - docs/getting-started-guides/docker-multinode.md).

**Comment by luxas** [comment]
@chenopis Updated. Please merge if you think all docs issues are resolved.

**Comment by chenopis** [comment]
@luxas Thanks! One more thing: you'll also need to add the following two lines to `/skip_toc_check.txt` to clear the Travis CI check:

docs/getting-started-guides/docker.md
docs/getting-started-guides/docker-multinode.md

**Comment by luxas** [comment]
@chenopis Could you do that for me please? I'm only mobile for the next four days. I have the "Allow maintainers to edit" checkbox checked.

It would be good to get this in ASAP

**Comment by chenopis** [comment]
@luxas Sure, no problem. Will do!

**Pull request merged**
