### PR TITLE
Write new task: Assigning CPU and RAM Resources to a Container.

### PR DESCRIPTION
**Pull request by steveperry-53**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1576)

### CODE REVIEW

**Comment by pwittrock** [comment]
Plz add to the task landing page

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 23 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7l815zzn1rdbyDib6:-KV7l815zzn1rdbyDib7:b-ijcedm) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L23)):*
> ```Markdown
> ### Assigning CPU and RAM resources to a container
> 
> When you create a Pod, you can request CPU and RAM resources for the containers
> ```

It is probably worth specifying what happens if you don't specify the resources.

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lrJnrvAfmkfmDG4_:-KV7lrJnrvAfmkfmDG4a:b13bvjq) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L52)):*
> ```Markdown
>           cpu-ram-demo-container:
>            ...
>             Limits:
> ```

What is the difference between requested resources and the limit?

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 56 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lo9QzsJl24v0TZIj:-KV7lo9QzsJl24v0TZIk:b-4zmrmm) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L56)):*
> ```Markdown
>               memory: 128Mi
>             Requests:
>               cpu:    250m
> ```

What happens if the memory limit is exceed by the container (killed with OOM)?  What about cpu usage (nothing, just limits the usage)?

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 69 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lJiXd4f4SnwmzpZC:-KV7lJiXd4f4SnwmzpZD:b28pive) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L69)):*
> ```Markdown
> Ti, Gi, Mi, Ki. For example, the following represent approximately the same value:
> 
>     128974848, 129e6, 129M , 123Mi
> ```

Consider adding a note about what will happen if there is no capacity in the cluster available (Pod is not scheduled until resources become available).
Consider mentioning that there are different QoS of resources (e.g. Burstable, Gauranteed).

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-:-KV7kydZ5BDpz48mvgal:b-fh6oaj)*

**Comment by pwittrock** [comment]
@kubernetes/sig-node Can anyone from node help answer these questions?

**Comment by dashpole** [comment]
*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 23 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7l815zzn1rdbyDib6:-KVAz8OJNdUPtuE80rNw:brr123h) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L23)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> It is probably worth specifying what happens if you don't specify the resources.
</details>
If resources are not specified, the container is considered "Best-Effort" and will be the first to be evicted if the node runs out of resources (e.g. memory).  More generally, requests and limits are used both to specify resources a container should be given, and to specify the Quality of Service (QoS) of a container.  

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by dashpole** [comment]
*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lrJnrvAfmkfmDG4_:-KVB00shZVNC23xafJ7l:b-3avg9v) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L52)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> What is the difference between requested resources and the limit?
</details>
From the docs: "Specifically, for each resource, containers specify a request, which is the amount of that resource that the system will guarantee to the container, and a limit which is the maximum amount that the system will allow the container to use. The system computes pod level requests and limits by summing up per-resource requests and limits across all containers."  Basically, a pod is guaranteed to get its requested resources during scheduling, and the limit is the most it is ever allowed to use.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by pwittrock** [comment]
@dashpole Does eviction occur when a Node has reserved memory for another container, but all memory is consumed?

**Comment by dashpole** [comment]
Ill post these here since they are relevant.  https://github.com/kubernetes/kubernetes/blob/master/docs/design/resource-qos.md https://github.com/kubernetes/kubernetes/blob/master/docs/design/resources.md

**Comment by pwittrock** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lrJnrvAfmkfmDG4_:-KVB139gaazqunkVbslM:b-kxb619) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L52)):*
<details><summary><i>Previously, dashpole (David Ashpole) wrote…</i></summary>
> From the docs: "Specifically, for each resource, containers specify a request, which is the amount of that resource that the system will guarantee to the container, and a limit which is the maximum amount that the system will allow the container to use. The system computes pod level requests and limits by summing up per-resource requests and limits across all containers."  Basically, a pod is guaranteed to get its requested resources during scheduling, and the limit is the most it is ever allowed to use.
</details>
The purpose of a limit then is to prevent eviction?  If a container is using more than its request and less than its limit, will it get evicted if the Node needs to reclaim resources?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by dashpole** [comment]
*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lrJnrvAfmkfmDG4_:-KVB1wjZMbMxGReipQuA:bd4o2sm) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L52)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> The purpose of a limit then is to prevent eviction?  If a container is using more than its request and less than its limit, will it get evicted if the Node needs to reclaim resources?
</details>
Limits mean different things for different resources as far as I know.  CPU limits, for example, will cause the container to be throttled when exceeded.  Exceeding memory limits will make the container a more likely candidate for eviction if memory limits are hit.  

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by dashpole** [comment]
*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lrJnrvAfmkfmDG4_:-KVB38L-wqPjJuzWu5ri:b-jsous6) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L52)):*
<details><summary><i>Previously, dashpole (David Ashpole) wrote…</i></summary>
> Limits mean different things for different resources as far as I know.  CPU limits, for example, will cause the container to be throttled when exceeded.  Exceeding memory limits will make the container a more likely candidate for eviction if memory limits are hit.  
</details>
Ive been corrected.  Exceeding limits will cause it to be killed by the kernel.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by dashpole** [comment]
*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 56 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lo9QzsJl24v0TZIj:-KVB2gvCdOi54vTR5sWc:bbr62yn) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L56)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> What happens if the memory limit is exceed by the container (killed with OOM)?  What about cpu usage (nothing, just limits the usage)?
</details>
Yes, it will be killed.  Cpu is throttled

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by pwittrock** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lrJnrvAfmkfmDG4_:-KVB2kLnfC3ywqZcfkse:bu6xt57) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L52)):*
<details><summary><i>Previously, dashpole (David Ashpole) wrote…</i></summary>
> Ive been corrected.  Exceeding limits will cause it to be killed by the kernel.
</details>
IIUC: The system will never allow the container the container to exceed its `Limits`, but it can exceed its `Requests`.  The request is guaranteed and if needed the Node will evict another Pod to provide the Requested resources.  Limits are not guaranteed but provide a hard upper bound.  Exceeding `Requests` make the container a *candidate* for throttling (CPU) or eviction (Memory).  Exceeding Limits either throttle immediately (CPU) or kill the container (Memory).  Is this an accurate summary?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by dashpole** [comment]
*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lrJnrvAfmkfmDG4_:-KVB5Phg-5BBdhcT1b7K:bxrud5g) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L52)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> IIUC: The system will never allow the container the container to exceed its `Limits`, but it can exceed its `Requests`.  The request is guaranteed and if needed the Node will evict another Pod to provide the Requested resources.  Limits are not guaranteed but provide a hard upper bound.  Exceeding `Requests` make the container a *candidate* for throttling (CPU) or eviction (Memory).  Exceeding Limits either throttle immediately (CPU) or kill the container (Memory).  Is this an accurate summary?
</details>
Yes, that is an accurate summary.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by pwittrock** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lrJnrvAfmkfmDG4_:-KVB9idHPoTxRrOe5PT5:b-3chs6o) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L52)):*
<details><summary><i>Previously, dashpole (David Ashpole) wrote…</i></summary>
> Yes, that is an accurate summary.
</details>
Thanks.  @steveperry-53 I think that answers your question yesterday about why one would ever set a limit.  Setting a limit causes the container to be killed / throttled when exceeding reserved resources instead of allowing it to run by possibly get evicted at some point in the future.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by steveperry-53** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 23 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7l815zzn1rdbyDib6:-KVBbGbhuNcr8i0flgbS:b-xxs4nz) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L23)):*
<details><summary><i>Previously, dashpole (David Ashpole) wrote…</i></summary>
> If resources are not specified, the container is considered "Best-Effort" and will be the first to be evicted if the node runs out of resources (e.g. memory).  More generally, requests and limits are used both to specify resources a container should be given, and to specify the Quality of Service (QoS) of a container.  
</details>
I'm concerned that if I add all the notes requested in this pull request, I will create a concept piece, rather than a task piece. I'll try to strike a balance. Our current design plan is that a task page quickly shows how to do a single task, but does not delve into explanations. Eventually, we can have concept topics that are focused, and we will link to those from our task pages. For example, we could have a concept topic that is focused on RAM requests and limits. We could have another that is focused on CPU requests and limits. For now, I'll link to existing topics that explain the concepts related to CPU and RAM.

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lrJnrvAfmkfmDG4_:-KVBcUzPsBhb1g2wW-cT:b-9lu301) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L52)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Thanks.  @steveperry-53 I think that answers your question yesterday about why one would ever set a limit.  Setting a limit causes the container to be killed / throttled when exceeding reserved resources instead of allowing it to run by possibly get evicted at some point in the future.
</details>
Thanks, that is helpful. Here's the question that remains in my mind: What would cause a user-mode process to exceed a RAM limit, given that RAM can be swapped out to disk? Does Kubernetes also impose a swap limit? The mlock man page says there are two main reasons a process would lock physical memory: real-time algorithms and high-security data processing. Is that what we're talking about here? Or is there some other way an application could use too much physical memory? 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by dashpole** [comment]
*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 23 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7l815zzn1rdbyDib6:-KVBhc7xkLiG2JMeTen4:b-c0u5m) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L23)):*
<details><summary><i>Previously, steveperry-53 (Steve Perry) wrote…</i></summary>
> I'm concerned that if I add all the notes requested in this pull request, I will create a concept piece, rather than a task piece. I'll try to strike a balance. Our current design plan is that a task page quickly shows how to do a single task, but does not delve into explanations. Eventually, we can have concept topics that are focused, and we will link to those from our task pages. For example, we could have a concept topic that is focused on RAM requests and limits. We could have another that is focused on CPU requests and limits. For now, I'll link to existing topics that explain the concepts related to CPU and RAM.
</details>
I would agree that the topic of QoS is a little complicated for a task piece.  If there are other places where we explain QoS and resource requests/limits, it might be worth just linking the more detailed explanation rather than summarizing here.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by dashpole** [comment]
*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7lrJnrvAfmkfmDG4_:-KVBiH1nWxj0nKWqiiSu:b-ayu99r) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L52)):*
<details><summary><i>Previously, steveperry-53 (Steve Perry) wrote…</i></summary>
> Thanks, that is helpful. Here's the question that remains in my mind: What would cause a user-mode process to exceed a RAM limit, given that RAM can be swapped out to disk? Does Kubernetes also impose a swap limit? The mlock man page says there are two main reasons a process would lock physical memory: real-time algorithms and high-security data processing. Is that what we're talking about here? Or is there some other way an application could use too much physical memory? 
</details>
Kubernetes does not support running with swap enabled.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by pwittrock** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 23 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KV7l815zzn1rdbyDib6:-KVBjD-iDYuQ9BJqErCR:b-wjs0vd) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/cfb9355d4e2dae7797c12e39260f3736dc90a1b3/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L23)):*
<details><summary><i>Previously, dashpole (David Ashpole) wrote…</i></summary>
> I would agree that the topic of QoS is a little complicated for a task piece.  If there are other places where we explain QoS and resource requests/limits, it might be worth just linking the more detailed explanation rather than summarizing here.
</details>
I think we should at least mention somewhere that setting memory limits  will cause the task to be killed if it exceeds the limit.  This may surprise some folks and we shouldn't count on them reading the detailed explanation before blindly proceeding ahead.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Comment by pwittrock** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docs/tasks/configure-pod-container/assign-cpu-ram-container.md, line 33 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576#-KVRehVw811wdblKT4vs:-KVRehVx7--JoELKv0zW:bgxdl6y) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/47350e2bb725f64011d6d6f4a028db46cb6b4fbf/docs/tasks/configure-pod-container/assign-cpu-ram-container.md#L33)):*
> ```Markdown
> containers in the Pod. Also, as a container runs on a Node, Kubernetes doesn't
> allow the CPU and RAM consumed by the container to exceed the limits you specify
> for the container If a container exceeds its RAM limit, it is terminated. If a
> ```

nit: missing period?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1576)*

**Pull request merged**
