### PR TITLE
Fix kubectl run syntax

### PR DESCRIPTION
**Pull request by mattymo**
Removed --expose, changed --service-overrides to --overrides,
and added apiVersion to conform to proper syntax.

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@mattymo if you'd like your PR to be reviewed, please, follow the recommendations from the @googlebot

**Comment by johndmulhausen** [comment]
@mattymo ping?

**Comment by kelseyhightower** [comment]
@mattymo Are you able to sign the CLA? If not I can take a look at fixing these examples. Let me know.

**Comment by kelseyhightower** [comment]
This is example is not quite right. I've fixed this in https://github.com/kubernetes/kubernetes.github.io/pull/927

**Pull request closed without merging**
