### PR TITLE
Removed `=` at the end of the flags.

### PR DESCRIPTION
**Pull request by gyliu513**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2734)

### CODE REVIEW

**Comment by gyliu513** [comment]
@caesarxuchao can you please help approve this? I'm going to update this file for `taint` related, so hope this can be committed first. Thanks.

**Comment by caesarxuchao** [comment]
Merged :)

**Comment by gyliu513** [comment]
Thanks @caesarxuchao :)

**Pull request merged**
