### PR TITLE
Fix spelling error

### PR DESCRIPTION
**Pull request by aschepis**
Fix misspelling of rabbitmq in coarse parallel processing example

> NOTE: Please check the “Allow edits from maintainers” box (see image below) to  
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4528)

### CODE REVIEW

**Comment by aschepis** [comment]
all set as an individual contributor.

**Comment by ahmetb** [comment]
/lgtm 

@aschepis Please check the “Allow edits from maintainers” box on the right so we can rebase/merge your branch.

**Comment by aschepis** [comment]
argh. i thought i had.  all set @ahmetb

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 0e567993aea1a398f10e4fb158d13de6f714beeb

https://deploy-preview-4528--kubernetes-io-master-staging.netlify.com

**Pull request merged**
