### PR TITLE
Use pipeline to remove new line char

### PR DESCRIPTION
**Pull request by hoatle**
When -w option is not available for base64, for example, when using alpine Docker image.
`echo -n "<text>" | base64 | tr -d '\n'` should be used, it works better.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3458)

### CODE REVIEW

**Comment by chenopis** [comment]
@mikedanese Is `base64 | tr -d '\n'` an acceptable substitute if `-w` is not available?

**Comment by mikedanese** [comment]
sorry just getting back from vacation. Yes this looks fine.

**Comment by chenopis** [comment]
No worries. Thanks @mikedanese!

**Comment by chenopis** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/3458)*

**Pull request merged**
