### PR TITLE
Api and Kubectl reference docs updates for 1.7

### PR DESCRIPTION
**Pull request by pwittrock**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.7 Features: set Milestone to `1.7` and Base Branch to `release-1.7`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4193)

### CODE REVIEW

**Comment by chenopis** [comment]
@pwittrock I saw some other PRs mention that there are still links to the user-guide directory (http://kubernetes.io/docs/user-guide/...) and some typos like "of of". Can these be corrected before we merge this in?

**Comment by ahmetb** [comment]
/lgtm
@pwittroc is all that node_modules dir actually used in the UI? It adds quite a bit to the source tree with all the JS, webfonts and other assets.

**Comment by pwittrock** [comment]
A couple things aren't rendering right.  WIll followup

**Comment by pwittrock** [comment]
Re the typos, those are in the source code types.go files and would require changes to kubernetes/kubernetes.  Do you want to file a PR to fix those?  To get into 1.7 it will need to be cherry picked

**Comment by pwittrock** [comment]
re node_modules.  I don't think they should be required, but when I delete them the rendering changes.  If you think we should remove them, would you file an issue?

**Comment by chenopis** [comment]
Re: typos. I don't think we have enough time to make the changes before the 1.7 release. Would it be possible to rerun the autogeneration process again and do a patch release? I opened issues https://github.com/kubernetes/kubernetes/issues/48105 and https://github.com/kubernetes/kubernetes.github.io/issues/4194

**Comment by pwittrock** [comment]
@chenopis Yes it is easy to rerun.  Just let me know when.

**Comment by chenopis** [comment]
@pwittrock Ok, thanks!

**Comment by pwittrock** [comment]
Alright, fixed up all the issues.  PTAL.

**Comment by pwittrock** [comment]
@ahmetb FWIW, there is a lot more in the openapi spec now that should make it possible to simplify the doc generator code.

**Comment by chenopis** [comment]
Fire in the hole! I'm merging this.

**Pull request merged**
