### PR TITLE
Update Calico Ubuntu guide to use v1.3.0

### PR DESCRIPTION
**Pull request by caseydavenport**
Updates the Calico ubuntu / systemd guide to use Kubernetes v1.3.0 (when it is released) and adds NetworkPolicy support.

### CODE REVIEW

**Comment by pwittrock** [comment]
@caseydavenport would you assign a tech reviewer who has the domain knowledge to review this?

**Comment by pwittrock** [comment]
@matchstick Assigned to you for triage.  Is this something the cluster team should look at?

**Comment by caseydavenport** [comment]
Going to close this for now - will be revisiting soon.

**Comment by matchstick** [comment]
@caseydavenport I apologize for missing this. Do you still need a reviewer?

**Pull request closed without merging**
