### PR TITLE
fix persistent volume example link

### LINKED ISSUE #2257: "PersistentVolume Provisioning" link is broken
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The link for "PersistentVolume Provisioning" in section "Before you begin" is broken: https://github.com/kubernetes/kubernetes/tree/master/examples/experimental/persistent-volume-provisioning/

**Proposed Solution:**
Replace with correct link.

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/

### PR DESCRIPTION
**Pull request by rootfs**
fix #2257

@jsafrane @gnufied

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2270)

### CODE REVIEW

**Comment by rootfs** [comment]
CI looks broken

**Comment by jsafrane** [comment]
LGTM from tech side

**Comment by gnufied** [comment]
lgtm

**Comment by jaredbhatti** [comment]
Can you resolve the conflicts?

**Comment by rootfs** [comment]
@jaredbhatti resolved, thanks

**Pull request merged**
