### PR TITLE
Fixing typo

### PR DESCRIPTION
**Pull request by aaronSig**
.PONY -> .PHONY

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2124)

### CODE REVIEW

**Comment by aaronSig** [comment]
I signed it!

**Comment by aaronSig** [comment]
I signed it!

**Comment by chenopis** [comment]
@jaredbhatti looks like the correct format for the makefile to me, but can you verify? Thx

**Comment by chenopis** [comment]
@janetkuo can you take a quick look and give your blessing for the makefile format w/ the corrected typo? Thx

**Comment by janetkuo** [comment]
@aaronSig thanks, LGTM

**Pull request merged**
