### PR TITLE
Update ubuntu install instructions.

### PR DESCRIPTION
**Pull request by castrojo**
Everything is now in the distro update channels, so these instructions can be simplified greatly.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2641)

### CODE REVIEW

**Comment by chenopis** [comment]
@pwittrock Would you mind assigning an appropriate tech reviewer to double check this? Thanks!

**Comment by madhusudancs** [comment]
@chenopis I am not qualified to review this.

@mikedanese any idea who works on this?

**Comment by chenopis** [comment]
@madhusudancs Ok, sorry about that. Thanks for taking a look anyway. =)

**Comment by battlemidget** [comment]
Due to the relatively new conjure-up experience there may be a lack in reviewers to approve this documentation. I just want to re-assure the tech review team that the entire http://conjure-up.io product relies on http://snapcraft.io and is continually tested inside our ci infrastructure.  The tests cover the installation and upgrading of conjure-up on multiple series (Trusty, Xenial) in addition to deploying kubernetes on various clouds including OpenStack, Localhost(LXD), and MAAS(metal as a service). We also have full end to end testing which is run against a completed conjure-up deployment (https://github.com/juju-solutions/bundle-kubernetes-e2e)

Please feel free contact me adam.stokes@ubuntu.com if you have further questions.

Thanks
Adam

**Comment by chenopis** [comment]
@battlemidget Thanks, Adam. I'm not running Ubuntu at the moment, so I just wanted someone else to independently confirm that those are the correct commands and the install is working. If you are vouching for this PR, then I can put it through. Thanks, for chiming in!

**Comment by battlemidget** [comment]
Thanks Andrew, I am vouching for these documentation changes. Thanks again

**Comment by chenopis** [comment]
@battlemidget Cool, thanks!

**Pull request merged**
