### PR TITLE
kubeadm init parameter change

### PR DESCRIPTION
**Pull request by qianmoke**
kubeadm init parameter should like :
      --api-advertise-addresses stringSlice   The IP addresses to advertise, in case autodetection fails
      --api-external-dns-names stringSlice    The DNS names to advertise, in case you have configured them yourself
      --api-port int32                        Port for API to bind to (default 6443)
      --cloud-provider string                 Enable cloud provider features (external load-balancers, storage, etc), e.g. "gce"
      --config string                         Path to kubeadm config file
      --discovery-port int32                  Port for JWS discovery service to bind to (default 9898)
      --pod-network-cidr string               Specify range of IP addresses for the pod network; if set, the control plane will automatically allocate CIDRs for every node
      --service-cidr string                   Use alternative range of IP address for service VIPs (default "10.96.0.0/12")
      --service-dns-domain string             Use alternative domain for services, e.g. "myorg.internal" (default "cluster.local")
      --skip-preflight-checks                 skip preflight checks normally run before modifying the system
      --token string                          Shared secret used to secure cluster bootstrap; if none is provided, one will be generated for you
      --use-kubernetes-version string         Choose a specific Kubernetes version for the control plane (default "v1.4.4")
not

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1708)

### CODE REVIEW

**Comment by qianmoke** [comment]
I signed it!

**Comment by devin-donnelly** [comment]
Can you please sign the updated CNCF CLA? Sorry, it's different now.

**Comment by devin-donnelly** [comment]
@qianmoke Sorry, the CLA has changed; you'll need to sign the new CNCF CLA.

**Comment by pires** [comment]
ping @qianmoke

**Comment by chenopis** [comment]
@qianmoke In order to close this PR, I'm going to reimplement these changes in PR #2368. Just sign the new Linux foundation CLA when you get a chance. Thx for your contribution!

**Pull request closed without merging**
