### PR TITLE
Doc typo

### PR DESCRIPTION
**Pull request by kelu27**
Kubenetes instead of Kubernetes

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2487)

### CODE REVIEW

**Comment by kelu27** [comment]
I signed it!

**Comment by chenopis** [comment]
@kelu27 Can you check to make sure you signed the CLA with the same email address as the one associated w/ your GitHub account? Thx

**Comment by chenopis** [comment]
P.S. Looks like the typo in docs/concepts/abstractions/overview.md was already fixed in a previous merged PR, but the one in docs/tasks/configure-pod-container/configure-liveness-readiness-probes.md is still needed. Thx

**Comment by chenopis** [comment]
These changes were covered by PRs #2526 and #2528 that have already been merged, so I'm going to close this one.

**Pull request closed without merging**
