### PR TITLE
Switch limit-range to the new task template. Add supporting yaml files.

### PR DESCRIPTION
**Pull request by nerdondon**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/3022)

### CODE REVIEW

**Comment by janetkuo** [comment]
@derekwaynecarr since you designed limit range, would you take a look?

**Comment by chenopis** [comment]
@derekwaynecarr Ping.

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
feel free to merge after rebase.

**Comment by chenopis** [comment]
@nerdondon There's a merge conflict in `docs/tasks/configure-pod-container/limit-range.md`. Once that's resolved, I can merge this PR. Thx

**Comment by nerdondon** [comment]
@chenopis resolved

**Pull request merged**
