### PR TITLE
Updated Datadog logo and added Mirantis, Giant Swarm to Tech Partner Section

### PR DESCRIPTION
**Pull request by ankurshukla**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1639)

### CODE REVIEW

**Comment by irabinovitch** [comment]
@ankurshukla  Looks like this might need a rebase?

**Comment by ankurshukla** [comment]
@irabinovitch now rebased!

**Comment by ankurshukla** [comment]
Hi

Not sure why but my pull request is failing the build (https://travis-ci.org/kubernetes/kubernetes.github.io/builds/174638275) 
Is there any more insights into what went wrong? My local branch seems to be up and running fine with my changes.

**Comment by ankurshukla** [comment]
closing this PR and will be submitting a new one.

**Comment by pwittrock** [comment]
@ankurshukla Please squash the commits and I will merge

**Comment by ankurshukla** [comment]
I just rebased my changes, Can you try now. Seems to be some issues with my repo. If this doesnt work, would have to create a new PR. 
apologies on my handicap with github :(

**Comment by pwittrock** [comment]
You will need to do something like

`git rebase -i HEAD~11` and then change the commits to fix ups.  Then repush with `git push <remote> <branch> --force`

**Comment by ankurshukla** [comment]
just did it, Thanks  :) my 2FA was causing issues that why rebasing didnt worked!

**Comment by pwittrock** [comment]
Looks like there are still 13 commits

**Comment by ankurshukla** [comment]
rebased and pushed again.

screen shot 2016-11-15 at 11 25 07

**Comment by ankurshukla** [comment]
I did the commits myself. Just had to generate a new access token to push the changes. Please add the Google CLA back. Screenshot attached in previous comment for reference.

**Comment by pwittrock** [comment]
Look at the commits.  Something seems very broken.

**Comment by ankurshukla** [comment]
yeah....my whole workspace seems a bit off now, due to continually adding commits to an open PR. Lemme start over, probably easy and cleaner than fixing and re-rebasing.
Apologies for all the inconveniences.

**Comment by pwittrock** [comment]
@ankurshukla No problem, but I think it might be worth your time to better understand the git workflow.

I would do this:

`git fetch upstream`
`git rebase upstream/master`
`git rebase -i HEAD~3`

> Squash the commits in the editor

`git push origin master`

Then see what happens

**Comment by ankurshukla** [comment]
closing this PR. Will submit a new (and tested) one.

**Pull request closed without merging**
