### PR TITLE
Update configure-pod-configmap.md

### PR DESCRIPTION
**Pull request by serrien**
Setting correct key for LOG_LEVEL env value

> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.7 Features: set Milestone to `1.7` and Base Branch to `release-1.7`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> NOTE: Please check the “Allow edits from maintainers” box below to allow 
> reviewers fix problems on your patch and speed up the review process.
> Please delete this note before submitting the pull request.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4017)

### CODE REVIEW

**Comment by SebErrien** [comment]
Hi, I signed the Contributor License Agreement.

**Comment by chenopis** [comment]
@SebErrien Can you check to make sure the commit for this PR uses the same email address as the one you used to sign the CLA? Thx

**Comment by SebErrien** [comment]
Hi, I checked licence agreement, I omitted to sign. It's done now.

**Comment by ahmetb** [comment]
@Random-Liu can you please review?

**Comment by chenopis** [comment]
Deploy preview ready!

Built with commit 4f850e3d0b1b24c056e4c9fa033e077fae7fda29

https://deploy-preview-4017--kubernetes-io-master-staging.netlify.com

**Comment by chenopis** [comment]
@Random-Liu @timstclair Can one of you quick verify that the key should be `log_level` and give a tech lgtm? Thx

**Comment by steveperry-53** [comment]
I'm just going to go ahead and vouch for the technical accuracy of this. It looks fine.

**Comment by steveperry-53** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/4017#-:-Kt_2fVzZfjvIXa7xAe5:bnfp4nl)*

**Pull request merged**
