### PR TITLE
Applying template to Namespaces topic and moving to Tasks.

### PR DESCRIPTION
**Pull request by iphutch**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2925)

### CODE REVIEW

**Comment by iphutch** [comment]
@steveperry-53 please review

**Comment by steveperry-53** [comment]
The new doc has this: {% include code.html language="json" file="namespace-dev.json" ghlink="/docs/admin/namespaces/namespace-dev.json" %}

Change the ghlink to "/docs/tasks/administer-cluster/namespace-dev.json". Then copy namespace-dev.json from docs/admin/namespaces/ to docs/tasks/administer-cluster/.

NOTE
Under Show all checks, we can see that the deploy/netlify preview failed. To investigate, you can use this command on your local machine.

docker run -ti --rm -v "$PWD":/k8sdocs -p 4000:4000 gcr.io/google-samples/k8sdocs:1.0

Output:
 Liquid Exception: Could not locate the included file 'namespace-dev.json' in any of ["/k8sdocs/docs/tasks/administer-cluster"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in docs/tasks/administer-cluster/namespaces.md
jekyll 3.3.1 | Error:  Could not locate the included file 'namespace-dev.json' in any of ["/k8sdocs/docs/tasks/administer-cluster"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.

**Comment by chenopis** [comment]
@iphutch Looks like we're pretty close. If you can fix the `namespace-dev.json` code snippet link in `/docs/tasks/administer-cluster/namespaces.md` and resolve the merge conflicts, we should be good to go for a merge.

**Comment by chenopis** [comment]
@steveperry-53 @iphutch Since things have moved around a bit, what do we want to do w/ this PR?

**Comment by steveperry-53** [comment]
@chenopis, I think the location of /docs/tasks/administer-cluster/namespaces.md is OK. I don't think we need the intermediate page in user-guide; I think we can just redirect the old topic to the new.

@iphutch, If you would like us to finish this up and get it published, check the **Allow Edits by Maintainers** check box.  Thanks.

**Comment by iphutch** [comment]
@steveperry-53 Done. Maintainers now have edit rights. Thanks.

**Comment by chenopis** [comment]
I'll work on resolving the merge issues and finishing this PR. Thanks @iphutch!

**Comment by chenopis** [comment]
@iphutch Was the contents of namespaces-walkthrough.md merged into namespaces.md? I wasn't sure when I was resolving the conflicts whether namespaces-walkthrough.md should be deleted or not.

**Pull request merged**
