### PR TITLE
Add missing commas, fix typos

### PR DESCRIPTION
**Pull request by hyunchel**
I did not try to correct *English* - as I'm not a good writer myself.
The commas seem to be necessary, however, to comprehend the sentences.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1139)

### CODE REVIEW

**Comment by jaredbhatti** [comment]
Hey there, can you rebase?  Otherwise, LGTM

**Comment by devin-donnelly** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/user-guide/horizontal-pod-autoscaling/index.md, line 123 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1139#-KQXeLV73CMpl8cjPLQd:-KQXeJAhTz8nxCDtKm4B:b55nn0x) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/bf53f13665f1d448cee48a9104f830f84030e691/docs/user-guide/horizontal-pod-autoscaling/index.md#L123)):*
> ```Markdown
> ```
> 
> In this case, if there are 4 pods running and each of them reports qps metric to be equal to 15, HPA will start 2 additional pods so there will be 6 pods in total. If there are multiple metrics passed in the annotation or CPU is configured as well then HPA will use the biggest 
> ```

"In this case, if there are four pods running and each pods reports a QPS metric of 15 or higher, horizontal pod autoscaling will start two additional pods (for a total of six pods running).

If you specify multiple metrics in your annotation or if you set a target CPU utilization, horizontal pod autoscaling will scale to according to the metric that requires the highest number of replicas.

---

*[docs/user-guide/horizontal-pod-autoscaling/index.md, line 126 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1139#-KQXfBLi0gKUvbAX-5Ho:-KQXfBLi0gKUvbAX-5Hp:befksfp) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/bf53f13665f1d448cee48a9104f830f84030e691/docs/user-guide/horizontal-pod-autoscaling/index.md#L126)):*
> ```Markdown
> number of replicas that comes from the calculations.
> 
> At this moment, even if CPU utilization target is not specified, a default of 80% will be used. 
> ```

If you do not specify a target for CPU utilization, Kubernetes defaults to an 80% utilization threshold for horizontal pod autoscaling.

---

*[docs/user-guide/horizontal-pod-autoscaling/index.md, line 127 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1139#-KQXfJTThjtmH6SjaFyP:-KQXfJTThjtmH6SjaFyQ:b8gqrz2) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/bf53f13665f1d448cee48a9104f830f84030e691/docs/user-guide/horizontal-pod-autoscaling/index.md#L127)):*
> ```Markdown
> 
> At this moment, even if CPU utilization target is not specified, a default of 80% will be used. 
> To calculate number of desired replicas based only on custom metrics, CPU utilization
> ```

If you want to ensure that horizontal pod autoscaling calculates the number of required replicas based only on custom metrics, you should set the CPU utilization target to a very large value (such as 100000%). As this level of CPU utilization isn't possible, horizontal pod autoscaling will calculate based only on the custom metrics (and min/max limits).

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1139)*

**Comment by hyunchel** [comment]
Thanks for the review! 
I rebased this branch on master, added a commit to update the sentences, and force pushed this branch.

**Comment by devin-donnelly** [comment]
Thanks! I accidentally had a typo in one of my suggested edits, though; I'll leave a review comment. Sorry about that! As soon as it's fixed we can merge.

**Comment by devin-donnelly** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/user-guide/horizontal-pod-autoscaling/index.md, line 123 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1139#-KQhEE51c86F3WT32sgG:-KQhEE51c86F3WT32sgH:bqcnpz1) ([raw file](https://github.com/kubernetes/kubernetes.github.io/blob/855d3fae5c2c5c1be272369f9114e03916b4e494/docs/user-guide/horizontal-pod-autoscaling/index.md#L123)):*
> ```Markdown
> ```
> 
> In this case, if there are four pods running and each pods reports a QPS metric of 15 or higher, horizontal pod autoscaling will start two additional pods (for a total of six pods running).
> ```

each pods -> each pod

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes.github.io/1139)*

**Comment by hyunchel** [comment]
No you are good! I should have done more than copy & paste.
The typo is fixed. Please review this one more time 🙇

**Comment by devin-donnelly** [comment]
Docs LGTM! Thanks; I'll go ahead and merge this in.

**Pull request merged**
