### PR TITLE
Import guestbook tutorial and manifest files

### PR DESCRIPTION
**Pull request by ahmetb**
/assign @cody-clark please review the layout/rendering

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4631)

### CODE REVIEW

**Comment by ahmetb** [comment]
@chenopis Is there a way to figure out why netlify preview has failed?

**Comment by cody-clark** [comment]
@ahmetb It looks like it can't find the manifest files:

> > Error: Could not locate the included file 'redis-master-deployment.yaml' in any of ["/opt/build/repo/docs/tutorials/stateless-application"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.

Could it be be because we're putting them in a new folder (/docs/tutorials/stateless-application/guestbook/)? The Cassandra example worked when we just left the manifest files in the same directory as the .md file (/docs/tutorials/stateful-application/).

**Comment by ahmetb** [comment]
@cody-clark I think it's because of this:

    {% include code.html language="yaml" file="redis-master-deployment.yaml"

it should be saying `file="guestbook/redis-master-deployment.yaml"`. I'll fix.

**Comment by ahmetb** [comment]
fixed now.

**Comment by cody-clark** [comment]
It seems that liquid tags behave differently from code blocks so the numbering is still interrupted even if indented. I'll need to find a way maintain the numbering other than the {:start="#"} tag. [Definition lists](https://stackoverflow.com/questions/17995467/how-can-i-put-a-liquid-tag-highlight-in-an-ordered-list) might be a solution.

Also, I'll fix the prereq download links.

**Comment by ahmetb** [comment]
We can merge and fix later. It seems like a low-priority problem to me.

**Comment by cody-clark** [comment]
Agreed.

**Comment by ahmetb** [comment]
@chenopis this is ready to review.

**Comment by cody-clark** [comment]
We need [PR #56](https://github.com/kubernetes/examples/pulls) from the examples repo to be merged so the pre

**Pull request merged**
