### PR TITLE
Change heading levels

### PR DESCRIPTION
**Pull request by craigbox**
Make consistent with heading CSS changes made pre-Xmas.  Please see published sample.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2244)

### CODE REVIEW

**Comment by craigbox** [comment]
Please don't commit yet - this is an example for a discussion around "should headings start at <h2> or <h3>"

**Comment by jaredbhatti** [comment]
@steveperry-53   What's your progress on this?

**Comment by steveperry-53** [comment]
@jaredbhatti, This work was done some time ago in https://github.com/kubernetes/kubernetes.github.io/pull/2287.

@craigbox, Can we just close this?

**Comment by jaredbhatti** [comment]
Thanks Steve!

**Comment by jaredbhatti** [comment]
Pinged Craig, he said "go ahead and close"

**Pull request closed without merging**
