### PR TITLE
update imported docs

### PR DESCRIPTION
**Pull request by mengqiy**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5656)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@mengqiy Should we add an entry to _data/reference.yaml, so that this topic shows in the left nav.
Something like this?

- title: Cloud Controller Manager
  section:
  - docs/admin/cloud-controller-manager

**Comment by steveperry-53** [comment]
@mengqiy Do you want someone to do a tech review? Or is a docs review good enough?

**Comment by mengqiy** [comment]
> Should we add an entry to _data/reference.yaml, so that this topic shows in the left nav.

Good point.
Can you add that in a followup PR, should be trivial. I will be OOO for several days (starting today) with limited availability. So if this PR does have big issue, I suggest to merge it as is. 

> Do you want someone to do a tech review? Or is a docs review good enough?

I have checked the content should be what I expected.

**Comment by mengqiy** [comment]
I have experienced the pain to tweak the update-imported-files.sh to work again. I will definitely rewrite it maybe in go before 1.9 release for sure!

**Pull request merged**
