### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by scjane**
Line 70 is where I modified. But I don't know why line 1-6 also have additions or deletions as shown below😏

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2308)

### CODE REVIEW

**Comment by chenopis** [comment]
@scjane Looks like there were some invisible characters that got added to lines 3 and 4. Are you using the site's built-in editor or via a Git client? If you're unable to fix it, you might want to just close this and redo it in a different PR.

**Comment by chenopis** [comment]
Looks like it should be okay.

**Comment by scjane** [comment]
@chenopis I'm using the site's built-in editor.

**Comment by chenopis** [comment]
Thanks @scjane . I think I was reading the diff wrong initially. Looks like those invisible characters were introduced in a previous change and the site's built-in editor was stripping them out automatically when you submitted your change, so all is well.

**Pull request merged**
