### PR TITLE
Adds a Kubernetes overview diagram using UML elements.

### PR DESCRIPTION
**Pull request by wernight**
Overview of Kubernetes work units created using Lucidchart (see also bugs #84).

### CODE REVIEW

**Comment by wernight** [comment]
I signed it! I think I'm already under the CLA.

**Comment by johndmulhausen** [comment]
I really appreciate this diagram! It's a little stick-figurey. As issue #84 states, we are supposed to be using a common set of assets for diagram creation:

https://docs.google.com/presentation/d/13klSkUQI9yPxKckP8UFLpzzKzxYwv1lit9ELWOnXJFM/edit#slide=id.p15

I hate to ask you to recreate this, but can you use the assets in this slide deck, please? You can just copy/paste/drag drop from within a copy of the slide deck, then use a Google Drawing (which is just another free document type in Google Drive) to copy/paste the final diagram and produce a cropped SVG.

Note to tech reviewers: You have to use the "view" button to see the SVG contents as an image, or just click this link:
https://github.com/wernight/kubernetes.github.io/blob/2ced103b4db94c402c498d603e9268b32e0c0ff2/images/overview_uml.svg

**Comment by wernight** [comment]
@johndmulhausen I used the font and colors. The rest is a UML deployment diagram (with some of class diagram). The example you linked to seem to be more a data flow diagram without clear multiplicities. Which part exactly do you want to see changed? The blocks' style? The lines? The color of the lines?

**Comment by wernight** [comment]
@johndmulhausen Any comment?

**Comment by wernight** [comment]
@johndmulhausen Please comment.

**Comment by johndmulhausen** [comment]
What I linked to was a slide deck full of diagram assets that can be used to create many kinds of diagrams. UML is not necessarily the best way to illustrate Kubernetes in a high-level overview. Conceptual diagrams are best, with simple notation. Please use the assets in the slide deck.

**Comment by wernight** [comment]
Ok made a version with the given assets but I feel it lacks a lot of the details of the UML diagram (like multiplicities and inheritance), also data flow is a bit odd to me as in which direction is a pull request?

https://docs.google.com/presentation/d/1kup1NiYM62qBeaT0A6G6tZ48uXMb2CRETSpeGafFRxw/edit?usp=sharing

**Comment by wernight** [comment]
Any update?

**Comment by kelseyhightower** [comment]
I'm going to merge this because people might find this image useful. Seems harmless because we don't link to it anywhere.

**Pull request merged**
