### PR TITLE
Correct hyphenation of net.beta.kubernetes.io/network-policy

### PR DESCRIPTION
**Pull request by matthewdupre**
networkpolicy should be network-policy (like the yaml example above).

I didn't find any other examples of this particular typo in this repo.

### CODE REVIEW

**Comment by pwittrock** [comment]
@saad-ali Who should take a look at network policy stuff?

**Comment by saad-ali** [comment]
> @saad-ali Who should take a look at network policy stuff?

Assign to @matchstick, he can reassign to someone on the networking team.

**Comment by pwittrock** [comment]
@matchstick Any good candidates for this?

**Comment by matchstick** [comment]
@girishkalele PTAL

**Comment by matchstick** [comment]
Sorry I am new to the process and did not know it needed two LGTMs.

**Pull request merged**
