### PR TITLE
Create a top-level CN directory to hold md files for the Chinese Kubernetes site

### PR DESCRIPTION
**Pull request by xinzhangcmu**
Per email discussion with @dankohn (dan@linuxfoundation.org), we are planing to (re)initiate the efforts to build the Chinese version of the kubernetes.io site; we are hoping to get it done before the Linuxcon + Containcon + CloudOpen in June in Beijing, China (http://events.linuxfoundation.org/events/linuxcon-containercon-cloudopen-china)

The agreed first step between Dan and I is to create this top-level cn directory, where future md files in Chinese will reside. 

After this PR, the discussed plan is that we (Caicloud, a Kubernetes-based startup in China) will make the initial thrust while pulling together the Chinese community to carry out the project before June this year.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2715)

### CODE REVIEW

**Comment by xinzhangcmu** [comment]
I signed it!

**Comment by chenopis** [comment]
@xinzhangcmu The CLA check is still not coming through. Can you make sure you signed it using the same email address that is associated w/ your GitHub account? Also, I'm only seeing an empty `cn/docs/.gitkeep` file in this PR. Is that the placeholder for the directory you mentioned?

**Comment by xinzhangcmu** [comment]
@chenopis Thanks for the prompt review! Yeah, I was planning to first create the placeholder (i.e., the empty dir) so that people can incrementally translate pages in there.

I updated my local git config --global user.email to match the email address I used to sign CLA, seems like I need to do some commit pushing to make it effective?

**Comment by chenopis** [comment]
@xinzhangcmu I think you will need to rewrite the email for the previous commit, see: http://stackoverflow.com/questions/2919878/git-rewrite-previous-commit-usernames-and-emails

**Comment by xinzhangcmu** [comment]
@chenopis cla issues should have been resolved, PTAL :)

**Pull request merged**
