### PR TITLE
 Fix for redundant footer section in home page.

### PR DESCRIPTION
**Pull request by aneeshep**
This commit removes redundant footer section in the Home page.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/2398)

### CODE REVIEW

**Comment by aneeshep** [comment]
I signed it!

**Comment by aneeshep** [comment]
I signed it!

**Comment by aneeshep** [comment]
I signed it!

**Comment by chenopis** [comment]
@aneeshep The Netlify preview seems to be broken. Can you rebase again to trigger it to redeploy a preview? Thx

**Comment by aneeshep** [comment]
@chenopis Can you check now? does it looks okay?

**Comment by chenopis** [comment]
@aneeshep Yes, I can see the preview now. Thx!

**Pull request merged**
