### PR TITLE
Interactive Tutorials: Having .html in URL causes a 404 before redirecting

### PR DESCRIPTION
**Pull request by BenHall**
I noticed on the Interactive Tutorials that having the .html in the URL was causing a 404 to be displayed before it redirected. 

Reproduce:
1) Visit http://kubernetes.io/docs/tutorials/getting-started/create-cluster/
2) Scroll to the bottom, click Start Module 1.
3) 404 page display for a moment, before redirecting.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1380)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
This is a known issue with the entire Kubernetes site. However, this PR is about to cause some merge conflicts with a larger fix; let's hang onto it for now.

**Comment by devin-donnelly** [comment]
@BenHall, as I suspected, there are a bunch of merge conflicts now. We can just close this PR and fix it with a different one, or you could update this one. What do you think?

**Comment by BenHall** [comment]
@devin-donnelly I've updated my branch with the upstream changes.

**Comment by devin-donnelly** [comment]
Still one merge conflict and, unfortunately, there's a new (second) CLA you'll need to sign.

**Comment by BenHall** [comment]
Updated the merge conflict and signed the CLA

**Pull request merged**
